Allow x509 crt error strings to be used externally
Mbed-TLS/mbedtls pull request #3692
Opened 2020-09-18 21:24 UTC by rcr

The motivation for this patch is to allow for iteration over the
error strings against the return from mbedtls_ssl_get_verify_results
directly. Currently to report multiple errors in a linewise fashion,
I call mbedtls_x509_crt_verify_info with a dummy prefix, and then
parse out this prefix and newlines from the buffer.

Signed-off-by: Richard Robbins <mail@rcr.io>

## Requires Backporting
No

## Migrations
No

2020-09-21 15:24 UTC, ronald-cron-arm requested changes
Thanks for your interest in Mbed TLS. I've done just a cursory review and spotted one small thing. Otherwise, the check-names.sh test script is returning in error. Could you please have a look?

2020-09-21 15:24 UTC, ronald-cron-arm commented on include/mbedtls/x509_crt.h
> +mbedtls_crt_verify_string;
You need a "_t" suffix when defining a type.

2020-09-21 15:38 UTC, ronald-cron-arm commented
Otherwise, why passing an empty string as prefix to `mbedtls_x509_crt_verify_info()` does not do the job?

2020-09-21 15:45 UTC, ronald-cron-arm commented
We will probably need a better explanation of your use case to decide whether we want to go with this or not. I don't know in depth the interface involved but it seems that one of the purpose of `mbedtls_x509_crt_verify_info()` is to avoid exposing directly the table of error messages.

2022-05-06 10:31 UTC, daverodgman commented
Closing - exposing the list of error strings doesn't seem like something we'd want to support in our API.

2022-05-06 10:31 UTC, closed without merging