fix issue #2020
Mbed-TLS/mbedtls pull request #4686
Opened 2021-06-18 17:07 UTC by Kazuyuki-Kimura

Fixed a bug that the little-endian Microblaze does not work when MBEDTLS_HAVE_ASM is defined.

I accidentally closed #4586.... sorry.

Signed-off-by: Kazuyuki Kimura <kim@wing.ocn.ne.jp>

2021-07-31 16:18 UTC, gilles-peskine-arm reviewed
Makes sense to me. I haven't reviewed the code for any other similar issues. I have not run any tests (as you're undoubtedly aware of, we do not have any testing on Microblaze).

Since this is a bug fix, it needs a changelog entry. Can you please create a file `ChangeLog.d/bignum-little-endian-microblaze.txt` containing something like
```
Bugfix
   * Fix bignum multiplication (and therefore asymmetric cryptography) on
     little-endian Microblaze when MBEDTLS_HAVE_ASM is enabled. Fixes #2020.
```

2022-05-13 12:15 UTC, daverodgman requested changes
Please add a Changelog

2022-05-30 16:38 UTC, daverodgman commented
This addresses the same issue as #5580 - although I think (but am not sure) that 5580 doesn't properly fix for both endiannesses, whereas this clearly has a code path for both big and little endian. So superficially it looks like this might be the preferred fix.

2022-05-30 16:51 UTC, daverodgman commented
Rebased and Changelog added. @Kazuyuki-Kimura or @Eurecam-Benjamin please could you test and confirm that addresses the issue? Ideally we also need a 2.28 backport. Thanks.

2022-07-29 10:40 UTC, daverodgman commented
Discussed in historical review; we agreed this is OK to merge without being able to properly test.

2022-07-29 11:13 UTC, tom-cosgrove-arm commented on library/bn_mul.h
> +#define MULADDC_X1_CORE                    \
annoying that the trailing `\` doesn't line up, but ah well

2022-07-29 11:14 UTC, tom-cosgrove-arm approved these changes
LGTM

2022-07-29 16:08 UTC, merged