Implemented mbedtls_net_connect_timeout
Mbed-TLS/mbedtls pull request #4837
Opened 2021-08-03 18:24 UTC by minego

Implemented an alternative form of mbedtls_net_connect which takes a timeout
argument.

Signed-off-by: Micah N Gorrell <micah.gorrell@venafi.com>

Notes:
* Pull requests cannot be accepted until the PR follows the [contributing guidelines](../CONTRIBUTING.md). In particular, each commit must have at least one `Signed-off-by:` line from the committer to certify that the contribution is made under the terms of the [Developer Certificate of Origin](../dco.txt).
* This is just a template, so feel free to use/remove the unnecessary things
## Description
A few sentences describing the overall goals of the pull request's commits.

## Status
**READY**

## Requires Backporting
NO

## Migrations
If there is any API change, what's the incentive and logic for it.

NO

## Additional comments

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog updated
- [ ] Backported

## Steps to test or reproduce
Outline the steps to test or reproduce the PR here.

2021-08-03 19:27 UTC, gilles-peskine-arm requested changes
Thank you for your contribution! I've done a design review, not a full code review.

2021-08-03 19:27 UTC, gilles-peskine-arm commented on include/mbedtls/net_sockets.h
> +int mbedtls_net_connect_timeout( mbedtls_net_context *ctx, const char *host, const char *port, int proto, int timeout );
Please make this `uint32_t timeout` for compatibility with `mbedtls_net_recv_timeout`. Also, please implement and document that 0 means to wait forever — it's not logical, but I think it's better for the module to be uniform.

2021-08-03 19:27 UTC, gilles-peskine-arm commented on include/mbedtls/net_sockets.h
> + * \brief          Initiate a connection with host:port in the given protocol with a timeout
Please create a changelog entry file in `Changelog.d` announcing the new function (see “Features” entries in `ChangeLog` for similar examples).

2021-08-03 19:27 UTC, gilles-peskine-arm commented on library/net_sockets.c
> +{
Most of the code is copied from `mbedtls_net_connect`. Code duplication is bad for maintenance (and also wastes code size). Please change `mbedtls_net_connect` to be a backward compatibility wrapper for calling the new function with timeout=0.

2021-08-03 19:51 UTC, minego commented
Thank you. It can be intimidating trying to contribute to a project like this, so clear requests like this are greatly appreciated. I've pushed changes to the PR based on your feedback.

Thanks,
Micah

On Tue, Aug 3, 2021, at 1:27 PM, Gilles Peskine wrote:
> 
> 
> ***@***.**** requested changes on this pull request.
> 
> Thank you for your contribution! I've done a design review, not a full code review.
> 
> 
> In include/mbedtls/net_sockets.h <https://github.com/ARMmbed/mbedtls/pull/4837#discussion_r682039106>:
> 
> > + * \brief          Initiate a connection with host:port in the given protocol with a timeout
> + *
> + * \param ctx      Socket to use
> + * \param host     Host to connect to
> + * \param port     Port to connect to
> + * \param proto    Protocol: MBEDTLS_NET_PROTO_TCP or MBEDTLS_NET_PROTO_UDP
> + * \param timeout  The timeout in milliseconds
> + *
> + * \return         0 if successful, or one of:
> + *                      MBEDTLS_ERR_NET_SOCKET_FAILED,
> + *                      MBEDTLS_ERR_NET_UNKNOWN_HOST,
> + *                      MBEDTLS_ERR_NET_CONNECT_FAILED
> + *
> + * \note           Sets the socket in connected mode even with UDP.
> + */
> +int mbedtls_net_connect_timeout( mbedtls_net_context *ctx, const char *host, const char *port, int proto, int timeout );
> 
> Please make this `uint32_t timeout` for compatibility with `mbedtls_net_recv_timeout`. Also, please implement and document that 0 means to wait forever — it's not logical, but I think it's better for the module to be uniform.
> 
> 
> In include/mbedtls/net_sockets.h <https://github.com/ARMmbed/mbedtls/pull/4837#discussion_r682039565>:
> 
> > @@ -123,6 +123,24 @@ void mbedtls_net_init( mbedtls_net_context *ctx );
>   */
>  int mbedtls_net_connect( mbedtls_net_context *ctx, const char *host, const char *port, int proto );
>  
> +/**
> + * \brief          Initiate a connection with host:port in the given protocol with a timeout
> 
> Please create a changelog entry file in `Changelog.d` announcing the new function (see “Features” entries in `ChangeLog` for similar examples).
> 
> 
> In library/net_sockets.c <https://github.com/ARMmbed/mbedtls/pull/4837#discussion_r682040427>:
> 
> > @@ -216,6 +216,128 @@ int mbedtls_net_connect( mbedtls_net_context *ctx, const char *host,
>      return( ret );
>  }
>  
> +/*
> + * Initiate a TCP connection with host:port and the given protocol with a timeout (ms)
> + */
> +int mbedtls_net_connect_timeout( mbedtls_net_context *ctx, const char *host,
> +                         const char *port, int proto, int timeout )
> +{
> 
> Most of the code is copied from `mbedtls_net_connect`. Code duplication is bad for maintenance (and also wastes code size). Please change `mbedtls_net_connect` to be a backward compatibility wrapper for calling the new function with timeout=0.
> 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/ARMmbed/mbedtls/pull/4837#pullrequestreview-721565354>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AADSRCFSCWQIUK7NBAN2LFLT3A7LLANCNFSM5BPLXZBA>.
> Triage notifications on the go with GitHub Mobile for iOS <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>.
>

2021-08-11 12:33 UTC, mstarzyk-mobica requested changes

2021-08-11 12:33 UTC, mstarzyk-mobica commented on library/net_sockets.c
> +				{
unhandled `ret == -1 && errno != EINTR`

2021-08-11 12:33 UTC, mstarzyk-mobica commented on library/net_sockets.c
> +				ret = select( fd + 1, NULL, &write_fds, &error_fds, timeout == 0 ? NULL : &tv );
from: https://man7.org/linux/man-pages/man2/select.2.html
```
WARNING: select() can monitor only file descriptors numbers that
       are less than FD_SETSIZE (1024)—an unreasonably low limit for
       many modern applications—and this limitation will not change.
       All modern applications should instead use poll(2) or epoll(7),
       which do not suffer this limitation.
```

2021-08-11 12:33 UTC, mstarzyk-mobica commented on library/net_sockets.c
> +						ret = MBEDTLS_ERR_NET_CONNECT_FAILED;
not sure about this error, maybe MBEDTLS_ERR_NET_SOCKET_FAILED would better here?

2021-08-11 12:33 UTC, mstarzyk-mobica commented on library/net_sockets.c
>          close( ctx->fd );
Closing same fd twice:
 - lines 268 and 278
 - here
 
Either:
-  Prepare a `goto` exit 
or
- After closing `fd` set it to a known magic value (-1 does the trick). Before closing it second time, check if it's value is not equal to magic (-1)

2021-08-11 12:33 UTC, mstarzyk-mobica commented on library/net_sockets.c
> +				ret = select( fd + 1, NULL, &write_fds, &error_fds, timeout == 0 ? NULL : &tv );
However, `select()` is widely used in this module, so I guess it's alright to use it here as well. Perhaps it should be addressed in separate PR (if at all)

2021-08-11 12:33 UTC, mstarzyk-mobica commented on include/mbedtls/net_sockets.h
> + * \param timeout  Maximum number of milliseconds to wait for a connection
Mention select()'s timeout granularity.
From https://man7.org/linux/man-pages/man2/select.2.html
```
Note that the timeout interval will be rounded up to the
              system clock granularity, and kernel scheduling delays
              mean that the blocking interval may overrun by a small
              amount.
```

2021-08-30 11:08 UTC, gilles-peskine-arm commented on library/net_sockets.c
> +				ret = select( fd + 1, NULL, &write_fds, &error_fds, timeout == 0 ? NULL : &tv );
Please call `check_fd(fd, 1)` before calling `select`, as is done in other functions that call `select`. And please add a non-regression test (similar to `poll_beyond_fd_setsize`) in `test_suite_net` to ensure that in case `connect` returns a file descriptor that's out of range, the outcome is that the function returns an error, not a buffer overflow.

We use `select` for maximum portability: some embedded OSes have `select` but not `poll`. There's no option to use `poll` where available because nobody has done the work to .

2021-09-28 13:05 UTC, daverodgman commented
Hi @minego - are you able to take a look at these review comments? Thanks

2023-06-02 11:35 UTC, tom-daubney-arm commented
We are now converting older PRs to draft PRs where the following conditions are met: They have not been updated in the last 3 months, and they need more than non-trivial work to complete.

2023-06-08 17:16 UTC, davidhorstmann-arm commented
@minego would you mind if I took this PR over to try and push it across the line?

2023-06-08 17:19 UTC, minego commented
That would be great. It hasn't been a big priority for me, but it would be great to get it in.

Thank you.

On Thu, Jun 8, 2023, at 11:17 AM, David Horstmann wrote:
> 
> 
> @minego <https://github.com/minego> would you mind if I took this PR over to try and push it across the line?
> 
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/Mbed-TLS/mbedtls/pull/4837#issuecomment-1583053004>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AADSRCEY5PTVMHXII52D37DXKICJBANCNFSM5BPLXZBA>.
> You are receiving this because you were mentioned.Message ID: ***@***.***>
>

2023-06-09 12:38 UTC, davidhorstmann-arm commented
Since 3rd party edits don't seem to be enabled on this PR, I've rebased and reopened this as #7724.

2023-06-09 12:38 UTC, closed without merging