Pr/move opt tests out of ssl opt
Mbed-TLS/mbedtls pull request #5244
Opened 2021-11-30 05:51 UTC by yuhaoth

## Description
Try move ssl-opt tests to subdirectory
## Status
**IN DEVELOPMENT**

2022-05-05 12:28 UTC, RcColes commented on tests/ssl-opt.sh
> -
Posix shell substitution is arcane knowledge at best - it would be better if there were some comments for these lines to be clear what they're doing

2022-05-09 03:58 UTC, yuhaoth commented
rebase and resolve conflicts

2022-05-30 07:34 UTC, yuhaoth commented
resolve conflict

2022-07-06 14:38 UTC, gabor-mezei-arm requested changes

2022-09-27 02:56 UTC, yuhaoth commented
Too old

2022-09-27 02:56 UTC, closed without merging