misc: add helper tools for generate config headers
Mbed-TLS/mbedtls pull request #5470
Opened 2022-01-27 03:22 UTC by yuhaoth

tls1.3 only mode need enable/disable many options.
With MBEDTLS_USER_CONFIG_FILE feature, we can add a header
file to easy the test.

This utils is to save local config change as a header file.
That can reduce the work load for generate new user config file

It is used for #5362 
## Status
**READY**

## Steps to test or reproduce
Outline the steps to test or reproduce the PR here.

2022-03-02 18:58 UTC, gilles-peskine-arm commented on scripts/generate_config.py
> +"""Mbed TLS user configuration file generate.
Please document what this script does.

Without knowing what this is supposed to do, it's impossible to review.

2022-03-11 12:49 UTC, gilles-peskine-arm commented
Sorry, I can't commit to reviewing this before mid-April.

2022-05-02 14:52 UTC, gabor-mezei-arm requested changes

2022-05-02 14:52 UTC, gabor-mezei-arm commented on scripts/generate_config.py
> +        return False, m['name'], ''
```suggestion
        return False, m['name'], ''

```
Add a new line for better separation.

2022-05-02 14:52 UTC, gabor-mezei-arm commented on scripts/generate_config.py
> +            yield from i.target_lines()
```suggestion
            yield from i.target_lines()

```
Add a new line for better separation.

2022-05-02 14:52 UTC, gabor-mezei-arm commented on scripts/generate_config.py
> +                '{name} has been added in argument'.format(**locals())
The same checks done twice. Should be moved to a function.

2022-07-01 14:14 UTC, gabor-mezei-arm submitted a review, later dismissed
LGTM

2022-07-09 05:41 UTC, yuhaoth commented
rebased

2022-09-19 14:53 UTC, gabor-mezei-arm submitted a review, later dismissed
LGTM

2022-09-27 02:21 UTC, yuhaoth commented
Rebased to clear CI fail flag

2022-10-19 16:02 UTC, gabor-mezei-arm approved these changes
LGTM

2023-06-16 12:16 UTC, tom-cosgrove-arm commented
Hi Jerry, I'm sorry, but after discussing with Dave and the other historical reviewers, we feel that there isn't a burning need for something like this, and anyway it would be better in `config.py` if anywhere, so I am closing this PR

2023-06-16 12:16 UTC, closed without merging