Fixed undefined behavior in ssl_read if buf parameter is NULL.
Mbed-TLS/mbedtls pull request #5527
Opened 2022-02-10 21:11 UTC by ashesman

Signed-off-by: Ashley Duncan <ashes.man@gmail.com>

Notes:
* Pull requests cannot be accepted until the PR follows the [contributing guidelines](../CONTRIBUTING.md). In particular, each commit must have at least one `Signed-off-by:` line from the committer to certify that the contribution is made under the terms of the [Developer Certificate of Origin](../dco.txt).
* This is just a template, so feel free to use/remove the unnecessary things
## Description
A few sentences describing the overall goals of the pull request's commits.

Fixed call of memcpy  with NULL destination pointer when mbedtls_ssl_read is called with buf parameter == NULL

Refer to issue https://github.com/ARMmbed/mbedtls/issues/3076

This situation could be unit tested by calling mbedtls_ssl_read(ctx, NULL, 0);  Unfortunately I do not have a good enough understanding of the test framework to write a good quality test.

NOTE: mbedtls_ssl_read can be called with buf == NULL to force a read from lower level buffer into tls buffers without actually returning any data.  This is useful for performing an update before asking how much data is ready to be read.

## Status
**READY/IN DEVELOPMENT/HOLD**

## Requires Backporting
When there is a bug fix, it should be backported to all maintained and supported branches.
Changes do not have to be backported if:
- This PR is a new feature\enhancement
- This PR contains changes in the API. If this is true, and there is a need for the fix to be backported, the fix should be handled differently in the legacy branch

Yes | NO  
Which branch?

## Migrations
If there is any API change, what's the incentive and logic for it.

YES | NO

## Additional comments
Any additional information that could be of interest

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog updated
- [ ] Backported

## Steps to test or reproduce
Outline the steps to test or reproduce the PR here.

2022-02-10 23:01 UTC, gilles-peskine-arm requested changes
* This needs a changelog entry (see `Changelog.d/00README.md`).
* I think `mbedtls_ssl_write` needs a similar patch.
* We do need a non-regression test.

2022-02-10 23:01 UTC, gilles-peskine-arm commented on library/ssl_msg.c
> +    if ( buf )
If `buf == NULL` but `len != 0`, that's a user error.
```suggestion
    if ( len != 0 )
```

2022-02-16 22:16 UTC, ashesman commented
> * This needs a changelog entry (see `Changelog.d/00README.md`).
Done
> * I think `mbedtls_ssl_write` needs a similar patch.
I dont think mbedtls_ssl_write requires the same fix mbedtls_ssl_write does have the same unchecked memcpy but I would argue that if you consider passing NULL to mbed_ssl_read is 'user error', then passing buf==NULL or len==0 to the write function would also be a user error. 
Although any situation where an unchecked pointer access could be checked preventing a potential hard fault on an embedded system should be checked IMO, even if it is a 'user error'.
> * We do need a non-regression test.
I don't know where to start on this.  It seems there is no risk of this fix causing regression but...

2022-02-23 08:51 UTC, gilles-peskine-arm commented
Please ensure all commit messages have a signoff line (`git rebase --signoff …`). Otherwise we aren't allowed to use your code.

Regarding `write`: passing `buf=NULL` and `len=0` is valid for both functions and should be unit-tested.

Regarding testing: what's needed is a non-regression test, i.e. a test that would fail if the bug was re-introduced. This can be done by adding `TEST_ASSERT( mbedtls_ssl_read( ssl, NULL, 0 ) == 0 );` to a place in a test suite where a call to `mbedtls_ssl_read` is valid.

2022-11-21 10:30 UTC, daverodgman commented on ChangeLog.d/mbedtls_ssl_read_undefined_behavior.txt
> +   * Fixed undefined behavior in mbedtls_ssl_read if len argument is 0
```suggestion
   * Fixed undefined behavior in mbedtls_ssl_read if len argument is 0.
```

2023-02-24 15:17 UTC, daverodgman commented
@gilles-peskine-arm given that the only missing sign-off is for a suggestion that you made, please add a sign-off on that commit.

2023-02-24 16:01 UTC, daverodgman commented
Superseded by #7171

2023-02-24 16:01 UTC, closed without merging