Accessors to own CID within mbedtls_ssl_context
Mbed-TLS/mbedtls pull request #5638
Opened 2022-03-16 16:38 UTC by paul-elliott-arm

## Description
Add accessors to own CID within mbedtls_ssl_context, as per request in #5184

Add sanity tests for all of the own CID set / get/config functions.

## Status
**READY**

## Requires Backporting
NO  

## Migrations
 NO

## Todos
- [ ] Tests
- [ ] Changelog updated

## Steps to test or reproduce
test_suite_ssl should run clean

2022-03-24 12:51 UTC, mprse requested changes
Looks good.
Only few style issues and one typo.

2022-03-24 12:51 UTC, mprse commented on library/ssl_tls.c
> +    {
Style: braces can be removed.

2022-03-24 12:51 UTC, mprse commented on library/ssl_tls.c
> +    {
Style: braces can be removed.

2022-03-24 12:51 UTC, mprse commented on library/ssl_tls.c
> +        {
Style: braces can be removed.

2022-03-24 12:51 UTC, mprse commented on library/ssl_tls.c
> +     * zero as this is is indistinguishable from not requesting to
typo: `is is` -> `is`

2022-03-25 06:39 UTC, mprse approved these changes
LGTM

2022-03-25 08:26 UTC, mpg commented
@paul-elliott-arm Unfortunately this has conflicts now that #5622 has been merged (add-add, easy to resolve). Could you rebase to resolve them?

2022-03-28 08:09 UTC, mpg commented
Check-files now complaining about missing newline at end of `tests/suites/test_suite_ssl.data` - probably a side-effect of resolving a conflict in that area. (The only other CI issue is an instance of #5583.)

2022-03-28 08:35 UTC, mpg reviewed
Partial review, interrupted because I'm no longer sure I understand what it is that we're trying to do here.

2022-03-28 08:35 UTC, mpg commented on ChangeLog.d/add_own_cid_accessors
> +   * Add the function mbedtls_ssl_get_own_cid() to access our own certificate
s/certificate/connection/

2022-03-28 08:35 UTC, mpg commented on include/mbedtls/ssl.h
> + * \param own_cid     The address of the buffer in which to store our own
Style: "The" should be aligned with the rest (same for the next param).

2022-03-28 08:35 UTC, mpg commented on include/mbedtls/ssl.h
> + * \brief              Get information about our request for usage of the CID
Ok, now I'm confused about what we're trying to do exactly. Should this function return what we requested, or what we negociated? I'll ask in #5184.

2022-03-31 07:42 UTC, mpg commented on include/mbedtls/ssl.h
> + * \brief              Get information about our request for usage of the CID
Ok, seems returning what we requested is indeed what the original reporter asked for. (Which IMO makes this more an optimisation request than a regression fix, but well, we started it, so let's finish it.)

2022-03-31 07:47 UTC, mpg requested changes
Completed my review, no further feedback beyond what I pointed our last time. I like the test, and I see you also fixed some pre-existing test gaps with `mbedtls_set_cid()` while at it, thanks for that!

2022-03-31 07:47 UTC, mpg commented on tests/suites/test_suite_ssl.data
> +cid_sanity:
Missing EOL character here.

2022-04-01 08:21 UTC, paul-elliott-arm commented
CI Failures are unfortunately the OpenCI results, which has not yet been re-configured. Internal CI passed Ok.

2022-04-01 08:48 UTC, mpg approved these changes
LGTM!

2022-04-01 09:30 UTC, mprse approved these changes

2022-04-01 09:36 UTC, merged