Backport 2.28: Support alternative MBEDTLS_PSA_CRYPTO_CONFIG_FILE
Mbed-TLS/mbedtls pull request #5740
Opened 2022-04-14 11:59 UTC by gilles-peskine-arm

Complete backport of https://github.com/Mbed-TLS/mbedtls/pull/5654 with the new PSA config file macros as well as the documentation and test improvements.

We don't normally backport new features, but this one has no impact on users who don't use it (e.g. no impact on code size) and minimal risk of bugs (unlikely to cause a bug if you don't use it). In maintenance terms, it's an additional thing, but we want to use it to simplify testing in a way that applies to both 3.x and 2.28, so it's easier on balance to have the feature in 2.28.

2022-04-14 12:32 UTC, RcColes reviewed
Is this missing the PSA config macros? (the main PR refers to them being backported)

2022-04-14 13:00 UTC, gilles-peskine-arm commented
My bad, I started to do a backport without the new macros, but then I realized we'd miss those new macros when we work on the accelerator tests, so I decided to make a straight backport. But I pushed the wrong branch when I made the PR. Fixed.

2022-04-14 13:55 UTC, RcColes submitted a review, later dismissed
Looks good, no real changes in the branch rebase. Changes still make sense in context and interact sensibly with all.sh and config.py.

2022-04-20 09:34 UTC, RcColes approved these changes

2022-04-26 15:54 UTC, AndrzejKurek requested changes

2022-04-26 15:54 UTC, AndrzejKurek commented on include/mbedtls/config.h
> + * in mbedtls_config.h.
```suggestion
 * in config.h.
```

2022-04-26 15:54 UTC, AndrzejKurek commented on include/mbedtls/config.h
> + * `"mbedtls/mbedtls_config.h"`.
```suggestion
 * `"mbedtls/config.h"`.
```

2022-04-26 15:54 UTC, AndrzejKurek commented on include/mbedtls/config.h
> +//#define MBEDTLS_CONFIG_FILE "mbedtls/mbedtls_config.h"
```suggestion
//#define MBEDTLS_CONFIG_FILE "mbedtls/config.h"
```

2022-04-26 15:54 UTC, AndrzejKurek commented on include/mbedtls/config.h
> + * `"mbedtls/mbedtls_config.h"` or #MBEDTLS_CONFIG_FILE.
```suggestion
 * `"mbedtls/config.h"` or #MBEDTLS_CONFIG_FILE.
```

2022-04-28 08:10 UTC, RcColes approved these changes

2022-04-28 10:11 UTC, AndrzejKurek approved these changes

2022-04-28 12:25 UTC, AndrzejKurek approved these changes

2022-04-28 16:17 UTC, merged