TLS 1.3: Add Finished Message and wrapup
Mbed-TLS/mbedtls pull request #5749
Opened 2022-04-16 09:18 UTC by yuhaoth

fixes #5497, #5498

2022-05-16 12:19 UTC, ronald-cron-arm requested changes

2022-05-16 12:19 UTC, ronald-cron-arm commented on library/ssl_tls13_server.c
> + * State Handler: MBEDTLS_SSL_SERVER_FINISHED
```suggestion
 * Handler for MBEDTLS_SSL_SERVER_FINISHED
```

2022-05-16 12:19 UTC, ronald-cron-arm commented on library/ssl_tls13_server.c
> + * State Handler: MBEDTLS_SSL_CLIENT_FINISHED
```suggestion
 * Handler for MBEDTLS_SSL_CLIENT_FINISHED
```

2022-05-16 12:19 UTC, ronald-cron-arm commented on library/ssl_tls13_server.c
> + * State Handler: MBEDTLS_SSL_FLUSH_BUFFERS
```suggestion
 * Handler for MBEDTLS_SSL_FLUSH_BUFFERS
```

2022-05-16 12:19 UTC, ronald-cron-arm commented on library/ssl_tls13_server.c
> +
```suggestion
```

2022-05-16 12:19 UTC, ronald-cron-arm commented on library/ssl_tls13_server.c
> +                  ( "Switch to handshake traffic keys for outbound traffic" ) );
```suggestion
                  ( "Switch to handshake traffic keys for inbound traffic" ) );
```

2022-05-16 12:19 UTC, ronald-cron-arm commented on library/ssl_tls13_server.c
> +    MBEDTLS_SSL_DEBUG_MSG( 1, ( "Switch to application keys for all traffic" ) );
In client and server, we switch in the handshake wrap-up state to the application keys thus this code should probably be moved to ` mbedtls_ssl_tls13_handshake_wrapup`.

2022-05-16 12:19 UTC, ronald-cron-arm commented on library/ssl_tls13_keys.h
> +    mbedtls_ssl_context* ssl );
```suggestion
    mbedtls_ssl_context *ssl );
```

2022-05-17 14:57 UTC, paul-elliott-arm reviewed
Just to comment that I have reviewed up to this point, and have nothing more to add than Ronald did , also to point out that #5748 is now merged, so this could do with rebase.

2022-05-18 09:06 UTC, yuhaoth commented
> Just to comment that I have reviewed up to this point, and have nothing more to add than Ronald did , also to point out that #5748 is now merged, so this could do with rebase.

Done. Rebased.

2022-05-18 13:56 UTC, ronald-cron-arm requested changes

2022-05-18 13:56 UTC, ronald-cron-arm commented on library/ssl_tls13_generic.c
> +
```suggestion
```

2022-05-18 13:56 UTC, ronald-cron-arm commented on library/ssl_tls13_generic.c
> +        mbedtls_ssl_key_set traffic_keys;
Not addressed it seems.

2022-05-18 13:56 UTC, ronald-cron-arm commented on library/ssl_tls13_keys.c
> +    mbedtls_platform_zeroize( &ssl->handshake->tls13_master_secrets,
Not addressed it seems.

2022-05-20 01:53 UTC, yuhaoth commented
Open CI pass and internal CI still running

2022-05-20 06:36 UTC, ronald-cron-arm approved these changes
Thanks for the changes. LGTM.

2022-05-20 17:11 UTC, paul-elliott-arm approved these changes
LGTM

2022-05-21 15:02 UTC, paul-elliott-arm commented
Not happy to merge this without explanation for the CI fail. Its not a usual failure, and it does genuinely look like an issue.

2022-05-23 06:23 UTC, yuhaoth commented
> Not happy to merge this without explanation for the CI fail. Its not a usual failure, and it does genuinely look like an issue.

OpenCI report same error again. I will try fix it .

2022-05-23 08:19 UTC, yuhaoth commented
Update to fix CI fail. 
I can reproduce it in my local test. And it pass now. 
And I am not sure why internal CI report PASS for `test_no_x509_info`

2022-05-23 08:27 UTC, paul-elliott-arm approved these changes
LGTM (CI Pending)

2022-05-23 13:07 UTC, yuhaoth commented
The openssl 1.1.1a exit with different exit code . 
In my local test , it return 0 and in OpenCI it return 1. 

with last commit, I expect internal CI will fail

2022-05-23 13:44 UTC, ronald-cron-arm commented on tests/ssl-opt.sh
> +            1 \
This is correct, client authentication cannot succeed as the support is not added yet (added in #5777).

2022-05-24 01:41 UTC, yuhaoth commented
I skip the test. And It should be re-enabled in client auth task

2022-05-24 08:08 UTC, ronald-cron-arm approved these changes
I looked at the Internal CI not failing the "TLS 1.3: Server side check - openssl with client authentication" ssl-opt.sh test. The Openssl client does receive (in one chunk) the fatal alert message sent by the Mbed TLS server (unexpected message) but returns with zero anyway. When it is failing on the Open CI (as expected) the only difference I see is that the Openssl client receives the fatal alert message in two pieces instead of one piece and returns in error in that case. Thus all together I think the issue we encountered on the CI is rather an issue of error detection in ssl-opt.sh (the server side is not taken into account to determine the result of the test) and/or interaction between the Openssl client and ssl-opt.sh. Thus in my opinion nothing to prevent this PR to be merged with the aforementioned test being disabled. As @yuhaoth mentioned it will be re-enabled in #5777. @paul-elliott-arm what do you think about this ?

2022-05-25 11:01 UTC, paul-elliott-arm approved these changes
LGTM

2022-05-25 11:02 UTC, merged