Add missing local variable initialization
Mbed-TLS/mbedtls pull request #5766
Opened 2022-04-22 00:32 UTC by leorosen

These issues were flagged by Coverity static code analyzer for
instances that a local variable may be used prior to being initialized.

Signed-off-by: Leonid Rozenboim <leonid.rozenboim@oracle.com>

2022-04-22 17:19 UTC, gilles-peskine-arm requested changes
Please rewrite the commit message whether the changes are necessary, or just good hygiene (robustness in case the code changes, reducing noise from otherwise-useful static analyzers). As far as I can tell, all the changes here fall into the second category. If there was an actual bug, it should have a changelog entry, a non-regression test if feasible (we run tests with MSan and Valgrind), and a backport.

2022-04-27 21:52 UTC, leorosen commented
Feel free to take over this PR and rewrite the commit message to your liking. I can no longer spend any time on upstreaming these changes.

2022-05-13 18:28 UTC, gilles-peskine-arm approved these changes
LGTM

Since this is only for robustness, and mostly in code that's already starting to diverge between 2.28 and development, I don't think we should backport.

2022-05-16 10:06 UTC, minosgalanakis approved these changes
LGTM

2022-05-16 13:47 UTC, merged