Deprecate mbedtls_cipher_setup_psa()
Mbed-TLS/mbedtls pull request #5813
Opened 2022-05-06 09:51 UTC by mprse

## Description
Deprecate mbedtls_cipher_setup_psa()

Resolves: https://github.com/Mbed-TLS/mbedtls/issues/5261

## Status
**READY**

2022-05-10 10:55 UTC, mpg commented
The CI is unhappy. I guess you need to add a few `#if !defined(MBEDTLS_DEPRECATED_REMOVED)` / `depends_on:!MBEDTLS_DEPRECATED_REMOVED` in tests.

2022-05-10 11:01 UTC, mprse commented
Yes I saw that I need to go back to this one, but I started working on something else and I would like to finish at least some part of the new task first.

2022-05-10 11:05 UTC, mpg commented
Sure, no worries! I was just checking for new things I should be reviewing, and then writing down the status. Nothing urgent here.

2022-05-12 11:54 UTC, mprse commented
Fixed dependencies in tests. Let's see if CI is happy now.

2022-05-13 08:05 UTC, mpg commented
CI not quite happy yet, but only one component failing, so this can be tested locally: `tests/scripts/all.sh test_full_no_deprecated_deprecated_warning`.

2022-05-13 13:16 UTC, gilles-peskine-arm commented
> In this case we have mbedtls_cipher_setup_psa() available, so I assume that test should be executed, but because MBEDTLS_DEPRECATED_WARNING got deprecation warnings forced to errors.

Gate that part of the tests with `#if !defined(MBEDTLS_TEST_DEPRECATED)`. See [comment in `component_test_full_deprecated_warning`](https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-2.28.0/tests/scripts/all.sh#L1481).

2022-05-19 07:22 UTC, mpg commented
> Gate that part of the tests with `#if !defined(MBEDTLS_TEST_DEPRECATED)`.

Looking at the code I think it should be the opposite: calls to deprecated functions in tests should be guarded by `#if defined(MBEDTLS_TEST_DEPRECATED)` (no `!`). Or am I missing something?

2022-05-19 07:42 UTC, mpg requested changes
A few more dependency clean-ups and we'll be there.

2022-05-19 07:42 UTC, mpg commented on tests/suites/test_suite_cipher.aes.data
> +depends_on:MBEDTLS_USE_PSA_CRYPTO:!MBEDTLS_DEPRECATED_REMOVED:MBEDTLS_AES_C:MBEDTLS_CIPHER_MODE_CBC
I think the extra dependency should be `MBEDTLS_TEST_DEPRECATED` (see comment in the test function).

2022-05-19 07:42 UTC, mpg commented on tests/suites/test_suite_cipher.function
> +#if defined(MBEDTLS_USE_PSA_CRYPTO) || defined(MBEDTLS_DEPRECATED_REMOVED)
Shouldn't we have the same guard here as for the call to `psa_crypt_init()`, that is `USE_PSA_CRYPTO && !DEPRECATED_REMOVED && TEST_DEPRECATED`? (Or just `USE_PSA_CRYPTO && TEST_DEPRECATED`?)

2022-05-19 07:42 UTC, mpg commented on tests/suites/test_suite_cipher.function
> +    !defined(MBEDTLS_TEST_DEPRECATED)
I think `DEPRECATED_REMOVED` is redundant with `TEST_DEPRECATED`, so the guard should be `#if !defined(MBEDTLS_USE_PSA_CRYPO) || !defined(MBEDTLS_TEST_DEPRECATED)`. That is, in plain English the condition for being able to use `cipher_setup_psa()` is "use-PSA is enabled, and we're allowed to test deprecated functions".

2022-05-19 07:42 UTC, mpg commented on tests/suites/test_suite_cipher.function
> +#if !defined(MBEDTLS_USE_PSA_CRYPTO) || defined(MBEDTLS_DEPRECATED_REMOVED) || \
Same as above.

2022-05-19 11:08 UTC, mpg requested changes
Looks almost good to me, just missed two data files I think.

2022-05-19 11:08 UTC, mpg commented on tests/suites/test_suite_cipher.ccm.data
> +depends_on:MBEDTLS_USE_PSA_CRYPTO:!MBEDTLS_DEPRECATED_REMOVED:MBEDTLS_AES_C:MBEDTLS_CCM_C
This should be changed to `MBEDTLS_TEST_DEPRECATED`, and in `gcm.data` as well.

2022-05-20 09:11 UTC, mpg approved these changes
LGTM - and the CI agrees :)

2022-05-30 07:49 UTC, superna9999 approved these changes

2022-05-31 06:50 UTC, mprse commented
PR-Merge is pending, but looks green I think we can merge this one.

2022-05-31 08:56 UTC, merged