[2.28] Rewrite x25519 example program
Mbed-TLS/mbedtls pull request #5848
Opened 2022-05-18 14:17 UTC by tom-daubney-arm

Backport of #5725

2022-05-30 11:00 UTC, paul-elliott-arm commented on programs/pkey/ecdh_curve25519.c
> +    ret = mbedtls_ecdh_calc_secret( &ctx_srv, &olen, secret_srv,
```suggestion
    ret = mbedtls_ecdh_calc_secret( &ctx_srv, &srv_olen, secret_srv,
```

2022-05-30 11:01 UTC, paul-elliott-arm commented on programs/pkey/ecdh_curve25519.c
> +    ret = memcmp( secret_srv, secret_cli, sizeof( secret_srv_olen ) );
```suggestion
    ret = memcmp( secret_srv, secret_cli, srv_olen );
```

2022-05-30 11:01 UTC, paul-elliott-arm commented on programs/pkey/ecdh_curve25519.c
> +    if( ret != 0 || ( secret_cli_olen != secret_srv_olen ) )
```suggestion
    if( ret != 0 || ( cli_olen != srv_olen ) )
```

2022-05-30 11:02 UTC, paul-elliott-arm requested changes
This still needs the Changelog entry. We build the Changelog for all LTS branches.

2022-05-31 09:26 UTC, gilles-peskine-arm approved these changes
I checked manually that `programs/pkey/ecdh_curve25519` now works whether Everest is enabled or not.

2022-05-31 09:26 UTC, merged