Reduce RAM - move some variables to .rodata
Mbed-TLS/mbedtls pull request #5894
Opened 2022-06-07 07:22 UTC by Xeenych

Add const to move variables to .rodata section

Signed-off-by: Xeenych <xeenych@gmail.com>

Fix #5891

2022-06-08 09:41 UTC, ronald-cron-arm requested changes
You miss the sign-off-by line in the commit message.

2022-06-08 09:54 UTC, Xeenych commented
> You miss the sign-off-by line in the commit message.

How do I edit the commit message?

2022-06-08 10:01 UTC, ronald-cron-arm commented
> > You miss the sign-off-by line in the commit message.
> 
> How do I edit the commit message?

Edit it locally : "git commit --amend".
Then force push the branch to your Mbed TLS fork, something like: "git push <remote fork name> --force-with-lease patch-1"

2022-06-08 10:01 UTC, gilles-peskine-arm commented
For a single commit:
```
git commit --no-edit --amend --signoff
```

For all commits since the last merge:
```
git rebase -i --signoff
```
and keep all the commits on “pick”.

2022-06-08 11:34 UTC, Xeenych commented
I've made this PR with github web interface. I cannot use git command line

2022-08-09 10:04 UTC, daverodgman commented
I think since the author has added a sign-off to the top of this PR description and seems happy, I'll add a sign-off so we can proceed.

2022-08-09 10:16 UTC, daverodgman submitted a review, later dismissed

2022-09-07 17:04 UTC, davidhorstmann-arm commented
I have rebased on top of development - of the 3 arrays, 2 were deprecated and have since been removed, so only 1 remains.

2022-09-09 09:58 UTC, davidhorstmann-arm commented
DCO is failing due to having a signature that doesn't match the PR author.

2023-02-01 22:05 UTC, tom-cosgrove-arm commented
So this changes

```
   text	   data	    bss	    dec	    hex	filename
  37565	    789	      0	  38354	   95d2	library/ssl_tls-aarch64-development.o
  37573	    777	      0	  38350	   95ce	library/ssl_tls-aarch64-5894.o
```

Since both text and data will be in flash, this seems like a (very minor) win - but suggests other patterns to look for.

2023-02-28 22:42 UTC, gstrauss commented
@Xeenych can you add a Signed-off-by: line to the commit so that it passes the DCO commit check?

2023-05-05 13:53 UTC, tom-cosgrove-arm approved these changes

2023-05-05 13:54 UTC, merged