Tls13 fixes doc
Mbed-TLS/mbedtls pull request #5908
Opened 2022-06-10 13:25 UTC by ronald-cron-arm

## Description
A few fixes in TLS 1.3 code that has not been released yet. Then a documentation of the high level organization of the TLS 1.3 handshake implementation followed by a few commits re-organizing the code in line with the documentation. 

## Status
CI check

## Requires Backporting
No, TLS 1.3 only

2022-06-13 14:09 UTC, minosgalanakis reviewed
Looks good code wise, but there are some minor spelling issues to documentation.

2022-06-14 16:40 UTC, ronald-cron-arm commented on library/ssl_tls13_client.c
> +                                     const unsigned char *buf, size_t len )
This is to align the arguments vertically with the one in the previous line.

2022-06-14 16:45 UTC, ronald-cron-arm commented on docs/architecture/tls13-support.md
> +between the calls to the handlers and as a consequence handlers do not have to
Are you sure of this ? Looking at it on the web it seems that "as a consequence" is correct.

2022-06-17 08:37 UTC, yuhaoth requested changes
Add an optional suggestion.

2022-06-17 08:37 UTC, yuhaoth commented on docs/architecture/tls13-support.md
> +functions `mbedtls_ssl_tls13_handshake_client/server_step` are the top level
```suggestion
functions `mbedtls_ssl_tls13_handshake_{client,server_step}` are the top level
```
I think it is better than `/`

2022-06-17 08:37 UTC, yuhaoth commented on docs/architecture/tls13-support.md
> +prefixed with `(mbedtls_)ssl_tls13_process/write`. To ease the maintenance and
```suggestion
prefixed with `(mbedtls_)ssl_tls13_{process,write}`. To ease the maintenance and
```
ditto

2022-06-24 11:48 UTC, ronald-cron-arm commented
@minosgalanakis @yuhaoth I believe I have addressed your comments. Please have another look.

2022-06-27 01:22 UTC, yuhaoth submitted a review, later dismissed
LGTM

2022-06-27 08:53 UTC, minosgalanakis approved these changes
LGTM

2022-06-28 07:24 UTC, ronald-cron-arm commented
@minosgalanakis @yuhaoth I had to rebase due to a conflict in ssl_tls13_server.c following the merge of #5973. Please have another look.

2022-06-28 07:38 UTC, yuhaoth approved these changes

2022-06-28 08:53 UTC, minosgalanakis approved these changes

2022-06-28 10:16 UTC, merged