cmake: IAR support option( MBEDTLS_FATAL_WARNINGS)
Mbed-TLS/mbedtls pull request #5950
Opened 2022-06-17 10:11 UTC by savent404

Notes:
* Pull requests cannot be accepted until the PR follows the [contributing guidelines](../CONTRIBUTING.md). In particular, each commit must have at least one `Signed-off-by:` line from the committer to certify that the contribution is made under the terms of the [Developer Certificate of Origin](../dco.txt).
* This is just a template, so feel free to use/remove the unnecessary things
## Description
A few sentences describing the overall goals of the pull request's commits.

Signed-off-by: savent gate savent_gate@outlook.com

## Status
**HOLD**

## Todos
- [x] Tests
- [ ] Documentation
- [ ] Changelog updated
- [ ] Backported

## Steps to test or reproduce
Outline the steps to test or reproduce the PR here.

2022-06-20 02:13 UTC, savent404 commented
needs reviewers.
Can anyone review this?

@tuvshinzayaArm  @gilles-peskine-arm

2022-07-22 13:46 UTC, paul-elliott-arm requested changes
Hi @savent404 - this looks good to me - it brings IAR in line with the other compilers. Unfortunately I think this could do with a changelog (see https://github.com/Mbed-TLS/mbedtls/blob/development/ChangeLog.d/00README.md) as this is a fix that is visible to the end user.

Something like
```
Bugfix
   * Stop warnings as errors being used by default when compiling with IAR without defining MBEDTLS_FATAL_WARNINGS
```
(But obviously this will need to be formatted properly)

2022-08-09 09:51 UTC, daverodgman approved these changes

2022-08-09 09:52 UTC, merged

2022-08-09 09:56 UTC, daverodgman commented
It occurred to me after merging that a backport is needed: see #6187