Add ALPN extension to the server side
Mbed-TLS/mbedtls pull request #5951
Opened 2022-06-17 10:22 UTC by xkqian

This will add alpn extension support the server side.
Also make the exist alpn cases available for both tls1.2 and tls1.3

2022-06-22 12:53 UTC, yuhaoth requested changes
Some improvement and GnuTLS test is missing

2022-06-22 12:53 UTC, yuhaoth commented on library/ssl_misc.h
> +                                size_t *olen );
```suggestion
                                size_t *out_len );
```

2022-06-22 12:53 UTC, yuhaoth commented on library/ssl_tls.c
> +     */
```suggestion
    /*
     * RFC7301, section 3.1
     *   opaque ProtocolName<1..2^8-1>;
     *
     *   struct {
     *       ProtocolName protocol_name_list<2..2^16-1>
     *   } ProtocolNameList;
     */
```

2022-06-22 12:53 UTC, yuhaoth commented on library/ssl_tls.c
> +    /* Min length is 2 ( list_len ) + 1 ( name_len ) + 1 ( name ) */
```suggestion
    /* 
     * protocal_name_list_len    2 bytes
     * protocal_name_len          1 bytes
     * protocal_name                 >=1 byte
     */
```

2022-06-22 12:53 UTC, yuhaoth commented on library/ssl_tls.c
> +    size_t list_len;
```suggestion
    size_t protocol_name_list_len;
```

2022-06-22 12:53 UTC, yuhaoth commented on library/ssl_tls.c
> +    size_t cur_alpn_len;
```suggestion
    const unsigned char *protocol_name;
    size_t protocol_name_len;
```

2022-06-22 12:53 UTC, yuhaoth commented on library/ssl_tls.c
> +                                size_t *olen )
```suggestion
                                size_t *out_len )
```

2022-06-22 12:53 UTC, yuhaoth commented on tests/ssl-opt.sh
> +            -s "server state: MBEDTLS_SSL_HANDSHAKE_WRAPUP" \
```suggestion
```

2022-06-23 08:25 UTC, yuhaoth submitted a review, later dismissed
LGTM.

2022-06-23 12:18 UTC, ronald-cron-arm requested changes
This looks quite good to me, just some minor suggestion for improvement.

2022-06-23 12:18 UTC, ronald-cron-arm commented on library/ssl_tls13_server.c
> +    p  += output_len;
```suggestion
    p += output_len;
```

2022-06-24 02:12 UTC, xkqian commented on library/ssl_tls.c
> +    MBEDTLS_PUT_UINT16_BE( *out_len - 6, p, 4 );
MBEDTLS_PUT_UINT16_BE( protocol_name_len + 1, p, 4 );

2022-06-24 07:48 UTC, ronald-cron-arm requested changes
Final very minor things. Otherwise, this looks good to me.

2022-06-24 07:48 UTC, ronald-cron-arm commented on library/ssl_tls.c
> +     * protocal_name_list_len    2 bytes
```suggestion
     * protocol_name_list_len    2 bytes
```

2022-06-24 07:48 UTC, ronald-cron-arm commented on library/ssl_tls.c
> +     * protocal_name_len         1 bytes
```suggestion
     * protocol_name_len         1 bytes
```

2022-06-24 07:48 UTC, ronald-cron-arm commented on library/ssl_tls.c
> +     * protocal_name             >=1 byte
```suggestion
     * protocol_name             >=1 byte
```

2022-06-24 07:48 UTC, ronald-cron-arm commented on library/ssl_tls.c
> +    p[6] = MBEDTLS_BYTE_0( protocol_name_len );
```suggestion
    /* Note: the length of the chosen protocol has been checked to be less
     * than 255 bytes in `mbedtls_ssl_conf_alpn_protocols`.
     */
    p[6] = MBEDTLS_BYTE_0( protocol_name_len );
```

2022-06-24 12:08 UTC, ronald-cron-arm approved these changes
LGTM, @yuhaoth please have a look to the last version.

2022-06-27 01:48 UTC, yuhaoth approved these changes
LGTM

2022-06-27 06:33 UTC, merged