Update documenation of PSA_ALG_RSA_PSS
Mbed-TLS/mbedtls pull request #5953
Opened 2022-06-17 11:28 UTC by tuvshinzayaArm

## Description

Currently documenation of PSA_ALG_RSA_PSS doesn't reflect the change in code.

## Status
**IN DEVELOPMENT**

## Requires Backporting

Yes 

Which branch?

2.28

## Migrations

NO

## Additional comments

Note regarding issue #5856, positive test case already exist. No need to add new positive test case

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog updated
- [ ] Backported

## Steps to test or reproduce

See documentation for PSA_ALG_RSA_PSS in include/psa/crypto_values.h file.

2022-06-20 18:00 UTC, gilles-peskine-arm requested changes
This documentation change is correct, but it does not fulfill https://github.com/Mbed-TLS/mbedtls/issues/5856, which asks for a new test case.

2022-06-22 12:51 UTC, tuvshinzayaArm commented
> This documentation change is correct, but it does not fulfill #5856, which asks for a new test case.

Positive test case already exist.

PSA verify hash: RSA-1024 PSS SHA-512, slen=62

This test hits desired branch.
```
    else
        return( room );
```

2022-06-22 20:19 UTC, gilles-peskine-arm approved these changes
My bad, you're right, the requested test case was already present.

2022-06-29 16:05 UTC, daverodgman approved these changes

2022-07-14 09:40 UTC, merged