Fix issue#5077
Mbed-TLS/mbedtls pull request #5985
Opened 2022-06-28 06:31 UTC by zhangsenWang

## Description
Fix issue#5077, Re-enable tests disable dued to old OpenSSL bug
## Status
**READY**

## Steps to test or reproduce
with openssl 1.1.1a or higher version
`export OPENSSL_NEXT=/path/to/openssl`
`./tests/ssl-opt.sh -f "DTLS fragmenting: 3d, openssl"`
`./tests/ssl-opt.sh -f "DTLS proxy: 3d, openssl"`

2022-06-28 07:36 UTC, xkqian commented
Seems DCO failed. You should pay attention to your commit message and add the signoff into it.

2022-06-28 08:43 UTC, zhangsenWang commented
> Seems DCO failed. You should pay attention to your commit message and add the signoff into it.

I have already added the signoff into it.

2022-06-28 13:32 UTC, minosgalanakis commented
Thank you for your contribution.

Would it be possible to reword the commit message so it describes what the patch does? Issue #5077 can be tracked through here.

Also does that mean that before merging this comit we need to update the CI images with the fixed version of OpenSSL?

2022-06-28 18:12 UTC, gilles-peskine-arm commented
@minosgalanakis We already have a recent enough version of openssl on the CI images. (A CI pass confirms that.) The tests are from before we had this recent version and we hadn't gotten around to re-enabling them.

2022-06-28 18:16 UTC, gilles-peskine-arm requested changes
Patch: approved.

Changelog message: please write a meaningful changelog message. See `git log` for examples. The issue number is not meaningful in itself. The issue should always be linked in the pull request description, but it isn't vital to have it in the commit message since it can be traced back from the commit through the pull request. “Re-enable tests disabled because of an old OpenSSL bug” would be an adequate commit message (and pull request title).

This needs a backport to the `mbedtls-2.28` long-time support branch. Note that in 2.28, there are 7 test cases with `skip_next_test`.

2022-06-29 02:17 UTC, zhangsenWang commented
> 

Thanks for your advice. I have changed the commit message. And I will do the backport with mbedtls-2.28 in another PR soon.

2022-06-29 06:20 UTC, xkqian commented
We can see the comments below: 
"## Besides, openssl should use dtls1_2 or dtls, otherwise it will cause "SSL alert number 70" error"

Seems If we use the dtls1, the test will fail because of the version mismatch.  I check the code in server and find that we disable the dtls 1.0 support, is that the intention? @gilles-peskine-arm

2022-06-29 09:14 UTC, gilles-peskine-arm commented
Mbed TLS 2.28 supports DTLS 1.0 and 1.2. Mbed TLS 3.x only supports 1.2.

OpenSSL 1.0.2g (`$OPENSSL`) only supports DTLS 1.0. OpenSSL 1.1.1a (`$OPENSSL_NEXT`) supports 1.0 and 1.2.

It should be ok to change these tests to `-dtls1_2` in 2.28, like you did in development.

2022-06-29 09:15 UTC, gilles-peskine-arm submitted a review, later dismissed
Thanks for improving the commit message. Looks good to me now.

There's a CI failure now though. Please check what's going on.

2022-06-30 02:24 UTC, xkqian requested changes

2022-06-30 02:24 UTC, xkqian commented on tests/ssl-opt.sh
> +
```suggestion

```

2022-06-30 03:35 UTC, xkqian approved these changes
LGTM

2022-06-30 14:16 UTC, gilles-peskine-arm approved these changes
LGTM

2022-06-30 15:40 UTC, gilles-peskine-arm requested changes
There's an inconsistency here. I think I know what's going on but this warrants further investigation. We need to make sure we understand what's going on.

2022-07-12 02:12 UTC, zhangsenWang commented on tests/ssl-opt.sh
> +requires_openssl_next
Thanks for you suggestion, you are right. I have performed more tests with OpenSSL below 1.1.1a. The bug did only occur with OpenSSL server. I have deleted the version requirement for OpenSSL client. Please review again, thank you.

2022-07-12 02:32 UTC, xkqian commented
Travis CI failed: 
`DTLS fragmenting: 3d, openssl client, DTLS 1.2 ......................... RETRY(client-timeout) RETRY(client-timeout) FAIL
  ! bad client exit code (expected 0, got 143)
  ! outputs saved to o-XXX-625.log`

2022-07-12 08:02 UTC, zhangsenWang commented
> Travis CI failed: `DTLS fragmenting: 3d, openssl client, DTLS 1.2 ......................... RETRY(client-timeout) RETRY(client-timeout) FAIL ! bad client exit code (expected 0, got 143) ! outputs saved to o-XXX-625.log`

2022-07-13 07:24 UTC, xkqian commented
Seems when `seed=1`, the pseudo random number will be the special one, which will cause the the test case time out failure(for examble drop 1:N packet, but the data size is multiplication of N). 
Suggest adding the option "seed" with different value from 1, such as `seed=2`
How about your opinion? @gilles-peskine-arm @zhangsenWang

2022-07-27 09:16 UTC, zhangsenWang commented
With certain seed, the DTLS test with OpenSSL client will time out. I find that this is because of an OpenSSL bug that the client will get stuck in case of duplicated  `Encrypted handshake message`,  I report it in https://github.com/openssl/openssl/issues/18887. As for the test cases using OpenSSL server, they passed according to the log in Jenkins.

2022-07-29 02:03 UTC, xkqian commented
Please skip the failure cases and go on this PR.  I think we can file one new issue with description: "With certain seed, the DTLS test with OpenSSL client will time out".

2022-07-29 07:42 UTC, xkqian commented
Something wrong with CI.  Please remove the tail white space.
![image](https://user-images.githubusercontent.com/53458466/181709853-eb55ce6b-11ee-4a12-8012-9c09e8838bfe.png)

2022-07-29 08:26 UTC, xkqian approved these changes
LGTM

2022-08-05 20:36 UTC, gilles-peskine-arm approved these changes

2022-08-16 08:56 UTC, merged