Pr/add tls13 paser psk kex mode ext
Mbed-TLS/mbedtls pull request #6078
Opened 2022-07-09 04:29 UTC by yuhaoth

## Description
fix #5661

## Status
**READY**

2022-07-13 11:49 UTC, ronald-cron-arm requested changes
This looks almost good to me. I have only minor comments and requests for improvement.

2022-07-13 15:45 UTC, ronald-cron-arm requested changes
Just some wording to improve I think.

2022-07-13 15:45 UTC, ronald-cron-arm commented on tests/ssl-opt.sh
> +    # For ubuntu 22.04, `Terminated` message is outputed from `wait` command.
```suggestion
    # For Ubuntu 22.04, `Terminated` message is outputted by the wait command.
```

2022-07-13 15:45 UTC, ronald-cron-arm commented on tests/ssl-opt.sh
> +    # to eliminate it from stdout, redirect stdout/stderr to CLI_OUT
```suggestion
    # To remove it from stdout, redirect stdout/stderr to CLI_OUT
```

2022-07-15 03:05 UTC, xkqian commented on library/ssl_tls13_server.c
> +    /* Read PSK mode list length (1 Byte) */
```suggestion
    /* Read ke_modes length (1 Byte) */
```

2022-07-18 06:26 UTC, ronald-cron-arm approved these changes
LGTM

2022-07-18 06:26 UTC, ronald-cron-arm commented
@xkqian please have another look to the last version.

2022-07-18 09:34 UTC, merged