Remove encoding width suffix from Arm bignum assembly
Mbed-TLS/mbedtls pull request #6090
Opened 2022-07-15 11:14 UTC by hanno-arm

Within the M-profile of the Arm architecture, some instructions admit both a 16-bit and a 32-bit encoding. For those instructions,
some assemblers support the use of the .n (narrow) and .w (wide) suffixes to force a choice of instruction encoding width.
Forcing the size of encodings may be useful to ensure alignment of code, which can have a significant performance impact on some microarchitectures.

It is for this reason that a previous commit introduced explicit .w suffixes into what was believed to be M-profile only assembly
in library/bn_mul.h.

This change, however, introduced two issues:
- First, the assembly block in question is used also for Armv7-A systems, on which the .n/.w distinction is not meaningful (all instructions are 32-bit).
- Second, compiler support for .n/.w suffixes appears patchy, leading to compilation failures even when building for M-profile
  targets.

This PR removes the .w annotations in order to restore working code, deferring controlled re-introduction for the sake of performance.

It also modifies all.sh to make sure that Arm inline assembly is at least built.

Fixes #6089.

2022-07-15 11:36 UTC, Aethedor commented
The changes to bn_mul.h is what I mentioned in my original report. That works for me, so good to hear that it's indeed the right patch.

2022-07-19 07:47 UTC, mpg reviewed
Thanks for the fix and test! Looks good to me, but shouldn't we also build that arm asm with gcc? We already have components that build with arm-none-eabi-gcc and arm-linux-gnueabihf-gcc (IIRC), they should probably be extended as well?

Also, I think this is a correct fix, and it's good for now, but in the long run I wonder if a better solution could be found. I thought the point of Arm's Unified Assembler Language was precisely what we shouldn't need to use different syntax from M-class (Thumb) and A-class (Arm). And it seems to me that GNU asm supports it with `.syntax unified`. But I'm not familiar enough with the details to know if this would work, so I'm very happy to merge the obvious fix for now and leave that for later - I just wanted to share the idea.

2022-07-19 08:13 UTC, mpg commented
Yes, I have no practical experience with that, so it's entirely possible that it doesn't work in practice. I'm also unlikely to have time to investigate, which is why I'm happy approving the present fix - as soon as the question of whether we should also extend the components that build with GCC for Arm is resolved.

2022-07-19 08:17 UTC, hanno-arm commented
@tom-cosgrove-arm Do you have time to look into build tests using GCC?

2022-07-19 08:29 UTC, tom-cosgrove-arm commented
@hanno-arm Sorry, no, I am somewhat overcommitted at the moment :(

2022-07-20 09:07 UTC, tom-cosgrove-arm commented
Note that with this PR, I am concerned that the `all.sh` updates are just changing existing builds, which means, although we will now be testing stuff we want to, we will no longer be testing stuff we used to. I don't know `all.sh` well enough to know if this is a problem

2022-08-16 13:09 UTC, daverodgman commented
@lhuang04 confirms that this PR addresses the problem for his use-case

2022-08-16 15:56 UTC, daverodgman commented
> Note that with this PR, I am concerned that the `all.sh` updates are just changing existing builds, which means, although we will now be testing stuff we want to, we will no longer be testing stuff we used to. I don't know `all.sh` well enough to know if this is a problem

Given that this test is very quick, I suggest we add an additional couple of lines to retain coverage of -O0 / assembly disabled

2022-08-16 15:57 UTC, daverodgman commented on tests/scripts/all.sh
>  }
```suggestion
  # Additional coverage with assembly disabled and -O0.
    scripts/config.py unset MBEDTLS_HAVE_ASM

    # ARM Compiler 6 - Target ARMv7-M
    armc6_build_test "--target=arm-arm-none-eabi -O0 -march=armv7-m+dsp"

    # ARM Compiler 6 - Target ARMv8.2-A - AArch64
    armc6_build_test "--target=aarch64-arm-none-eabi -O0 -march=armv8.2-a+crypto"
}
```

2022-08-16 15:58 UTC, hanno-arm commented
We do have tests for ASM disabled: https://github.com/Mbed-TLS/mbedtls/blob/development/tests/scripts/all.sh#L2811 for 32-bit and https://github.com/Mbed-TLS/mbedtls/blob/development/tests/scripts/all.sh#L2822 for 64-bit.

2022-08-16 15:58 UTC, daverodgman requested changes
LGTM but suggest we retain some coverage of non-assembly builds for armcc?

2022-08-16 16:50 UTC, gilles-peskine-arm commented
@daverodgman We test with assembly disabled. That's important because there could be a bug in the C code. However, there's no reason to test with multiple compilers. (There are reasons to test with different endiannesses — which we don't do at all at the moment — and with different word sizes, which we do.)

It is useful to test assembly code with different compilers because they might optimize differently and this can reveal bugs at the asm/c interface. For example recently we had code that was missing a clobber declaration and this worked fine with GCC but led Clang to produce non-working code.

2022-08-16 16:57 UTC, gilles-peskine-arm requested changes
LGTM for the assembly change (I agree with worrying about portability first and compiler- and CPU-specific microoptimization second). But please keep the plain v7m build.

2022-08-16 16:57 UTC, gilles-peskine-arm commented on tests/scripts/all.sh
> +    scripts/config.py set MBEDTLS_HAVE_ASM
It's on by default anyway, but I have nothing against explicitly enabling it.

2022-08-16 16:57 UTC, gilles-peskine-arm commented on tests/scripts/all.sh
> +    armc6_build_test "--target=arm-arm-none-eabi -O1 -march=armv7-m+dsp"
Blocker: please keep a build with a plain `arch=armv7-m` as well.

2022-08-16 16:57 UTC, gilles-peskine-arm commented on tests/scripts/all.sh
> +    armc6_build_test "--target=arm-arm-none-eabi -O1 -march=armv7-a"
Minor: I'd prefer to have `--target` and `-march` next to each other since they're strongly related.

2022-08-16 18:14 UTC, daverodgman commented on tests/scripts/all.sh
>  }
Based on Gilles' comment below, I don't think this is needed.

2022-08-17 13:42 UTC, daverodgman commented
(marking single reviewer as it's been double-reviewed up to the last, trivial commit)

2022-08-17 14:06 UTC, tom-cosgrove-arm approved these changes
LGTM

2022-08-17 14:32 UTC, gilles-peskine-arm approved these changes

2022-08-18 07:48 UTC, merged

2022-08-24 06:10 UTC, peter-toft-greve commented
Good stuff! Fixes ARMv7l build fails

2022-11-22 11:25 UTC, nasli commented
Thanks for the fix!!
Is there an ETA for the next release @gilles-peskine-arm ? Thanks!

2022-11-22 11:27 UTC, gilles-peskine-arm commented
@nasli We're planning a release mid-December.

2022-11-22 16:25 UTC, nasli commented
Great! thank you for the update!