TLS 1.3: Key exchange modes: Add psk/psk_ephemeral check
Mbed-TLS/mbedtls pull request #6106
Opened 2022-07-20 09:10 UTC by yuhaoth

# Description

The key exchange mode detection depends on `ssl->conf`, `ssl->handshake->extensions_present` and key exchange modes from client side.

- NewSessionTicket depends on key exchange modes from client side
- ServerHello depends on which kex mode is selected. 

So, a new field `peer_kex_mods` is created for NewSessionTicket message. The key exchange mode used by neogotiation is decided by configuration and recevied data

2022-07-20 13:36 UTC, ronald-cron-arm requested changes

2022-07-20 13:36 UTC, ronald-cron-arm commented on library/ssl_misc.h
> +    int peer_tls13_kex_modes; /*!< key exchange modes from client side */
I prefer the prototype's solution with a `key_exchange` field both on client and server side to store the negotiated key exchange mode (could be `key_exchange_mode` by the way) and `tls13_kex_modes` as a server only field storing the key exchange modes proposed by the client.
I prefer this solution as we negotiate a single mode not a set of modes thus `tls13_kex_modes` for a negotiated single mode is confusing. To go there I think we have:
1.  to change all occurrences of `tls13_kex_modes` in the code by `key_exchange(_mode)` but when storing the key exchange modes proposed by the client on server side.
2. introduce utility functions `mbedtls_ssl_tls13_key_exchange_mode_with_{psk,ephemeral}` like the `mbedtls_ssl_tls13_kex_with_{psk,ephemeral}` functions in the prototype for checks of the negotiated key exchange mode.
3. use the two functions of 2 in place of the `mbedtls_ssl_tls13_.*_enabled` functions to check the negotiated exchange mode in client and server code.

2022-07-20 17:29 UTC, ronald-cron-arm commented on library/ssl_misc.h
> +    int peer_tls13_kex_modes; /*!< key exchange modes from client side */
I've pushed #6112 to address this and hopefully speed-up things. Hopefully #6112 will pass the CI and you can base your work upon it.

2022-07-21 01:57 UTC, yuhaoth commented
It has been resolved in 6112

2022-07-21 02:49 UTC, yuhaoth commented
Add some local tests and mark it as `do not merged`

2022-12-17 10:59 UTC, closed without merging