Added script to test abi_check
Mbed-TLS/mbedtls pull request #6116
Opened 2022-07-21 10:43 UTC by tuvshinzayaArm

## Description
This new script will test abi_check.
Changes to all.sh will be made so that script can be called from there.

## Status
**IN DEVELOPMENT**

## Requires Backporting
 NO  

## Migrations

NO

## Additional comments

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog updated
- [ ] Backported

## Steps to test or reproduce
run script from root of project

2022-09-01 08:28 UTC, gilles-peskine-arm requested changes

2022-09-01 08:28 UTC, gilles-peskine-arm commented on tests/scripts/check_abi_check.py
> +    return "^["+ "".join(["("+line+")" for line in lines]) +"]$"
This doesn't do what you think. `[…]` is a _character_ set, so you're building a regex that matches a single character. Alternation (matching one of multiple patterns) is `…|…`.

2022-09-01 08:28 UTC, gilles-peskine-arm commented on tests/scripts/check_abi_check.py
> +    def test_abi_different(self):
`abi_check` does several things, currently 4: API differences, ABI differences, generated file differences, storage format test differences. We should have a negative test for each of them: e.g. there should at least one test case with (compatible ABI, incompatible ABI, compatible generated files, compatible storage format tests), and one with (compatible API, compatible ABI, compatible generated files, incompatible storage format tests), and one with (compatible API, compatible ABI, incompatible generated files, compatible storage format tests) (I'm not sure if incompatible API, compatible ABI is possible with abi_check's definition of API/ABI compatibility).

The task description for #5409 specifically requests negative testing for API/ABI compatibility, and there's a separate task #5410 for generated test cases. So for #5409 it's enough to focus on API/ABI differences, but the test has to fail if `abi_check.py` only reports incompatibilities in generated tests.

2022-09-01 08:28 UTC, gilles-peskine-arm commented on tests/scripts/check_abi_check.py
> +    run_main()
We need to have a component of `all.sh` that runs this, so that it's run on the CI.

2022-09-01 10:33 UTC, gilles-peskine-arm commented
Ignore the CI statuses for PR-5986, due to an accidental incorrect force-push.

2022-09-01 16:02 UTC, gilles-peskine-arm commented on tests/scripts/check_abi_check.py
> +    def test_abi_different(self):
`_read_storage_tests` records test cases if they either come from an automatically generated file or the function name contains `read`. So for #5410, there should be a test case that removes a `read` test from a non-automatically-generated file, and a test case that removes a non-`read` test from an automatically generated file.

c4b814a9c2c192f8f52908645720ced9cb817447 is an ABI break and not an API break. All enum identifiers still exist afterwards, so source programs will still work, so it's a compatible API. But the values of some enum identifiers change, so some compiled programs won't work anymore, so it's an ABI break.

2023-05-12 13:46 UTC, daverodgman commented
Closing since Zaya is unlikely to progress this further.

2023-05-12 13:46 UTC, closed without merging