TLS 1.3: NewSessionTicket: finalize tls13 session tickets flow.
Mbed-TLS/mbedtls pull request #6167
Opened 2022-08-02 10:22 UTC by yuhaoth

## Description
Previous PRs finished PSK and NewSessionTicket parser/writer. 

This PR is to add session ticket identify and handshake psk setting. Also some tests.

## Status
**IN DEVELOPMENT**

2022-09-05 07:11 UTC, xkqian commented on library/ssl_tls13_server.c
> +    int ret;
```suggestion
    int ret = MBEDTLS_ERR_ERROR_CORRUPTION_DETECTED;
```

2022-09-05 07:14 UTC, xkqian commented on library/ssl_tls13_server.c
> +    {
```suggestion
```

2022-09-05 07:14 UTC, xkqian commented on library/ssl_tls13_server.c
> +    }
```suggestion
```

2022-09-05 07:22 UTC, xkqian commented
https://github.com/Mbed-TLS/mbedtls/pull/6135 has been merged.  "preceding PR" can be removed.

2022-09-06 00:55 UTC, yuhaoth commented on library/ssl_tls13_client.c
> +            ssl->session_negotiate->ticket_age_add;
That is a `uint32_t`. It has been modulated by 2^32.

2022-09-07 02:37 UTC, xkqian commented on library/ssl_tls13_client.c
> +            ssl->session_negotiate->ticket_age_add;
Seems uint32_t only type cast ( now - ssl->session_negotiate->ticket_received ), from the description, should we type cast the summary, I mean:  ( now - ssl->session_negotiate->ticket_received ) +
            ssl->session_negotiate->ticket_age_add

2022-09-12 13:52 UTC, ronald-cron-arm requested changes

2022-09-12 13:52 UTC, ronald-cron-arm commented on library/ssl_tls13_server.c
> +        *selected_ciphersuite = session->ciphersuite;
```suggestion
        *selected_ciphersuite = ciphersuite;
```

2022-09-12 13:52 UTC, ronald-cron-arm commented on library/ssl_tls13_server.c
> +
```suggestion
```

2022-09-12 13:52 UTC, ronald-cron-arm commented on library/ssl_tls13_client.c
> +            (uint32_t)( now - ssl->session_negotiate->ticket_received ) +
```suggestion
           ( (uint32_t)( now - ssl->session_negotiate->ticket_received ) * 1000 ) +
```
`ssl_tickets.c` assumes that `mbedtls_time()` returns a value in seconds (as time() does in Linux and Windows). Let's be consistent with this here and thus multiply the time difference by 1000 as the ticket age is defined to be in ms by the TLS 1.3 spec.

2022-09-13 02:51 UTC, yuhaoth commented on tests/ssl-opt.sh
> +run_test    "TLS 1.3: PSK: default suite. m->m" \
Yes.

2022-09-13 06:16 UTC, yuhaoth commented on library/ssl_tls13_server.c
> +               ( obfuscated_ticket_age - session->ticket_age_add );
Fix it with some differences. Please double check.

2022-09-14 01:49 UTC, yuhaoth commented on library/ssl_tls13_keys.c
> +             mbedtls_md_get_size( mbedtls_md_info_from_type( md_type ) ) );
This can not be replace. input parameter of `mbedtls_md_get_size` is `const mbedtls_md_info_t *`.

2022-09-14 01:55 UTC, yuhaoth commented on library/ssl_tls13_client.c
> +            case MBEDTLS_TLS_EXT_SERVERNAME:
we got `server_name` extension from GnuTLS/OpenSSL server.  But the current code return unsupported extension error. According to spec, it should be allowed. 

And this is the reason why I add #6170 .

2022-09-14 02:25 UTC, yuhaoth commented on library/ssl_tls13_client.c
> +            ssl->session_negotiate->ticket_age_add;
yes.

2022-09-14 06:19 UTC, yuhaoth commented on library/ssl_tls13_server.c
> +               ( obfuscated_ticket_age - session->ticket_age_add );
Found bellow error, it is come from `TLS 1.3: NewSessionTicket: Basic check, G->m` . 
```
ssl_tls13_server.c:0144: |2| => check_identity_match_ticket
ssl_tls13_server.c:0231: |3| Ticket expired: Ticket age outside tolerance window ( diff=-10 )
ssl_tls13_server.c:0243: |2| <= check_identity_match_ticket
```
I think the case might be caused by below reason.

- `now == session->start `, that means the time of ticket create and receive from client is in one seconds. As a result, `age_in_ms` is zero and `client_age_in_ms` is not zero. 
- Client cpu timer is faster than server. 

So, I think we should add negative tolerance window.  I prefer change the `diff` check to 

```
if( ( age_in_ms - client_age_in_ms ) > MBEDTLS_SSL_TLS1_3_TICKET_AGE_TOLERANCE/2 || 
     ( client_age_in_ms  - age_in_ms ) > MBEDTLS_SSL_TLS1_3_TICKET_AGE_TOLERANCE/2  )
```

2022-09-14 12:20 UTC, ronald-cron-arm requested changes
A few remaining issues, otherwise this looks good to me.

2022-09-14 14:22 UTC, yuhaoth commented on library/ssl_tls13_client.c
> +            (uint32_t)( ( age_in_ms + ssl->session_negotiate->ticket_age_add )
It is come from https://github.com/Mbed-TLS/mbedtls/pull/6167#discussion_r962552078 . 

I think it can improve readability.

2022-09-15 07:19 UTC, ronald-cron-arm requested changes
Two last minor things.

2022-09-15 07:19 UTC, ronald-cron-arm commented on library/ssl_tls13_server.c
> +        mbedtls_ssl_session *i_session=(mbedtls_ssl_session *)session;
`i_session` is not necessary anymore as now `session` has the right type.

2022-09-15 07:19 UTC, ronald-cron-arm commented on library/ssl_tls13_server.c
> +     *       that.
```suggestion
     * NOTE: When `now == session->start`, `age_diff_in_ms` may be negative
     *       as the age units are different on the server (s) and in the client (ms)
     *       side. Add a -1000 ms tolerance window to take this into account.
```

2022-09-15 08:29 UTC, ronald-cron-arm approved these changes
LGTM. @xkqian please have a look to this last version.

2022-09-16 04:33 UTC, yuhaoth commented
This PR got a merge test fail. https://jenkins-mbedtls.oss.arm.com/blue/organizations/jenkins/mbed-tls-pr-merge/detail/PR-6167-merge/43/pipeline

fix it with https://github.com/Mbed-TLS/mbedtls/pull/6167/commits/a5df584d87a3bf6f929a60dba84906eb0f886cd3

2022-09-16 07:41 UTC, ronald-cron-arm requested changes

2022-09-16 07:41 UTC, ronald-cron-arm commented on library/ssl_tls13_keys.c
> +                PSA_ALG_HMAC( mbedtls_hash_info_psa_from_md( md_type ) ) ) );
```suggestion
                mbedtls_hash_info_psa_from_md( md_type ) ) );
```
not sure why we would need PSA_ALG_HMAC here. Then to do the MD type to PSA alg translation, just above we use `mbedtls_psa_translate_md( md_type )` thus I would suggest to use the same here, thus:
```suggestion
                mbedtls_psa_translate_md( md_type ) ) );
```

2022-09-16 09:27 UTC, ronald-cron-arm approved these changes
LGTM

2022-09-16 10:32 UTC, xkqian approved these changes
LGTM

2022-09-18 19:18 UTC, merged