Improve ECDSA verify validation - 2.28 backport
Mbed-TLS/mbedtls pull request #6191
Opened 2022-08-10 10:44 UTC by daverodgman

Trivial backport of #6190

2022-08-11 13:27 UTC, tom-cosgrove-arm approved these changes
LGTM. Faithful backport

2022-08-11 13:28 UTC, tom-cosgrove-arm commented
(I will leave the `approved` off this until the main PR has two approvals)

2022-08-18 10:54 UTC, gilles-peskine-arm requested changes
Rejecting the error code change in an LTS branch.

2022-08-18 10:54 UTC, gilles-peskine-arm commented on library/ecdsa.c
> +        ret = MBEDTLS_ERR_ECP_BAD_INPUT_DATA;
Either error code is arguably correct. In an LTS, we should err on the side of being conservative.

2022-08-22 12:51 UTC, tom-cosgrove-arm submitted a review, later dismissed
LGTM. Faithful backport.

2022-09-23 09:43 UTC, daverodgman commented
Trivial rebase onto latest mbedtls-2.28 just to test Travis - no changes made

2022-09-23 11:17 UTC, tom-cosgrove-arm submitted a review, later dismissed
LGTM

2022-10-26 17:44 UTC, gilles-peskine-arm requested changes
This is a failthful backport of https://github.com/Mbed-TLS/mbedtls/pull/6190, and has the same issues in the changelog entry.

2022-10-28 09:52 UTC, tom-cosgrove-arm approved these changes
Faithful backport, now matching #6190 with fixed ChangeLog entry

2022-10-28 13:48 UTC, gilles-peskine-arm approved these changes
LGTM

2022-10-31 09:37 UTC, merged