Move TLS related code from test_suite_ssl.function to ssl_helpers.c and ssl_helpers.h
Mbed-TLS/mbedtls pull request #6202
Opened 2022-08-15 07:27 UTC by zhangsenWang

## Description
`test_suite_ssl.function` contains many functions that are used to set up a TLS connection. Move those functions (and the types they use) to a new file `tests/src/ssl_helpers.c` with declarations in `tests/include/test/ssl_helpers.h`

## Status
**READY**

## Requires Backporting
Yes, 2.28.

## Additional comments
target issue #6173 

## Todos
- [x] create `ssl_helpers.h` and `ssl_helpers.c`
- [x] rename types that need to be moved
- [x] move types to `ssl_helpers.h`
- [x] rename functions that need to be moved
- [x] adjust format to limit line length 
- [x] move functions to `ssl_helpers.c` and add declaration to `ssl_helpers.h`
- [ ] backport

2022-08-16 06:21 UTC, xkqian requested changes
I haven't gone through all of the code, just give out draft comments.   Please pay attention to the line width < 80 characters and vertical alligned.

2022-08-16 06:21 UTC, xkqian commented on tests/src/ssl_helpers.c
> +                                                            size_t capacity )
```suggestion
                                size_t capacity )
```
Vertical alligned

2022-08-16 06:21 UTC, xkqian commented on tests/src/ssl_helpers.c
> +                             const unsigned char *input, size_t input_len )
```suggestion
                                 const unsigned char *input, size_t input_len )
```
Vertical alligned

2022-08-16 06:21 UTC, xkqian commented on tests/src/ssl_helpers.c
> +                             unsigned char* output, size_t output_len )
vertical alligned

2022-08-16 06:21 UTC, xkqian commented on tests/src/ssl_helpers.c
> +    if( ( buf == NULL ) || ( buf->buffer == NULL ) )
```suggestion
    if( buf == NULL || buf->buffer == NULL )
```

2022-08-16 06:21 UTC, xkqian commented on tests/src/ssl_helpers.c
> +    if ( ( buf->content_length + input_len ) > buf->capacity )
```suggestion
    if ( buf->content_length + input_len > buf->capacity )
```

2022-08-16 06:21 UTC, xkqian commented on tests/src/ssl_helpers.c
> +    if( ( buf == NULL ) || ( buf->buffer == NULL ) )
```suggestion
    if( buf == NULL || buf->buffer == NULL )
```

2022-08-16 06:21 UTC, xkqian commented on tests/src/ssl_helpers.c
> +    {
```suggestion
```

2022-08-16 06:21 UTC, xkqian commented on tests/src/ssl_helpers.c
> +    }
```suggestion
```

2022-08-16 06:21 UTC, xkqian commented on tests/src/ssl_helpers.c
> +                                      size_t capacity )
vertical alligned

2022-08-16 06:21 UTC, xkqian commented on tests/src/ssl_helpers.c
> +                                        size_t buf_len, size_t* msg_len )
```suggestion
                                        size_t buf_len, size_t *msg_len )
```

2022-08-16 06:21 UTC, xkqian commented on tests/src/ssl_helpers.c
> +void mbedtls_test_mock_socket_close( mbedtls_test_mock_socket* socket )
```suggestion
void mbedtls_test_mock_socket_close( mbedtls_test_mock_socket *socket )
```

2022-08-16 06:21 UTC, xkqian commented on tests/src/ssl_helpers.c
> +                                 mbedtls_test_mock_socket* peer2,
vertical alligned

2022-08-16 06:21 UTC, xkqian commented on tests/src/ssl_helpers.c
> +    {
```suggestion
```

2022-08-16 06:21 UTC, xkqian commented on tests/src/ssl_helpers.c
> +    }
```suggestion
```

2022-08-16 06:21 UTC, xkqian commented on tests/src/ssl_helpers.c
> +    {
```suggestion
```

2022-08-16 06:21 UTC, xkqian commented on tests/src/ssl_helpers.c
> +    }
```suggestion
```

2022-08-16 06:21 UTC, xkqian commented on tests/src/ssl_helpers.c
> +                                  mbedtls_test_ssl_message_queue* queue_output,
vertical alligned

2022-08-16 06:21 UTC, xkqian commented on tests/src/ssl_helpers.c
> +                                                                    size_t len )
vertical alligned

2022-08-16 06:21 UTC, xkqian commented on tests/src/ssl_helpers.c
> +    {
```suggestion
```

2022-08-16 06:21 UTC, xkqian commented on tests/src/ssl_helpers.c
> +    }
```suggestion
```

2022-08-16 06:21 UTC, xkqian commented on tests/src/ssl_helpers.c
> +                            int endpoint_type,
vertical alligned

2022-08-16 06:21 UTC, xkqian commented on tests/src/ssl_helpers.c
> +            mbedtls_test_mock_tcp_send_msg,
vertical alligned

2022-08-16 06:21 UTC, xkqian commented on tests/src/ssl_helpers.c
> +            mbedtls_test_mock_tcp_send_nb,
ditto

2022-08-16 06:21 UTC, xkqian commented on tests/src/ssl_helpers.c
> +                            mbedtls_test_message_socket_context *context )
ditto

2022-08-16 06:21 UTC, xkqian commented on tests/src/ssl_helpers.c
> +    {
Remove the '{' and '}' , the same as line 824,826,828

2022-08-16 06:21 UTC, xkqian commented on tests/src/ssl_helpers.c
> +                                     mbedtls_ssl_context *second_ssl,
ditto

2022-08-16 06:21 UTC, xkqian commented on tests/src/ssl_helpers.c
> +    {
ditto

2022-08-16 06:21 UTC, xkqian commented on tests/src/ssl_helpers.c
> +                      int* forced_ciphersuite )
```suggestion
                      int *forced_ciphersuite )
```

2022-08-16 06:21 UTC, xkqian commented on tests/src/ssl_helpers.c
> +                  const unsigned char *name, size_t name_len )
ditto

2022-08-16 06:21 UTC, xkqian commented on tests/src/ssl_helpers.c
> +                                        const unsigned char *iv, size_t iv_len,
ditto

2022-08-16 06:21 UTC, xkqian commented on tests/src/ssl_helpers.c
> +                                    mbedtls_ssl_transform *t_out,
vertical alligned

2022-08-23 07:19 UTC, zhangsenWang commented
The line width and vertical align issues have be revised.  Besides, in the process of finding out reason of some check failure, I encounter some points and finally solve them in my own way. I'm not sure if it's suitable.

1. I add one library `mbedtls_ssl_test` in `CMakeLists.txt`. The reason is that since all files in `tests/src` are compiled into an OBJECT library `mbedtls_test`, but our `tests/src/ssl_helpers.c` need many functions in the `library` , other programs (such as those in `programs`) that need library `mbedtls_test `will have to link the functions in the `library`. which will cause undefined reference.  This error only occurs when using cmake, nothing need to be changed with the `Makefile`

2. use `#pragma` in `tests/src/ssl_helpers.c` to disable a warning `C4267 `about conversion from `size_t `to `int `etc. This warning is treated as error. This is because original `tests/test_suite_ssl.c` is compile with `tests/CMakeLists.txt` but now `tests/src/ssl_helpers.c` is compiled with `CMakeLists.txt`. The `CMAKE_C_CFLAGS `in these two file are not the same. This only   occurs under MSVC

I'm looking forward for your opinions, thanks.  @xkqian @gilles-peskine-arm

2023-05-17 16:50 UTC, davidhorstmann-arm commented
Was this superseded by #6500? Can it be closed?

2023-05-17 16:56 UTC, gilles-peskine-arm commented
Superseded by https://github.com/Mbed-TLS/mbedtls/pull/6500

2023-05-17 16:56 UTC, closed without merging