TLS 1.3:Add multiple pre-configured psk test for server
Mbed-TLS/mbedtls pull request #6260
Opened 2022-09-06 04:14 UTC by yuhaoth

## Description

Fix #6053 

It has been supported, but there are no tests for it . 

## Status
**READY**

2022-09-13 14:11 UTC, ronald-cron-arm requested changes
Just one suggestion.

2022-09-13 14:11 UTC, ronald-cron-arm commented on tests/opt-testcases/tls13-kex-modes.sh
> +P_SRV_PSK_LIST="psk_list=abc,dead,def,beef,Client_identity,6162636465666768696a6b6c6d6e6f70"
To exercise in different ways the PSK look-up code on server side, what about to have 3 lists:
1) One with the Client_identity PSK being first in the list
2) One with the Client_identity PSK being last in the list (as the current one)
3) One with the Client_identity PSK being in the middle
and to use them in a randomly manner in the various tests.

2022-09-14 12:33 UTC, ronald-cron-arm approved these changes
LGTM

2022-09-14 12:35 UTC, ronald-cron-arm commented
@xkqian could you please review this PR. This looks good to me.

2022-09-14 13:29 UTC, xkqian commented on tests/opt-testcases/tls13-kex-modes.sh
> +    case $(( TESTS % 3 )) in
What's the value of TESTS?

2022-09-15 02:03 UTC, yuhaoth commented on tests/opt-testcases/tls13-kex-modes.sh
> +    case $(( TESTS % 3 )) in
It is set by `run_test` function.

2022-09-15 02:07 UTC, xkqian approved these changes
LGTM

2022-09-15 06:58 UTC, merged