TLS 1.3: PSK: Exclude pre_shared_key for HRR
Mbed-TLS/mbedtls pull request #6304
Opened 2022-09-21 03:06 UTC by yuhaoth

## Description
`pre_shared_key` extension is not allowed for HRR message. 

## Status
**READY**

2022-09-21 07:31 UTC, ronald-cron-arm requested changes
This looks good to me but the certificate settings in the tests that are not necessary.

2022-09-21 07:31 UTC, ronald-cron-arm commented on tests/opt-testcases/tls13-kex-modes.sh
> +         "$P_SRV crt_file=data_files/ecdsa_secp256r1.crt key_file=data_files/ecdsa_secp256r1.key force_version=tls13 tls13_kex_modes=psk_ephemeral debug_level=5 psk_list=Client_identity,6162636465666
```suggestion
         "$P_SRV force_version=tls13 tls13_kex_modes=psk_ephemeral debug_level=5 psk_list=Client_identity,6162636465666768696a6b6c6d6e6f70,abc,dead,def,beef curves=secp384r1" \
```

2022-09-21 07:31 UTC, ronald-cron-arm commented on tests/opt-testcases/tls13-kex-modes.sh
> +         "$O_NEXT_CLI_NO_CERT -CAfile data_files/test-ca2.crt -tls1_3 -msg -allow_no_dhe_kex -psk_identity Client_identity -psk 6162636465666768696a6b6c6d6e6f70 -groups P-256:P-384" \
```suggestion
         "$O_NEXT_CLI_NO_CERT -tls1_3 -msg -allow_no_dhe_kex -psk_identity Client_identity -psk 6162636465666768696a6b6c6d6e6f70 -groups P-256:P-384" \
```

2022-09-21 07:31 UTC, ronald-cron-arm commented on tests/opt-testcases/tls13-kex-modes.sh
> +         "$P_SRV crt_file=data_files/ecdsa_secp256r1.crt key_file=data_files/ecdsa_secp256r1.key force_version=tls13 tls13_kex_modes=psk_ephemeral debug_level=5 psk_list=Client_identity,6162636465666
```suggestion
         "$P_SRV force_version=tls13 tls13_kex_modes=psk_ephemeral debug_level=5 psk_list=Client_identity,6162636465666768696a6b6c6d6e6f70,abc,dead,def,beef curves=secp384r1" \
```

2022-09-21 07:31 UTC, ronald-cron-arm commented on tests/opt-testcases/tls13-kex-modes.sh
> +         "$G_NEXT_CLI_NO_CERT --debug=4 --single-key-share --x509cafile data_files/test-ca2.crt --priority NORMAL:-VERS-ALL:-KX-ALL:+ECDHE-PSK:+DHE-PSK:+PSK:+VERS-TLS1.3:-GROUP-ALL:+GROUP-SECP256R1:+
```suggestion
         "$G_NEXT_CLI_NO_CERT --debug=4 --single-key-share --priority NORMAL:-VERS-ALL:-KX-ALL:+ECDHE-PSK:+DHE-PSK:+PSK:+VERS-TLS1.3:-GROUP-ALL:+GROUP-SECP256R1:+GROUP-SECP384R1 --pskusername Client_identity --pskkey 6162636465666768696a6b6c6d6e6f70 localhost" \
```

2022-09-21 15:30 UTC, ronald-cron-arm approved these changes
LGTM. Thanks.

2022-09-21 15:31 UTC, ronald-cron-arm commented
@xkqian could you please review this PR ?

2022-09-22 07:56 UTC, xkqian commented
I have gone through the code and run the test cases locally, LGTM.

2022-09-22 07:57 UTC, xkqian approved these changes
LGTM

2022-09-22 08:21 UTC, merged