Improve outcome analysis for driver-only builds
Mbed-TLS/mbedtls pull request #6435
Opened 2022-10-17 10:32 UTC by mpg

## Description

Improve outcome analysis by using an exclude list rather than an include list for test suites to compare, and making the reference configuration closer to the driver-based configuration.

## Status
**READY**

## Requires Backporting

NO  - the script is in development only, to test development-only features

## Requires ChangeLog

NO - this is a developer-only script

2022-10-18 06:19 UTC, mprse reviewed
Tested script locally and found one general problem: `test_psa_crypto_config_accel_hash_use_psa`
is now running `ssl-opt.sh` and `compat.sh` which are redundant for our case and take lots of time. We can comment out this part from the test component, but it is easy to forget. 

Additionally we will need more reference configurations, so maybe we could have keep reference implementations for hash, cipher, aead, etc. in the separate file.

Change looks good and works fine.

2022-10-18 08:36 UTC, mpg commented
@mprse Thanks for your review!

> Tested script locally and found one general problem: `test_psa_crypto_config_accel_hash_use_psa` is now running `ssl-opt.sh` and `compat.sh` which are redundant for our case and take lots of time. We can comment out this part from the test component, but it is easy to forget.

Indeed, I added something for that.
 
> Additionally we will need more reference configurations, so maybe we could have keep reference implementations for hash, cipher, aead, etc. in the separate file.

Good point. I've given it some thought, and actually, I think this script should be only for the work in progress (so, hash so far, and very soon moving to cipher+aead). Work that's complete (so, hash as soon as #6437 is done) should actually be tested in the CI. I'll create issues about that.

2022-10-18 09:17 UTC, mpg commented
Ok, I've created https://github.com/Mbed-TLS/mbedtls/issues/6445 to add that analysis for hashes to the CI immediately, and left a note in https://github.com/Mbed-TLS/mbedtls/issues/6337 to add it for cipher+aead when we're done.

2022-10-18 09:26 UTC, mprse commented
The sign-off in commit is missing and CI is failing.

2022-10-18 13:19 UTC, mprse submitted a review, later dismissed
LGTM.
Restarted Ci as it has glitched. 
(Test results provided in https://github.com/Mbed-TLS/mbedtls/pull/6447#issue-1413193492)

2022-10-19 09:36 UTC, AndrzejKurek commented on docs/architecture/psa-migration/outcome-analysis.sh
> +IGNORE="$IGNORE hkdf" # disabled
A bit of an explanation here would help.

2022-10-19 09:40 UTC, AndrzejKurek commented on tests/scripts/all.sh
> +        echo "skip sh scripts"
More detail here would be great: "compat.sh and ssl-opt.sh skipped"

2022-10-19 09:42 UTC, AndrzejKurek commented on docs/architecture/psa-migration/outcome-analysis.sh
> +    make neat
Wow, I didn't know that target :)

2022-10-19 10:01 UTC, AndrzejKurek requested changes
Just two cosmetic remarks.

2022-10-19 10:27 UTC, AndrzejKurek approved these changes

2022-10-19 12:42 UTC, mprse approved these changes

2022-10-19 13:54 UTC, merged