all.sh: support build & test on ARM64 Host
Mbed-TLS/mbedtls pull request #6459
Opened 2022-10-20 02:34 UTC by lpy4105

## Description
Resovles: Build on Arm64 HOST Fail #5758

Add functions in test/scripts/all.sh:

- Identify the `aarch64` target of the compiler on the host
- Check if the compiler supports A64 SHA512 instructions based on its version
- Generate the `-march` switch for SHA{512/256} acceleration
- Check the compiler version and add `-march` switch for each components that enables `MBEDTLS_SHA{512/256}_USE_A64_CRYPTO_*`

## Status
**READY**

## Additional comments
Tested on local ARM64 host

2022-10-24 13:07 UTC, yuhaoth requested changes
- ‘SHA_FLAGS' is local variable, please use lower case.
- If there is only one CFLAGS, please do not introduce `SHAFLAGS`

2022-10-24 13:07 UTC, yuhaoth commented on scripts/mbedtls_dev/c_build_helper.py
> +        cflags = os.getenv('CFLAGS', '')
```suggestion
        cflags = os.getenv('CFLAGS', None)
```

2022-10-24 13:07 UTC, yuhaoth commented on tests/scripts/all.sh
> +    fi
I do not think we should filter them by name. 

The condition should be ：
- `MBEDTLS_SHA{512/256}_USE_A64_CRYPTO_*` is enabled
- compiler target is `aarch64`

2022-10-24 14:57 UTC, lpy4105 commented on tests/scripts/all.sh
> +    fi
> That can be replace by `config.py get MBEDTLS_SHA{512/256}_USE_A64_CRYPTO_*` And just check it before build in all component.

This approach is not identical to the current implementation. `config.py get MBEDTLS_SHA{512/256}_USE_A64_CRYPTO_*` wouldn't get correct value until we have configured, which means we couldn't know if the compiler version should be checked before the component is running. I'm not sure if that is acceptable.

2022-10-27 06:28 UTC, lpy4105 commented
Rebased to due to conflicts.

2022-11-01 08:10 UTC, lpy4105 commented
Rebased to resolve conflicts.

2022-11-08 02:43 UTC, yuhaoth approved these changes
LGTM

2022-11-11 07:01 UTC, yuhaoth commented
In nightly build, the build was cancelled and mark this PR fail. I am not sure why.

2022-11-11 08:34 UTC, yuhaoth commented
Internal CI pass. 
OpenCI cancel the build in nightly build and mark it fail.

2023-01-16 13:23 UTC, daverodgman commented
If it's old, it will not run in the nightly CI and will be (inaccurately) shown as a failure. You can force-push to re-trigger the CI, or manually re-trigger it via Jenkins.

2023-01-16 13:25 UTC, daverodgman commented
@gilles-peskine-arm I think this may be a pre-requisite for #5387 so please bump up your review queue when you have a chance.

2023-01-27 15:37 UTC, gilles-peskine-arm requested changes
This change is far too invasive for what it does. I think it's solving problems in the wrong place.

> This issue is related to incorrect -march settings when building with MBEDTLS_SHA{512/256}_USE_A64_CRYPTO_*

`all.sh` does not enable the `USE_A64_CRYPTO` symbols explicitly. If they're getting enabled when they shouldn't, that's a problem in other scripts (or in the C code, but I don't think we ever automatically enable this symbol within the C code).

I see several potential problems, and I'm not sure what's actually a problem, and if/where each problem is solved.

* The library should build out of the box on an arm64 host with/without crypto extensions, with reasonable compilers (in particular old or recent clang). This should be handled in the C code and `Makefile` and `CMakeLists.txt`, not `all.sh`.
* The library should use the crypto extensions where available (which again depends on the compiler). This should ideally not be handled in `all.sh`, but we may need to help sometimes by setting `CFLAGS`.
* Some auxiliary scripts call a C compiler (e.g. `generate_psa_constants.py`, `check_names.py`. I don't understand why we'd need to set `CFLAGS` here though: what's the problem, as long as we aren't cross-compiling?
* A few components are x86-specific (`m32`, `mx32`). _That_ is a good reason for a `support` function.

2023-01-31 07:27 UTC, lpy4105 commented
As @yuhaoth are working on new solutions of the issue, see https://github.com/Mbed-TLS/mbedtls/issues/5758#issuecomment-1381556465, I will split the bug fix commits that are not related to the issue into another PR, so that they could be merged first.

2023-02-01 04:12 UTC, lpy4105 commented
@gilles-peskine-arm Just to answer your questions.

> all.sh does not enable the USE_A64_CRYPTO symbols explicitly. If they're getting enabled when they shouldn't, that's a problem in other scripts (or in the C code, but I don't think we ever automatically enable this symbol within the C code).

Neither `all.sh` nor C code enables USE_A64_CRYPTO symbols **"explicitly"**. The problem is `config.py`, `config.py full/crypto` enables those symbols. So most of the test cases in `all.sh` enable those symbols implicitly.

> - The library should build out of the box on an arm64 host with/without crypto extensions, with reasonable compilers (in particular old or recent clang). This should be handled in the C code and Makefile and CMakeLists.txt, not all.sh.
> - The library should use the crypto extensions where available (which again depends on the compiler). This should ideally not be handled in all.sh, but we may need to help sometimes by setting CFLAGS.

I agree that the the library should be build out of the box on an arm64 host with/without crypto extensions. I think @yuhaoth is working on this. After the new solution is proposed, I will adapt this PR to cover the compile time detection in `all.sh`.

>- Some auxiliary scripts call a C compiler (e.g. generate_psa_constants.py, check_names.py. I don't understand why we'd need to set CFLAGS here though: what's the problem, as long as we aren't cross-compiling?

If USE_A64_CRYPTO symbols were enabled but CFLAGS is not provided, the error would occur from the current build system, no matter what script it is. But with the new solution, CFLAGS might not be required and this might not be a problem.

2023-04-11 07:06 UTC, yuhaoth commented
#6459 has been fixed by other PRs.

2023-04-11 07:06 UTC, closed without merging