TLS 1.3: Fix tls13 mbedtls ssl is handshake over
Mbed-TLS/mbedtls pull request #6476
Opened 2022-10-24 01:33 UTC by yuhaoth

## Description
fix #6312

- Add `MBEDTLS_SSL_NEW_SESSION_TICKETS` and `MBEDTLS_SSL_NEW_SESSION_TICKETS_FLUSH` into handshake over state
- Replace internal usage of `mbedtls_ssl_is_handshake_over

## Status
**READY**

2022-10-26 08:04 UTC, ronald-cron-arm requested changes

2022-10-26 08:04 UTC, ronald-cron-arm commented on library/ssl_msg.c
> +            if( ssl->state != MBEDTLS_SSL_HANDSHAKE_OVER  )
I would rather keep `mbedtls_ssl_is_handshake_over()` by default and change to `ssl->state !=/== MBEDTLS_SSL_HANDSHAKE_OVER` only where necessary for the writing and reading of post-handshake messages. Thus in `mbedtls_ssl_handshake()`, `mbedtls_ssl_handshake_step()`, `mbedtls_ssl_read/write()` and this should be about it (but I may miss other here).

2022-10-28 16:04 UTC, ronald-cron-arm requested changes
Just one thing I spotted. I will need to check the changes in ssl_tls.c and ssl_msg.c.

2022-11-06 02:48 UTC, yuhaoth commented
Rebase to trigger CI.

2022-11-07 04:54 UTC, yuhaoth commented
OpenCI got failure. But Internal CI pass

2022-11-09 08:10 UTC, ronald-cron-arm requested changes
I am not sure about the changes in DTLS 1.2 specific code.

2022-11-18 10:14 UTC, yuhaoth commented
I think we might need a separate function for `post handshake message` .  Then we do not need break current code and improve the readability. 

For current code, if the ticket is expired after handshake over, we do not have chance re-send and receive new ticket. As my understand , we should refresh the ticket if the old one is expired.  I am not very sure this point.

2022-11-20 06:43 UTC, yuhaoth commented
Just take a look at session ticket code of TLS1.2. It saves the ticket after handshake over.  And TLS 1.3 will return  `MBEDTLS_ERR_SSL_RECEIVED_NEW_SESSION_TICKET` in `mbedtls_ssl_handshake` to ask user save the ticket.  That looks different. And `mbedtls_ssl_{read,write}` might return this error also, but there is no code for it in `ssl_client2.c`

And I take a  quick look on OpenSSL, BoringSSL and GnuTLS. As my understand now(might be wrong), they maintain a session ticket cache and before resumption, user should lookup the cache with API and set session.

**How about remove `MBEDTLS_ERR_SSL_RECEIVED_NEW_SESSION_TICKET` and add a callback function ?** That will look similar with TLS1.2, GnuTLS, BoringSSL and OpenSSL. If OKay, I will create an issue for it.
- If session ticket is updated, `mbedtls_ssl_{read,write}` does not need process it. To do resumption, user just need pickup a right ticket from session ticket cache.
- If the callback is not set, only the last session ticket will be received by user code.
- If the callback is set, user should implement a session ticket cache for it and lookup the cache before resumption.

2022-11-22 08:24 UTC, ronald-cron-arm commented
> Just take a look at session ticket code of TLS1.2. It saves the ticket after handshake over. And TLS 1.3 will return `MBEDTLS_ERR_SSL_RECEIVED_NEW_SESSION_TICKET` in `mbedtls_ssl_handshake` to ask user save the ticket. That looks different. And `mbedtls_ssl_{read,write}` might return this error also, but there is no code for it in `ssl_client2.c`
> 
> And I take a quick look on OpenSSL, BoringSSL and GnuTLS. As my understand now(might be wrong), they maintain a session ticket cache and before resumption, user should lookup the cache with API and set session.
> 
> **How about remove `MBEDTLS_ERR_SSL_RECEIVED_NEW_SESSION_TICKET` and add a callback function ?** That will look similar with TLS1.2, GnuTLS, BoringSSL and OpenSSL. If OKay, I will create an issue for it.
> 
>     * If session ticket is updated, `mbedtls_ssl_{read,write}` does not need process the error. To do resumption, user just need pickup a right ticket from session ticket cache.
> 
>     * without the callback, only the last session ticket will be received by user code.
> 
>     * with the callback, user should implement a session ticket cache for it and lookup the cache before resumption.

That's an interesting point and we should consider it. Please create an investigation task to not forget about it. To ease the transition if we eventually do it I have just made MBEDTLS_ERR_SSL_RECEIVED_NEW_SESSION_TICKET experimental (see https://github.com/Mbed-TLS/mbedtls/pull/6638).

2022-11-23 08:28 UTC, ronald-cron-arm approved these changes
LGTM

2022-11-23 10:45 UTC, xkqian commented
It looks quite good to me except a question about the coverage of the test cases?   I just note that somewhere we keep the **mbedtls_ssl_is_handshake_over()** there, and somewhere we will detect the actual state with **ssl->state != MBEDTLS_SSL_HANDSHAKE_OVER** , do we need extra test cases to cover them?

2022-11-23 11:05 UTC, xkqian approved these changes
LGTM

2022-11-23 11:12 UTC, merged