Update PR template
Mbed-TLS/mbedtls pull request #6514
Opened 2022-10-31 15:24 UTC by daverodgman

Aim is to simplify the template, and provide gatekeepers / release-leads with a quick checklist of the things that are often missed.

2022-11-01 17:20 UTC, gilles-peskine-arm requested changes
The new PR template is nice and short. I think a lot of people just go TL,DR on the current one.

Please keep the mention of reviews in `CONTRIBUTING.md`.

2022-11-01 17:20 UTC, gilles-peskine-arm commented on CONTRIBUTING.md
> - - As with any open source project, contributions will be reviewed by the project team and community and may need some modifications to be accepted.
Please keep the part about reviews. It's typically the most visible aspect of contributing to Mbed TLS, so it deserves prominence.

2022-11-02 07:34 UTC, gilles-peskine-arm approved these changes
LGTM

2022-11-02 12:14 UTC, paul-elliott-arm approved these changes
LGTM

2022-11-02 13:05 UTC, merged