Enable mpi_mod_int test case to take full-range MPI integers
Mbed-TLS/mbedtls pull request #6573
Opened 2022-11-09 11:46 UTC by tom-cosgrove-arm

Also add commented-out test cases that currently fail

## Gatekeeper checklist

- [ ] **changelog** not required - this is tests
- [ ] **backport** will be needed
- [ ] **tests** these are tests

2022-11-09 17:30 UTC, wernerlewis submitted a review, later dismissed
LGTM

2022-11-09 18:01 UTC, gilles-peskine-arm requested changes
The test code is using the wrong type for signed integers. And while you're at it please make a couple of improvements in the data.

2022-11-10 13:16 UTC, gilles-peskine-arm approved these changes
LGTM

2022-11-10 13:16 UTC, gilles-peskine-arm commented on tests/suites/test_suite_bignum.function
> +    /* Since we're converting sign+magnitude to two's complement, we lose one
Technically, we don't require `mbedtls_mpi_sint` to have two's complement with naive overflow on conversion. If the value is out of range, the behavior is undefined, and could for example be a runtime fatal error (or nasal demons). But it's ok, we don't need to be robust against malformed test data. There is already plenty of test code that just assumes test data is within some allowed range.

2022-11-10 13:23 UTC, wernerlewis approved these changes

2022-11-14 12:03 UTC, yanesca commented
(Internal CI has passed)

2022-11-14 12:04 UTC, merged