Pr/workaround-gnutls_anti_replay_fail
Mbed-TLS/mbedtls pull request #6787
Opened 2022-12-15 02:40 UTC by yuhaoth

Signed-off-by: Jerry Yu <jerry.h.yu@arm.com>

## Description

Please write a few sentences describing the overall goals of the pull request's commits.

## Gatekeeper checklist

- [ ] **changelog** provided, or not required
- [ ] **backport** done, or not required
- [ ] **tests** provided, or not required

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

2023-01-07 08:06 UTC, yuhaoth commented
For time being, we want to solve #6623 with this solution.

2023-01-09 11:40 UTC, ronald-cron-arm requested changes
Two suggestions about the documentation. Otherwise, this looks good to me.

2023-01-10 07:57 UTC, ronald-cron-arm approved these changes
LGTM, please find a second reviewer.

2023-01-11 02:36 UTC, lpy4105 approved these changes
LGTM

2023-01-11 08:05 UTC, merged