WIP: TLS 1.3: Key Generation: change some key generation functions to static
Mbed-TLS/mbedtls pull request #6791
Opened 2022-12-15 09:37 UTC by yanrayw

## Description

Fix: #6675 

## Gatekeeper checklist

- [x] **changelog** not required, part of enhancing key generation in TLS 1.3.
- [x] **backport** not required
- [x] **tests** not required

## Comments
This PR only fixes one issue listed in https://github.com/Mbed-TLS/mbedtls/issues/6675.

2023-01-05 06:19 UTC, yuhaoth requested changes
Some nitpick improvements. And others look good to me

2023-01-05 06:19 UTC, yuhaoth commented on library/ssl_tls13_keys.c
> +static int mbedtls_ssl_tls13_key_schedule_stage_application(
```suggestion
static int ssl_tls13_key_schedule_stage_application(
```

2023-01-05 06:19 UTC, yuhaoth commented on library/ssl_tls13_keys.c
> +static int mbedtls_ssl_tls13_generate_handshake_keys(
```suggestion
static int ssl_tls13_generate_handshake_keys(
```

2023-01-05 06:19 UTC, yuhaoth commented on library/ssl_tls13_keys.c
> +static int mbedtls_ssl_tls13_generate_application_keys(
```suggestion
static int ssl_tls13_generate_application_keys(
```

2023-01-12 07:47 UTC, yanrayw commented
Since new code style was introduced, this PR was rebased to resolve all the conflicts. In addition, this PR was simplified from 4 commits to 2 commits since we don't have to focus on code style anymore.

2023-02-01 02:30 UTC, yuhaoth submitted a review, later dismissed
LGTM

2023-02-01 04:00 UTC, xkqian requested changes

2023-02-02 03:29 UTC, xkqian approved these changes
LGTM

2023-02-03 05:39 UTC, yuhaoth approved these changes
LGTM

2023-02-03 10:56 UTC, merged