Disable code style correction for bignum assembly
Mbed-TLS/mbedtls pull request #6876
Opened 2023-01-04 18:11 UTC by davidhorstmann-arm

The inline assembly defined in `bn_mul.h` confuses code style parsing, causing code style correction to fail. Disable code style correction for the whole section gated by `#if defined(MBEDTLS_HAVE_ASM)` to prevent this.

## Gatekeeper checklist

- [ ] ~**changelog** provided, or~ not required
- [ ] **backport** done, or not required
- [ ] ~**tests** provided, or~ not required

2023-01-04 18:19 UTC, gilles-peskine-arm commented on library/bn_mul.h
> +/* *INDENT-ON* */
Why restart styling here? Uncrustify doesn't particularly help with the rest of the file either.

2023-01-04 19:15 UTC, gilles-peskine-arm requested changes

2023-01-04 19:15 UTC, gilles-peskine-arm commented on scripts/code_style.py
> +    if fix_style_single_pass(src_file_list) != True:
[PEP8](https://peps.python.org/pep-0008/) is not happy (but I'll let it slide if pylint does).

2023-01-04 19:15 UTC, gilles-peskine-arm commented on library/bn_mul.h
> +/* *INDENT-ON* */
Uncrustify runs without erroring out if asked to restyle the rest of the file. But I'm not fully confident it'll do the right thing. And we might add more problematic assembly later for another architecture. So please keep the rest of the file unstyled.

2023-01-05 13:25 UTC, gilles-peskine-arm approved these changes
Thanks for the updates, LGTM

2023-01-05 13:31 UTC, daverodgman approved these changes

2023-01-05 13:35 UTC, merged