Have compat.sh and ssl-opt.sh not return success for > 255 errors
Mbed-TLS/mbedtls pull request #6927
Opened 2023-01-13 11:51 UTC by tom-cosgrove-arm

Fixes #2068

## Gatekeeper checklist

- [ ] **changelog** not required - this isn't a user-facing change
- [ ] **backport** in progress
- [ ] **tests** not required - these are minor fixes to test scripts

2023-01-13 12:00 UTC, daverodgman commented on tests/compat.sh
> +    FAILED=255
I'd put a comment to explain here

2023-01-13 12:01 UTC, daverodgman commented on tests/ssl-opt.sh
> +    FAILS=255
Again, comment would be good

2023-01-13 12:01 UTC, daverodgman requested changes
Ideally would be good to have comments IMO

2023-01-13 12:16 UTC, daverodgman approved these changes

2023-01-14 08:40 UTC, tom-cosgrove-arm commented
CI is green - ready to merge

2023-01-14 11:19 UTC, merged