mbedtls_mpi_sub_abs: Skip memcpy when redundant (#6701).
Mbed-TLS/mbedtls pull request #6942
Opened 2023-01-17 19:51 UTC by ucko

## Description

In some contexts, the output pointer may equal the first input pointer, in which case copying is not only superfluous but results in "Source and destination overlap in memcpy" errors from Valgrind (as I observed in the context of ecp_double_jac) and a diagnostic message from TrustInSoft Analyzer (as Pascal Cuoq reported in the context of other ECP functions called by cert-app with a suitable certificate).

I will be happy to supply a corresponding LTS PR in due course, particularly given that I'm using that branch myself.

(Split from #6930.)

## Gatekeeper checklist

- [ ] **changelog** provided, or not required
- [ ] **backport** done, or not required
- [ ] **tests** provided, or not required

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

2023-01-17 19:58 UTC, tom-cosgrove-arm commented on ChangeLog.d/conditionalize-mbedtls_mpi_sub_abs-memcpy.txt
> +     Analyzer in #6701; observed independently by Aaron Ucko under Valgrind.
I think the first sentence could be simply

`Fix potential undefined behaviour in mbedtls_mpi_sub_abs ().`

(ChangeLog entries are user facing, and users probably don't need to know that level of detail)

2023-01-17 20:05 UTC, ucko commented
That's fair, though I'll go with the US spelling of "behavior", for which I do see precedent. ;-)

2023-01-17 20:14 UTC, tom-cosgrove-arm approved these changes
LGTM

2023-01-31 20:25 UTC, gilles-peskine-arm requested changes
Looks good to me, but please [rewrite the commit messages to ensure that all commits have a signoff line](https://github.com/Mbed-TLS/mbedtls/pull/6942/checks?check_run_id=10708747165).

2023-01-31 20:34 UTC, ucko commented
AFAICT, only the ChangeLog simplification lacked such a line; fixed.  Thanks, and sorry for the accidental omission.

2023-01-31 20:38 UTC, tom-cosgrove-arm commented
Thanks for fixing that; can you prepare the backport now? We normally merge a PR and its backport at the same time, so we need both before this can be merged.

2023-01-31 20:38 UTC, tom-cosgrove-arm approved these changes
LGTM; just needs CI (I don't expect any problems now) and the backport

2023-01-31 20:54 UTC, ucko commented
Sounds good, thanks!  I've pushed a squashed backport: https://github.com/ucko/mbedtls/tree/2023a-bignum-2.28

2023-01-31 20:58 UTC, tom-cosgrove-arm commented
The backport should be raised as a second PR, targeting the branch `mbedtls-2.28`, with the same title as the original but with `[Backport 2.28]` prepended to the title. See, for example, PRs #6982 and #6983

2023-01-31 21:01 UTC, ucko commented
So I see, thanks.  Opened #7001.

2023-01-31 21:09 UTC, gilles-peskine-arm approved these changes
Thanks, LGTM

2023-02-01 10:36 UTC, merged