Minor improvements to `c_build_helper.py`
Mbed-TLS/mbedtls pull request #6975
Opened 2023-01-27 18:34 UTC by davidhorstmann-arm

This PR contains 2 improvements:
- Refactor `c_build_helper` to use a helper function for compilation. This allows a more flexible usage in other scripts that need to compile C code.
- Respect `$HOSTCC` for compilation if it is set, before falling back on `$CC`, allowing generated files to be generated when `$CC` is set for cross compiling.

## Gatekeeper checklist

- [ ] **changelog** provided, ~or not required~
- [ ] **backport** done, ~or not required~
- [ ] **tests** ~provided, or~ not required - Minor changes

2023-01-30 15:14 UTC, aditya-deshpande-arm approved these changes
LGTM - please link to the backport in the PR description though

2023-01-31 19:37 UTC, gilles-peskine-arm requested changes
LGTM apart from the changelog entry.

We should document this in [the relevant section of `README.md`](https://github.com/davidhorstmann-arm/mbedtls/blob/c-build-helper-improvements/README.md#generated-source-files-in-the-development-branch). And we should also test it. We can test it by changing one of the cross-compilation components of `all.sh` to doing `make neat` before building, and setting `HOSTCC`. (Separately for make and cmake, if we document that this works with both make and cmake.) We can do that in a follow-up PR.

2023-01-31 19:37 UTC, gilles-peskine-arm commented on ChangeLog.d/c-build-helper-hostcc.txt
> +     generated files. This allows them to be generated when CC is set for
“generation of the generated files” is uninformative. In contexts like this we call them “[generated] configuration-independent files”.

2023-01-31 19:38 UTC, gilles-peskine-arm commented
Should we backport this? In LTS branches, the configuration-independent generated files are tracked by Git so this would only be for the convenience of maintainers.

2023-02-01 13:38 UTC, davidhorstmann-arm commented
> Should we backport this? In LTS branches, the configuration-independent generated files are tracked by Git so this would only be for the convenience of maintainers. But keeping support scripts aligned facilitates future backports.

I tend to think that it'd be better to backport for alignment, even if this is not so useful in 2.28. The extra work required is fairly trivial.

2023-02-01 14:28 UTC, gilles-peskine-arm approved these changes

2023-02-01 15:04 UTC, aditya-deshpande-arm approved these changes

2023-02-07 09:25 UTC, merged