Fix incorrect dispatch to USAGE in example programs, which causes uninitialized memory to be used
Mbed-TLS/mbedtls pull request #6998
Opened 2023-01-31 15:08 UTC by aditya-deshpande-arm

## Description

Fixes issues #1120 and #6700.

Numerous example programs contain the following:
```
if (argc == 0) {
    goto USAGE;
}

// later in program
p = argv[1];
```
If a program is called from the shell then`argc = 1`, so the program will not go to USAGE due to the check. The access to `argv[1]` is accessing undefined memory. This PR changes the check to `if (argc < 2)`.

## Gatekeeper checklist

- [x] **changelog** provided
- [ ] **backport** TODO
- [ ] **tests** not required, example programs

2023-01-31 16:18 UTC, tom-cosgrove-arm commented on ChangeLog.d/fix-example-programs-no-args.txt
> +     ssl_mail_client.c.
Probably don't need so much detail, but should mention the issue numbers:

```
   * Fix behavior of sample programs when run with no arguments, which could
     access uninitialized memory in some cases. Fixes #6700 (which was found
     by TrustInSoft Analyzer during REDOCS'22) and #1120.
```

2023-01-31 16:58 UTC, tom-cosgrove-arm commented
I suspect the `Lost content` error on `all_u16-check_files` is a race condition while it was assembling the changelog the new version of the file came in, but the assembled changelog didn't include lines from that - i.e. a spurious failure

2023-01-31 16:58 UTC, tom-cosgrove-arm approved these changes
LGTM

2023-02-01 14:25 UTC, tom-cosgrove-arm commented
CI is failing because of

```
Trailing whitespace:
ChangeLog.d/fix-example-programs-no-args.txt: 3
^^^^check_files: Check: file sanity checks (permissions, encodings): tests/scripts/check_files.py -> 1^^^^
```

2023-02-01 14:26 UTC, tom-cosgrove-arm requested changes
Need to fix trailing whitespace

2023-02-01 17:04 UTC, tom-cosgrove-arm commented
The Travis failure is due to not having a newline at the end of the ChangeLog file:

```
Missing newline at end of file:
ChangeLog.d/fix-example-programs-no-args.txt
^^^^check_files: Check: file sanity checks (permissions, encodings): tests/scripts/check_files.py -> 1^^^^
```

2023-02-02 09:18 UTC, aditya-deshpande-arm commented
> The Travis failure is due to not having a newline at the end of the ChangeLog file:
> 
> ```
> Missing newline at end of file:
> ChangeLog.d/fix-example-programs-no-args.txt
> ^^^^check_files: Check: file sanity checks (permissions, encodings): tests/scripts/check_files.py -> 1^^^^
> ```

Ah, I didn't know that we needed those at the end of non-source files!

2023-02-02 09:24 UTC, tom-cosgrove-arm approved these changes
LGTM

2023-02-02 11:56 UTC, daverodgman submitted a review, later dismissed

2023-02-06 09:52 UTC, daverodgman approved these changes

2023-02-06 09:53 UTC, merged

2023-02-14 22:34 UTC, gilles-peskine-arm commented on programs/pkey/dh_genprime.c
> +    if (argc < 2) {
No, that's not right. This program doesn't require an argument. Several others don't either. https://github.com/Mbed-TLS/mbedtls/issues/7100