2.28 only: Fix the build without MBEDTLS_CERTS_C
Mbed-TLS/mbedtls pull request #7013
Opened 2023-02-01 17:51 UTC by gilles-peskine-arm

Fix several build errors when `MBEDTLS_CERTS_C` is disabled. I think all of them were regressions due to backporting changes from `development` where `certs.c` is now a test module (available in all configurations). Fixes #6243.

Add a component in `all.sh` so that the CI will complain us if this happens again.

## Gatekeeper checklist

- [x] **changelog** provided
- [x] **backport** (N/A: the option doesn't exist in `development`)
- [x] **tests** provided

2023-02-01 20:22 UTC, tom-cosgrove-arm approved these changes
LGTM - checked that each change is necessary, and that no more changes are required to build without `MBEDTLS_CERTS_C`, and that tests then pass

2023-02-01 22:26 UTC, tom-cosgrove-arm commented
Fails code style check :(

2023-02-01 22:29 UTC, tom-cosgrove-arm requested changes
Need to fix the code style

2023-02-02 06:07 UTC, tom-cosgrove-arm approved these changes
LGTM - only changes since previous approval are whitespace

2023-02-02 06:08 UTC, tom-cosgrove-arm commented on programs/ssl/ssl_server2.c
> +    mbedtls_printf(" ok (key types: %s - %s)\n",
indeed

2023-02-03 09:24 UTC, tom-cosgrove-arm commented
CI pass - the failure is a Windows infrastructure failure on Internal CI pr-head, but the corresponding OpenCI pr-head succeeded. Removing `needs-ci`

2023-02-06 11:38 UTC, daverodgman approved these changes

2023-02-06 11:39 UTC, merged