library: psa_crypto: Fix compilation error in psa_key_derivation_abort
Mbed-TLS/mbedtls pull request #7125
Opened 2023-02-17 09:40 UTC by joerchan

## Description

Fix compilation error in psa_key_derivation_abort when MBEDTLS_PSA_BUILTIN_ALG_TLS12_PRF is defined, but
MBEDTLS_PSA_BUILTIN_ALG_TLS12_PSK_TO_MS is not defined.

In function 'psa_key_derivation_abort':
error: 'psa_tls12_prf_key_derivation_t'
{aka 'struct psa_tls12_prf_key_derivation_s'} has no member named 'other_secret'

## Gatekeeper checklist

- [ ] **changelog** provided, or not required
- [ ] **backport** done, or not required
- [ ] **tests** provided, or not required

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

2023-02-21 22:47 UTC, gilles-peskine-arm requested changes
Thanks for the fix!

* [ ] Please [write a changelog entry](https://github.com/Mbed-TLS/mbedtls/blob/development/ChangeLog.d/00README.md).
* [x] 2.28 doesn't have `other_secret`, so this doesn't need a backport.
* [x] Ideally we'd like a non-regression test, but we can't test all combinations of build options, I don't think there's a good reason to test this specific combination as opposed to many others, and we don't currently have a framework to test combinations of KDFs (like we do for some other algorithms, and for each algorithm family it tends to be a significant amount of work). So I think we'll continue without a test.

2023-02-24 06:26 UTC, valeriosetti approved these changes
LGTM

2023-03-14 09:07 UTC, joerchan commented
@gilles-peskine-arm This was fixed in another patch:
https://github.com/Mbed-TLS/mbedtls/commit/6c7644150ac411b3ebc5fe94d9de064de6fee363

This did not add a changelog.

2023-03-14 09:07 UTC, closed without merging

2023-03-14 20:49 UTC, gilles-peskine-arm commented
Oh, looks like we accidentally fixed this bug while working on an unrelated feature. Thanks for noticing! I've submitted a changelog entry.