Backport 2.28: compat.sh: Skip static ECDH cases if unsupported in openssl
Mbed-TLS/mbedtls pull request #7153
Opened 2023-02-23 08:56 UTC by lpy4105

This PR is a backport of https://github.com/Mbed-TLS/mbedtls/pull/7137 to branch mbedtls-2.28.

Because `compat.sh` has changed a lot from `development` branch, the backport isn't a simple cherry-pick. The commit history has been reorganized.

2023-02-23 10:12 UTC, yanrayw requested changes
Looks good to me except for a typo.

2023-02-23 10:12 UTC, yanrayw commented on tests/compat.sh
> +                # If ti is NULL cipher ...
```suggestion
                # If it is NULL cipher ...
```
typo

2023-02-23 16:30 UTC, gilles-peskine-arm approved these changes
Looks good to me as a backport of https://github.com/Mbed-TLS/mbedtls/pull/7137. For this one I don't think we need to do anything different in 2.28.

2023-02-24 01:58 UTC, yanrayw approved these changes
LGTM

2023-02-28 17:11 UTC, merged