Fix segfault in mbedtls_oid_get_numeric_string
Mbed-TLS/mbedtls pull request #7270
Opened 2023-03-11 22:50 UTC by DemiMarie

When passed an empty OID, mbedtls_oid_get_numeric_string would read one byte from the zero-sized buffer and return an error code that depends on its value.  This is demonstrated by the test suite changes, which check that an OID with length zero and an invalid buffer pointer does not cause Mbed TLS to segfault.

Also check that second and subsequent subidentifiers are terminated, and add a test case for that.  Furthermore, stop relying on integer division by 40, use the same loop for both the first and subsequent subidentifiers, and add additional tests.

## Description

Please write a few sentences describing the overall goals of the pull request's commits.

## Gatekeeper checklist

- [ ] **changelog** provided, or not required
- [ ] **backport** done, or not required
- [ ] **tests** provided, or not required

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

2023-03-13 14:17 UTC, aditya-deshpande-arm commented
Hi Demi, thank you so much for contributing to Mbed TLS! We will try to review your PR as soon as we can.

As this is a bug fix, would you be comfortable doing the following two things:
1. Adding a ChangeLog entry for this PR. The instructions for this can be found [here](https://github.com/Mbed-TLS/mbedtls/blob/development/ChangeLog.d/00README.md)
2. Creating a backport PR for our LTS branch:  mbedtls-2.28

Thank you once again, and please feel free to reply with any questions you may have!

2023-03-15 12:34 UTC, davidhorstmann-arm requested changes
Thanks for catching this!

Looks good except that it needs a [ChangeLog entry](https://github.com/Mbed-TLS/mbedtls/blob/development/ChangeLog.d/00README.md) (since this is a fix). Something like:
```
Security
   * Fix a 1-byte out-of-bounds read in mbedtls_oid_get_numeric_string()
```

2023-03-15 12:48 UTC, tom-cosgrove-arm commented on library/oid.c
> +    for (i = 0; i < oid->len; i++) {
Now that `i` is only used within the body of this loop, we can narrow the scope with
```suggestion
    for (size_t i = 0; i < oid->len; i++) {
```

2023-03-15 12:50 UTC, tom-cosgrove-arm commented on library/oid.c
>      n = size;
(minor, pre-existing) would be nicer to declare and initialise these two at the same time

```
char *p = buf;
size_t n = size;
```

2023-03-15 13:05 UTC, DemiMarie commented
> Thanks for catching this!

You’re welcome!

> Looks good except for the [ChangeLog entry](https://github.com/Mbed-TLS/mbedtls/blob/development/ChangeLog.d/00README.md) (since this is a fix). Something like:
> 
> ```
> Security
>    * Fix a 1-byte out-of-bounds read in mbedtls_oid_get_numeric_string()
> ```

Will add a slightly longer entry explaining that this never made it into a release.  Should I credit myself as the bug reporter?

2023-03-15 13:18 UTC, tom-cosgrove-arm commented on ChangeLog.d/oid-oob-read.txt
> +      Marie Obenour before it appeared in git master or in any release tags, so
I presume it should be `development` here, not `master`?

2023-03-15 13:20 UTC, DemiMarie commented on ChangeLog.d/oid-oob-read.txt
> +      Marie Obenour before it appeared in git master or in any release tags, so
I meant the `master` branch, but will rephrase this to make it clearer.

2023-03-15 13:36 UTC, gilles-peskine-arm commented
> this never made it into a release

The changelog only describes differences between releases. For example the “Bugfix” subsection of the “Mbed TLS 3.4.0” section lists bugs that are present in Mbed TLS 3.3 (and possibly earlier versions) but no longer in Mbed TLS 3.4.0. So if the bug was not in any release, its fix shouldn't be announced in the changelog.

Sorry for the conflicting instructions — I guess previous reviewers didn't realize the bug had been introduced after the last release.

(Note — I'm assuming that it's correct that the buggy code was never released, I haven't personally checked.)

2023-03-15 14:00 UTC, davidhorstmann-arm commented
> (Note — I'm assuming that it's correct that the buggy code was never released, I haven't personally checked.)

That's correct as the bug was introduced in #7105, my apologies.

2023-03-15 14:03 UTC, davidhorstmann-arm approved these changes
LGTM

2023-03-15 16:26 UTC, minosgalanakis commented
Backport has been provided in #7295, removing label.

2023-03-16 05:03 UTC, DemiMarie commented
> > this never made it into a release
> 
> The changelog only describes differences between releases. For example the “Bugfix” subsection of the “Mbed TLS 3.4.0” section lists bugs that are present in Mbed TLS 3.3 (and possibly earlier versions) but no longer in Mbed TLS 3.4.0. So if the bug was not in any release, its fix shouldn't be announced in the changelog.

Can I conclude from this that only problems in released code (as opposed to development branches) are considered security vulnerabilities?

2023-03-16 09:29 UTC, davidhorstmann-arm approved these changes
LGTM, thanks again!

2023-03-16 09:33 UTC, gilles-peskine-arm commented
> Can I conclude from this that only problems in released code (as opposed to development branches) are considered security vulnerabilities?

Depends what you mean. We aim for the `development` branch to be secure at all times. (In contrast, we don't aim for it to have API stability: a new feature might have API-breaking changes until it's been in a release.) We treat security problems that appear only in `development` with the same urgency as security problems that appear in a release. A vulnerability is a vulnerability.

On the other hand, we would typically not issue a CVE for a vulnerability that was present for some time in the `development` branch, but never made it into a release.

I would recommend not using `development` in production, both to avoid using brand new features before their API has stabilized, and so you can track bug fixes (especially, but not limited to, security fixes).

The changelog lists differences between versions. That's why we don't mention bugs if they appeared after the last release, whether they're security bugs or not.

2023-03-16 09:46 UTC, tom-cosgrove-arm approved these changes
LGTM

2023-03-16 11:32 UTC, davidhorstmann-arm approved these changes
~LGTM - faithful backport!~ Posted on wrong PR, apologies

2023-03-16 12:21 UTC, merged