Add msvc support for AESCE
Mbed-TLS/mbedtls pull request #7316
Opened 2023-03-20 10:22 UTC by yuhaoth

## Description

This PR is enable MSVC support for AESCE module.

The code is verified under below condition.
- Build with VS2022 and `platformtoolsetversion=v143`
   - With VS2022, platformtoolsetversion=v141 build fail. 
- Test on Windows 10 with `selftest` 

> NOTE:  Build command `msbuild /nodeReuse:false /t:Rebuild /p:Configuration=Debug,Platform=ARM64,PlatformToolset=v143  "mbedTLS.sln"`

## Gatekeeper checklist

- [ ] **changelog** provided, or not required
- [ ] **backport** done, or not required
- [ ] **tests** provided, or not required

2023-03-20 14:21 UTC, daverodgman commented
AFAICT `platformtoolsetversion=v141` means VS 2017. We support VS 2013 - so if this doesn't work on VS 2017, it needs to detect the compiler version and only enable for recent versions of VS.

2023-03-20 14:53 UTC, tom-cosgrove-arm commented
This probably also needs an update to `check_config.h` around where it says

```
#error "MBEDTLS_AESCE_C defined, but not all prerequisites"
```

2023-03-20 15:56 UTC, tom-cosgrove-arm commented
There also needs to be a fix for around line 368 in `aesce.h`

```
/* use 'asm' as an optimisation barrier to prevent loading MODULO from memory */
asm ("" : "+w" (r));
```

2023-03-20 15:57 UTC, tom-cosgrove-arm commented on library/aesce.h
> +
Hmm, looks like the type errors are related to https://developercommunity.visualstudio.com/t/arm64-wrong-and-missing-types-in-arm64-neonh/1590951

2023-03-21 06:57 UTC, yuhaoth commented on library/aesce.h
> +
I did not get this error. What's your build command. It looks like msvc 2022.

2023-03-21 07:23 UTC, tom-cosgrove-arm commented on library/aesce.h
> +
I was using a custom makefile. The command it executed was as shown

```
cl -nologo -Ilibrary/ -Iinclude/ -Fobuild\library\ -c ./library\aesce.c
```

The compiler it was running was

`c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\HostARM64\ARM64/cl.exe`

2023-03-21 07:46 UTC, yuhaoth commented on library/aesce.h
> +
let me try it. 

I did not install arm64 host compiler. but I think it can be reproduced by same version.

2023-03-21 08:45 UTC, yuhaoth commented on library/aesce.h
> +
I tried it with bellow commands. It does not report error. Please double check.

```
"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x64_arm64 uwp 10.0.22621.0 -vcvars_ver=14.35
cl -nologo -Ilibrary/ -Iinclude/ -Fobuild\library\ -c ./library\aesce.c
```

2023-03-21 08:51 UTC, yuhaoth commented on library/aesce.h
> +
I can reproduce it now. I forget rebase this PR. :(

2023-03-21 09:01 UTC, yuhaoth commented on library/aesce.h
> +
fixed.

2023-03-21 09:19 UTC, yuhaoth commented
I just rebased this PR due to gcm compile fail.

2023-03-21 09:26 UTC, yuhaoth commented
I have tried some msvc versions from vs2022 with bellow command
```
"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x64_arm64 uwp 10.0.22621.0 -vcvars_ver=%1

cl -Ilibrary/ -Iinclude/ -c ./library\aesce.c
```
The versions are `14.16.27023 14.29.30133 14.30.30705 14.31.31103 14.32.31326 14.33.31629 14.34.3193314.35.32215`

`14.16.27023` reports ARM64 not support from `arm_neon.h` . Others passed above test.

2023-03-22 03:13 UTC, yuhaoth commented on library/aesce.h
> +
That might be a bug of GCC also.  

GCC think `poly64_t` and `poly64x1_t` are different. So `cast` is a MUST for GCC. But I think they are same

2023-03-22 05:41 UTC, yuhaoth commented
ARMCC reports license server error. Others pass

2023-03-27 06:52 UTC, yuhaoth commented
Rebase to re-trigger CI

2023-03-29 05:13 UTC, yuhaoth commented
It is replaced with #7286

2023-03-29 07:36 UTC, tom-cosgrove-arm commented
Actually, could we not do that? i.e. let's not have one PR (7286) that does a bunch of completely different things.

There should be one PR to replace the Perl scripts with Python, and another to add MSVC support for AESCE

2023-03-29 08:43 UTC, yuhaoth commented
> Actually, could we not do that? i.e. let's not have one PR (7286) that does a bunch of completely different things.
> 
> There should be one PR to replace the Perl scripts with Python, and another to add MSVC support for AESCE

Agree. I do not think it more.

2023-03-29 09:09 UTC, yuhaoth commented
> There should be one PR to replace the Perl scripts with Python, and another to add MSVC support for AESCE

I only left AESCE part here.

2023-03-29 09:16 UTC, yuhaoth commented
Rebased to resolve conflicts

2023-03-29 10:03 UTC, yuhaoth commented
Should I remove perl relative commit from this PR?

2023-03-29 15:55 UTC, tom-cosgrove-arm commented
> Should I remove perl relative commit from this PR?

I think the normal way in Mbed TLS is to have the commits from the preceding PR in the following one, although in my view that makes review (in the GitHub interface) harder. The alternative is to target the branch of the preceding PR in the following PR, which makes it easier to review in GitHub, but means you then need to update the PR when the preceding one is merged.

And in both cases, the following PR should have the `needs-preceding-pr` label

2023-03-30 05:57 UTC, yuhaoth commented
I just re-write the history. 

MSVC project relative commit is removed from this PR. 

And I create [a temp PR](#7356) to verify it with MSVC .

2023-04-04 02:27 UTC, yuhaoth commented
Rebase to re-trigger CI

2023-04-08 14:43 UTC, gilles-peskine-arm commented
> I think the normal way in Mbed TLS is to have the commits from the preceding PR in the following one, although in my view that makes review (in the GitHub interface) harder. The alternative is to target the branch of the preceding PR in the following PR, which makes it easier to review in GitHub, but means you then need to update the PR when the preceding one is merged.

Targeting the branch of the preceding PR is indeed nicer for reviewing in advance. But it's more work to keep it fully up-to-date when the preceding PR evolves, which I think is why part we often don't do it. Another reason we don't do it is that it somewhat messes up the pr-merge CI job — the API/ABI check isn't meaningful. But we have done it sometimes, so it's not an established rule that you have to target the final branch from the start.

2023-04-08 14:44 UTC, gilles-peskine-arm commented
> AFAICT platformtoolsetversion=v141 means VS 2017. We support VS 2013 - so if this doesn't work on VS 2017, it needs to detect the compiler version and only enable for recent versions of VS.

I'd expect arm support to have improved during the 2010s, so it would be reasonable to require a more recent version of VS for arm-specific features.

2023-04-11 09:46 UTC, yuhaoth commented
> I'd expect arm support to have improved during the 2010s, so it would be reasonable to require a more recent version of VS for arm-specific features.

I prefer VS 2022. That is first native version for Arm64

2023-04-11 11:25 UTC, tom-cosgrove-arm commented
> I prefer VS 2022. That is first native version for Arm64

I don't think we should go that recent, and it's still common for people to cross-compile

2023-04-24 14:22 UTC, daverodgman requested changes

2023-04-24 14:22 UTC, daverodgman commented on library/aesce.h
>  #if defined(MBEDTLS_HAVE_ASM) && defined(__GNUC__) && \
This conflicts with the change to check_config - if you try to build without `MBEDTLS_HAVE_ASM`, check_config won't complain but you will not get the AESCE implementation.

I guess we should remove the check for HAVE_ASM here (although technically we do still have the asm optimisation barrier for gcc)

2023-04-24 14:22 UTC, daverodgman commented on library/aesce.h
> +#if defined(_M_ARM64) || defined(_M_ARM64EC)
Need to check MSVC version here I think

2023-04-24 14:26 UTC, daverodgman commented
> > I prefer VS 2022. That is first native version for Arm64
> 
> I don't think we should go that recent, and it's still common for people to cross-compile

IIUC we have established that 2017 doesn't work, and 2022 does. If someone is able to test on some in-between versions and confirm a working version, we can use that, but if not, it's probably OK to go with 2022 for now.

2023-04-24 14:27 UTC, daverodgman commented
We should document in `mbedtls_config.h` which compilers (and versions) are supported for `MBEDTLS_AESCE_C`.

2023-04-25 08:20 UTC, daverodgman commented on include/mbedtls/mbedtls_config.h
> + *          Studio 2019 version 16.11.2"(`_MSC_VER >= 1929`)
```suggestion
 * \note    The minimum version of MSVC for building this module is Visual
 *          Studio 2019 version 16.11.2.
```

2023-04-25 08:24 UTC, daverodgman commented
Do we want to add a #error if the user tries to build for Arm with MBEDTLS_AESCE_C enabled on an old MSVC? As it stands, I think it will silently not build AESCE_C, so if plain C is still enabled, the user will unexpectedly not get AESCE.

2023-04-26 02:29 UTC, yuhaoth commented on library/aesce.h
> +#if defined(_MSC_VER) && _MSC_VER >=1929 && \
I agree with [your comment](https://github.com/Mbed-TLS/mbedtls/pull/7316#issuecomment-1521380967). 
I will revert the changes in this paragraph. And raise compiler check error when `MBEDTLS_HAVE_ARM64` enabled.

2023-04-26 08:29 UTC, daverodgman commented
Looks good but the gcc check triggers when building with clang

2023-04-26 08:32 UTC, daverodgman commented on library/aesce.c
> +#elif defined(__GNUC__) && (__GNUC__ < 6)
```suggestion
#elif defined(__GNUC__) && (__GNUC__ < 6) && !defined(__clang__)
```

2023-04-26 08:33 UTC, daverodgman commented
I think the recommended way to detect gcc but not clang is `defined(__GNUC__) && !defined(__clang__)` - see https://github.com/abseil/abseil.github.io/blob/master/docs/cpp/platforms/macros.md

2023-04-26 08:37 UTC, tom-cosgrove-arm commented
> I think the recommended way to detect gcc but not clang is `defined(__GNUC__) && !defined(__clang__)` - see https://github.com/abseil/abseil.github.io/blob/master/docs/cpp/platforms/macros.md

That's what we normally do - but putting `#if defined(__clang__)` and `#elif defined(__GNUC__)` gives the same result

2023-04-26 08:42 UTC, daverodgman commented
> > I think the recommended way to detect gcc but not clang is `defined(__GNUC__) && !defined(__clang__)` - see https://github.com/abseil/abseil.github.io/blob/master/docs/cpp/platforms/macros.md
> 
> That's what we normally do - but putting `#if defined(__clang__)` and `#elif defined(__GNUC__)` gives the same result

It would, but the first if condition also has a version check, so we do need the suggested fix.

2023-04-26 08:56 UTC, yuhaoth commented on library/aesce.c
> +#elif defined(__GNUC__) && (__GNUC__ < 6)
fix with @tom-cosgrove-arm 's suggestion.

2023-04-26 10:14 UTC, tom-cosgrove-arm approved these changes
LGTM

2023-04-26 20:27 UTC, merged