ecp: Unify test cases
Mbed-TLS/mbedtls pull request #7329
Opened 2023-03-22 14:32 UTC by minosgalanakis

## Description

Resolves #7306 .

This patch replaces the test functions for the following curves:

 MBEDTLS_ECP_DP_SECP192R1
    * MBEDTLS_ECP_DP_SECP224R1
    * MBEDTLS_ECP_DP_BP256R1
    * MBEDTLS_ECP_DP_BP512R1
    * MBEDTLS_ECP_DP_BP384R1

Instead of invoking a functionally similar curve specific method, 
`ecp_mod_pXXX_generic_raw(char *input_N, char *input_X, char *result)` ,
                          
the new generic implementation is accepting a curve_id, 
`
ecp_mod_p_generic_raw(int curve_id, char *input_N, char *input_X, char *result)` 

which is defined in the [ecp interface](https://github.com/Mbed-TLS/mbedtls/blob/development/include/mbedtls/ecp.h#L66-L76).

Then the curve specific parameters are switch-gated, greatly simplifying the test code.

## Gatekeeper checklist

- [x] **changelog** Not required since that is a new interface, and are not changing behaviour or logs.
- [x] **backport** Not required since that is a new interface not ported to 2.28
- [x] **tests** Provided

2023-03-22 14:34 UTC, minosgalanakis commented
Please only review [this commit](https://github.com/Mbed-TLS/mbedtls/pull/7329/commits/6b83341b027500bcd1ab81d2a11b18cac9d7609b), since the pr is based on top of [PR7222](https://github.com/Mbed-TLS/mbedtls/pull/7222)

2023-03-27 16:00 UTC, gabor-mezei-arm submitted a review, later dismissed
LGTM

2023-03-29 10:46 UTC, minosgalanakis commented
I have added an extra [commit ](https://github.com/Mbed-TLS/mbedtls/pull/7329/commits/5ce38d326c3a819589a39393366d4266b75f5162)to avoid a regression of the issues fixed by #7103 and #7343.

2023-04-03 10:39 UTC, gabor-mezei-arm requested changes

2023-04-06 15:39 UTC, minosgalanakis commented
@gabor-mezei-arm I agree that was not straightforward. I have updated the code during the rebase for the conflict resolution, and now dependenices can be optionally declared as class members. 

`arch_split` will still append the architectural dependency when set.

2023-04-06 15:56 UTC, gabor-mezei-arm approved these changes
LGTM

2023-04-11 12:06 UTC, yanesca requested changes
I have a minor suggestion for improvement and left a question in the comments.

2023-04-12 08:45 UTC, minosgalanakis commented on tests/suites/test_suite_ecp.function
> +/* BEGIN_CASE depends_on:MBEDTLS_TEST_HOOKS:MBEDTLS_ECP_DP_SECP_GENERIC_ENABLED */
As a matter of fact we don't. Good catch. Will be removed.

2023-04-12 12:23 UTC, merged