Clarify LTS lifetime
Mbed-TLS/mbedtls pull request #7383
Opened 2023-03-30 14:04 UTC by yanesca

## Description

Users can get more value out of our LTS releases and plan transition between versions better if the documentation is more clear about the lifetime of LTS branches.

## Gatekeeper checklist

- [ x ] **changelog** not required
- [ ] **backport** will be provided after approval
- [ x ] **tests** not required

2023-03-30 15:02 UTC, davidhorstmann-arm approved these changes
LGTM

2023-04-02 18:42 UTC, daverodgman requested changes
It's not a given that an LTS will be supported for 3 years; I've suggested some more precise wording.

2023-04-02 18:42 UTC, daverodgman commented on BRANCHES.md
> +After a new LTS branch is created, it remains supported for at least 3 years.
```suggestion
When a new LTS branch is created, it usually remains supported for three years.
```

2023-04-04 08:04 UTC, daverodgman submitted a review, later dismissed

2023-04-11 07:33 UTC, gilles-peskine-arm requested changes

2023-04-11 10:41 UTC, davidhorstmann-arm approved these changes
LGTM, thanks!

2023-04-11 11:21 UTC, gilles-peskine-arm approved these changes
LGTM

2023-04-17 17:18 UTC, merged