Improve tests for parsing x509 SubjectKeyId and AuthorityKeyId
Mbed-TLS/mbedtls pull request #7411
Opened 2023-04-06 09:15 UTC by mprse

## Description

Resolves: https://github.com/Mbed-TLS/mbedtls/issues/6985

This PR is build on top of: PR https://github.com/Mbed-TLS/mbedtls/pull/6866. First commit of this PR: d2507ff5d1ae3e8b05e0b8345e8497d0d78d33ed.

Provides make file generated certificates for tests and improves test by checking values of tested cert fields (not length only).

## Gatekeeper checklist

- [ ] **changelog** provided, or not required
- [ ] **backport** done, or not required
- [ ] **tests** provided, or not required

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

2023-05-08 14:27 UTC, mprse commented
Coverage report below:

![image](https://user-images.githubusercontent.com/30721012/236850088-183f1c8b-3afc-48d7-bc7c-642e39fc7a46.png)

![image](https://user-images.githubusercontent.com/30721012/236850387-a805557b-77cc-442b-9269-b6bae88a2ed2.png)

2023-05-09 06:42 UTC, mprse commented
@DemiMarie @AndrzejKurek This one is ready for review.

2023-05-09 15:02 UTC, DemiMarie commented on tests/suites/test_suite_x509parse.data
> +x509_crt_parse_authoritykeyid:"data_files/authorityKeyId_subjectKeyId_sn_len_malformed.crt.der":"":"":"":MBEDTLS_ERR_X509_INVALID_EXTENSIONS+MBEDTLS_ERR_ASN1_LENGTH_MISMATCH
```suggestion
x509_crt_parse_authoritykeyid:"data_files/authorityKeyId_subjectKeyId_sn_len_malformed.crt.der":"":"":"":MBEDTLS_ERR_X509_INVALID_EXTENSIONS+MBEDTLS_ERR_ASN1_LENGTH_MISMATCH
```

Nit: missing newline at EOF

2023-05-12 09:21 UTC, AndrzejKurek commented on tests/suites/test_suite_x509parse.function
> +        if (crt.authority_key_id.authorityCertIssuer.buf.len > 0)
Use a authorityKeyId_issuer check instead in case if the test does not parse it properly.

2023-05-12 09:24 UTC, AndrzejKurek commented
Also, the CI is unhappy so I'm applying the "needs:ci" label too.

2023-05-16 12:31 UTC, mprse commented on tests/suites/test_suite_x509parse.function
> +        if (crt.authority_key_id.keyIdentifier.len > 0)
If parsing of `keyIdentifier` fails then we will have an error case. But I agree that using expected values for this check is better.

2023-05-16 12:40 UTC, mprse commented on tests/suites/test_suite_x509parse.data
>  X509 CRT parse Authority Key Id - Wrong Issuer Tag 2
Wrong DirectoryName tag in issuer field ?

2023-05-16 14:10 UTC, AndrzejKurek commented on tests/suites/test_suite_x509parse.function
> +        if (crt.authority_key_id.keyIdentifier.len > 0)
What I meant is - if there's no field to parse, then there's no error, so we won't it up.

2023-05-16 14:11 UTC, AndrzejKurek commented on tests/suites/test_suite_x509parse.data
>  X509 CRT parse Authority Key Id - Wrong Issuer Tag 2
Yes :)

2023-05-18 14:54 UTC, AndrzejKurek commented on tests/data_files/Makefile
> +	$(OPENSSL) req -x509 -nodes -days 7300 -key server2.key -outform DER -out $@ -config authorityKeyId_subjectKeyId.conf -extensions 'v3_req_authorityKeyId_empty'
This is not an empty AuthorityKeyIdentifier, it's missing, as in the case above.

2023-05-18 14:54 UTC, AndrzejKurek commented on tests/data_files/authorityKeyId_subjectKeyId.conf
> +subjectKeyIdentifier = hash
This is not an empty AuthorityKeyIdentifier, it's missing, as in the case above.

2023-05-25 09:56 UTC, AndrzejKurek submitted a review, later dismissed

2023-06-07 07:05 UTC, mprse commented
Rebased to resolve conflicts (`makefile`).

2023-06-07 12:56 UTC, AndrzejKurek submitted a review, later dismissed

2023-06-13 17:11 UTC, davidhorstmann-arm requested changes
One issue after regenerating the certificates, one cosmetic non-blocker.

Looks good otherwise!

2023-06-13 17:11 UTC, davidhorstmann-arm commented on tests/suites/test_suite_x509parse.function
>              }
Not a blocker for this PR, but I'd prefer using standard functions for comparison of directory names.

I think we can either:
* Use `mbedtls_x509_string_to_names()` to convert the test string to a DN, then use `x509_name_cmp()` to compare to the name in the cert. This requires exporting `x509_name_cmp()` publicly.
* Use `mbedtls_x509_dn_gets()` to convert the name in the cert to a string and `strcmp()` with the test name.

But I'd be happy for this change to be in a followup PR.

2023-06-14 12:26 UTC, mprse commented on tests/data_files/Makefile
> +	$(OPENSSL) req -x509 -nodes -days 7300 -key server2.key -outform DER -out $@ -config authorityKeyId_subjectKeyId.conf -extensions 'v3_req'
Fixed as suggested.

2023-06-14 13:01 UTC, davidhorstmann-arm approved these changes
LGTM, thanks!

2023-06-14 13:41 UTC, AndrzejKurek approved these changes

2023-06-14 17:16 UTC, merged