sha256.c: improvements in code size
Mbed-TLS/mbedtls pull request #7414
Opened 2023-04-07 08:15 UTC by yanrayw

## Description

Fix: #7373 

## Gatekeeper checklist

- [ ] **changelog** required
- [ ] **backport** not required
- [ ] **tests** required

2023-04-11 15:24 UTC, tom-daubney-arm commented
Hey @yanrayw, can I please ask what mbedtls configuration you are building with and what compile options you are using to get the numbers that you quoted in the PR description?

2023-04-12 07:27 UTC, yanrayw commented
> Hey @yanrayw, can I please ask what mbedtls configuration you are building with and what compile options you are using to get the numbers that you quoted in the PR description?

Hi Tom, it's default configurations in MbedTLS (no any modifications) with `gcc 8.4.0` on x86. The code is built based on 03d557d.

2023-04-12 07:45 UTC, tom-daubney-arm commented
> > Hey @yanrayw, can I please ask what mbedtls configuration you are building with and what compile options you are using to get the numbers that you quoted in the PR description?
> 
> Hi Tom, it's default configurations in MbedTLS (no any modifications) with `gcc 8.4.0` on x86. The code is built based on [03d557d](https://github.com/Mbed-TLS/mbedtls/commit/03d557db3572a4dc1b8b2ccaa5af45d511039511).

Thanks, and do you also have any extra CFLAGS etc that you are passing to make?

2023-04-12 07:51 UTC, yanrayw commented
> do you also have any extra CFLAGS etc that you are passing to make?

No I don't. It's just simple `make CC=gcc lib`. I'm not very sure this PR really helps in code size. As it does something different than issue requirement. https://github.com/Mbed-TLS/mbedtls/issues/7373#issuecomment-1499912026

2023-04-13 03:30 UTC, yanrayw commented
> I can see that removing a `memcpy` and replacing it with the `sha256_put_uint32_be` function has the potentail to save some code size however it is possible that compiler optimisations already reduce the impact of using a `memcpy`.

Agree with this. Initially I used gcc and found there are some code size improvements on `x86_64` but no difference (in assembly code) on `aarch64`. Yesterday I realized we should measure code size by `ARMCC 6.19` on ARMv8.  I went with a simple test by running `ARMC6_BIN_DIR=/usr/local/ArmCompilerforEmbedded6.19/bin ./tests/scripts/all.sh build_armcc`, however the code size is even increased. I think probably there isn't much we can do by simply replacing `MBEDTLS_PUT_UINT32_BE` as code size has been improved by #6666 . Once we have a firm conclusion, I think we can close this PR and the corresponding issue.

2023-04-13 07:54 UTC, tom-daubney-arm commented
@yanrayw You are probably right there but I would like @tom-cosgrove-arm to weigh in on this before we close it off :)

2023-04-13 13:55 UTC, tom-daubney-arm requested changes
I have reviewed the code in this PR in full. I think the idea in principle is good but it is possible that the compiler optimisation for `memcpy` is already very good.

Following on from the discussion in the comments I can now say that this PR unfortunately increases the code size of the library. Using the code size comparison script that has been modified in #7426 I get the following out resulting from adding the code in this PR into the library:
| Old Size | New Size | Change (Bytes) | Change (%) |
| ---: |  ---: |  ---: | ---: |
| 79384 | 79346 | 38 | 0.05% |

So we have an overall increase of 38 bytes which equates to 0.05%.

I have marked this PR as "Request changes" but as @yanrayw has already mentioned it could be that the PR ends up being closed.

2023-04-14 04:17 UTC, yanrayw commented
> So we have an overall increase of 38 bytes which equates to 0.05%.

Thanks a lot @tom-daubney-arm . I used modified `code_size_compare.py` with `tfm-medium` config and got same results. The code size is even increased by 38 bytes.

| File Name | Old Size | New Size | Change (Bytes) | Change (%) |
| ---: | ---: |  ---: |  ---: | ---: |
| sha256.o | 1392 | 1354 | 38 | 2.81% |

I believe compiler has optimized `memcpy` so we can't save more code size in this area regarding #7373. AFAIU, we could close this PR and #7373 . Does this make sense to both of you? @tom-daubney-arm @tom-cosgrove-arm

2023-04-14 13:53 UTC, tom-daubney-arm commented
> Does this make sense to both of you? @tom-daubney-arm @tom-cosgrove-arm

Yep I agree with all of that

2023-04-17 12:51 UTC, yanesca commented
@yanrayw according to our new process PRs with 'high-priority' label should go on the unified board. Could you please add this PR to the board?

2023-04-18 01:49 UTC, yanrayw commented
> 

Thanks for letting me know @yanesca . It's added.

2023-04-18 01:50 UTC, closed without merging