ECP: Add Unit Tests for secp224k1
Mbed-TLS/mbedtls pull request #7425
Opened 2023-04-11 15:50 UTC by minosgalanakis

## Description

Resolves #7257 

## Gatekeeper checklist

- [ ] **changelog**not required
- [ ] **backport** not required
- [ ] **tests** provided

2023-04-14 14:14 UTC, gabor-mezei-arm requested changes
The changes for the P192K1 testing is not part of this PR and must be removed.

2023-04-14 14:14 UTC, gabor-mezei-arm commented on tests/suites/test_suite_ecp.function
> +    mbedtls_mpi_mod_raw_fix_quasi_reduction(X.p, &m);
As the description of this issue recommend  the `mbedtls_mpi_mod_mpi()` should be used here.

2023-04-17 08:33 UTC, yanesca commented
@minosgalanakis this is a deliverable for this quarter, it should have a `priority-high` label, could you please add it?

2023-04-18 10:47 UTC, minosgalanakis commented
I have rebased and addressed the comment. The code is still based on #7424 since it makes resolving conflicts easier and we can test the code as we expect it to come in.

Please only review the [last three commits](https://github.com/Mbed-TLS/mbedtls/pull/7425/files/cec506083b3dbddd52bdf6d22d5b18c4277f5aae..56ca0e3c50ab498eacb9a2c79d1897a5268a8778)

When the pr for `p192k1` is merged, I will rebase it

2023-04-21 10:17 UTC, paul-elliott-arm approved these changes
LGTM

2023-04-21 10:18 UTC, merged