ECP: Add Unit Tests for secp256k1
Mbed-TLS/mbedtls pull request #7427
Opened 2023-04-11 17:20 UTC by minosgalanakis

## Description
Resolves #7258

## Gatekeeper checklist

- [x] **changelog** not required. Extending testing coverage, does not affect library's behaviour
- [x] **backport** not required. This is worked required by a newly developped interface
- [x] **tests** provided,.

2023-04-17 08:33 UTC, yanesca commented
@minosgalanakis this is a deliverable for this quarter, it should have a `priority-high` label, could you please add it?

2023-04-18 13:19 UTC, minosgalanakis commented
As before it is based on PR #7425 . Please review only [last 3 commits](https://github.com/Mbed-TLS/mbedtls/pull/7427/files/357b9e1342f32f507d82c097beeeb656a117c23a..f2568cad2347d530eb8180def0083f337d131da0) if need to. 

It will rebased after #7425 has been merged.

2023-04-21 10:55 UTC, minosgalanakis commented
PR Rebased on latest development. Ready to review

2023-04-21 11:11 UTC, paul-elliott-arm requested changes
1 thing jumped out. Everything else looks ok, but need to do a slightly deeper pass.

2023-04-21 11:11 UTC, paul-elliott-arm commented on library/ecp_curves.c
> +int ecp_mod_p256k1(mbedtls_mpi *);
Shouldn't this be:

```suggestion
int mbedtls_ecp_mod_p256k1(mbedtls_mpi *);
```

2023-04-25 10:19 UTC, gabor-mezei-arm approved these changes
Only a minor non-blocking issue found otherwise looks good to me.

2023-04-25 10:19 UTC, gabor-mezei-arm commented on scripts/mbedtls_dev/ecp.py
> +
Before class definition there should be two empty line.

2023-04-26 07:52 UTC, merged