Document qemu bug affecting the mbedtls_x509_crt_parse_path test
Mbed-TLS/mbedtls pull request #7441
Opened 2023-04-13 16:22 UTC by gilles-peskine-arm

Document a [known issue](https://gitlab.com/qemu-project/qemu/-/issues/263) when running tests under Qemu (which we intend to do on the CI [one of these days](https://github.com/Mbed-TLS/mbedtls/issues/3855)).

## Gatekeeper checklist

- [x] **changelog** N/A
- [ ] **backport** TODO
- [x] **tests** N/A

2023-04-18 16:36 UTC, tom-cosgrove-arm commented on tests/suites/test_suite_x509parse.data
> +# The parse_path tests are known to fail when compiled for a 32-btt architecture
```suggestion
# The parse_path tests are known to fail when compiled for a 32-bit architecture
```

2023-04-19 07:14 UTC, tom-cosgrove-arm submitted a review, later dismissed
LGTM

2023-04-21 15:41 UTC, daverodgman requested changes

2023-04-21 15:41 UTC, daverodgman commented on tests/suites/test_suite_x509parse.data
> +depends_ondepends_on:MBEDTLS_MD_CAN_SHA1:MBEDTLS_RSA_C:MBEDTLS_MD_CAN_SHA256:MBEDTLS_PK_CAN_ECDSA_SOME:MBEDTLS_ECP_DP_SECP384R1_ENABLED
Typo?

2023-04-24 11:43 UTC, daverodgman approved these changes

2023-05-03 12:51 UTC, gilles-peskine-arm commented
I forced-pushed because there was a merge conflict. In "Improve testing of mbedtls_x509_crt_parse_file", reconcile the change to the function that tests `mbedtls_x509_crt_parse_file`: addition of `USE_PSA_INIT/USE_PSA_DONE` in development, additional testing and moved to be grouped with `mbedtls_x509_crt_parse_path` in the PR.

2023-07-07 14:08 UTC, tom-cosgrove-arm commented on tests/suites/test_suite_x509parse.data
> +# The parse_path tests are known to fail when compiled for a 32-btt architecture
@daverodgman if you're fixing the conflicts, can you take this suggestion please?

2023-07-07 14:09 UTC, tom-cosgrove-arm commented on tests/suites/test_suite_x509parse.data
> +# The parse_path tests are known to fail when compiled for a 32-btt architecture
err, n/m, already done

2023-07-07 14:12 UTC, daverodgman commented
Discussed in historical review - conflicts are trivial so agreed to resolve the merge & dust off the review

2023-07-07 14:20 UTC, daverodgman approved these changes
LGTM

2023-07-07 14:45 UTC, tom-cosgrove-arm approved these changes
LGTM

2023-07-07 18:15 UTC, daverodgman commented
OpenCI failure is spurious

2023-07-07 18:15 UTC, merged