Backport: Clean up & improve PK write test functions
Mbed-TLS/mbedtls pull request #7456
Opened 2023-04-18 15:02 UTC by valeriosetti

This is the backport of issue #7446 as solved in PR #7449.

## Gatekeeper checklist

- [ ] **changelog** not required
- [ ] **backport** not required: this is the backport
- [ ] **tests** not required

2023-04-19 07:36 UTC, mpg approved these changes
LGTM

2023-04-19 07:41 UTC, mpg commented
Note for the future: as a reviewer, I like it when backports have the same commit structure as the original PR, because then I can use `git range-diff` to check it's just the same changes. (Also, as a backport author, that's easily achieved by using `git cherry-pick development..original_branch`.) (Here I manually made a diff of diffs, but I don't know how to make it as readable as the output from git range-diff.)

2023-04-20 19:24 UTC, AndrzejKurek approved these changes

2023-04-20 19:25 UTC, AndrzejKurek commented on tests/data_files/Makefile
> +#### Convert PEM keys in DER format
```suggestion
#### Convert PEM keys to DER format
```
Same suggestion as in the original PR.

2023-04-24 08:43 UTC, mpg requested changes
This needs updating to match changes in the original PR.

2023-04-24 09:21 UTC, mpg approved these changes
LGTM, thanks!

2023-04-24 09:40 UTC, AndrzejKurek approved these changes
Faithful backport.

2023-04-24 11:05 UTC, merged