[Bignum] Bignum/test read write named modulu
Mbed-TLS/mbedtls pull request #7629
Opened 2023-05-22 10:11 UTC by xkqian

## Description

Prepare a function to test the utility functions of read(), write() for named modulu.
Prepare a function to test the random data generate by mbedtls_mpi_mod_random().

Preceding PR: #7582 

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog**  not required
- [x] **backport**  not required
- [x] **tests** not required

2023-05-25 15:35 UTC, minosgalanakis requested changes
Looks ok, minor changes requested

2023-05-30 13:16 UTC, minosgalanakis commented on tests/suites/test_suite_ecp.function
> +                                        MBEDTLS_MPI_MOD_EXT_REP_BE));
Nitpicking, so I wont block the review. Now with bytes, they can both fit in one line:

~~~~~~
    TEST_EQUAL(0, mbedtls_mpi_mod_write(&rA, &m, (unsigned char *) bufx,
                                        bytes, MBEDTLS_MPI_MOD_EXT_REP_BE));
~~~~~~

2023-05-30 13:20 UTC, minosgalanakis submitted a review, later dismissed
Looks good

2023-05-30 17:20 UTC, gabor-mezei-arm approved these changes
Looks good to me

2023-05-31 12:24 UTC, gabor-mezei-arm approved these changes
LGTM

2023-05-31 12:53 UTC, minosgalanakis approved these changes

2023-06-01 08:11 UTC, merged