Add a do-while loop around macros.
Mbed-TLS/mbedtls pull request #7686
Opened 2023-06-05 17:42 UTC by DemiMarie

## Description

Add do-while loops around various macros.

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** not required - no functional changes
- [x] **backport** in #7721
- [x] **tests** not required - no functional changes

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

2023-06-07 03:17 UTC, bensze01 approved these changes
Looks good to me. Please rebase on top of development to fix the CI issues (See #7699), and backport to 2.28.

2023-06-07 12:49 UTC, gilles-peskine-arm commented
Thank you for your contributions. I don't have time to review everything, and I'm afraid I can't commit to review all of your pull requests. In general, please don't request review from specific people except by prior agreement.

2023-06-07 19:52 UTC, DemiMarie commented
> Thank you for your contributions.

You’re welcome!

> I don't have time to review everything, and I'm afraid I can't commit to review all of your pull requests.

That’s not a problem.

> In general, please don't request review from specific people except by prior agreement.

Sorry about that.  Is there a way to disable the GitHub feature that suggests people to request review from?

2023-06-19 17:59 UTC, bensze01 requested changes

2023-06-19 17:59 UTC, bensze01 commented on library/x509.c
> +            PRINT_ITEM(name);                           \
The new code style mandates brackets around one-line `if`` statements. This should allow the `check_code_style`  unit-test to pass.
```suggestion
        if (ns_cert_type & (type)) {                    \
            PRINT_ITEM(name);                           \
        }                                               \
```

2023-06-19 17:59 UTC, bensze01 commented on library/x509.c
> +            PRINT_ITEM(name);      \
Ditto.
```suggestion
        if ((key_usage) & (code))  { \
            PRINT_ITEM(name);        \
        }                            \
```

2023-06-20 15:53 UTC, bensze01 approved these changes
LGTM

2023-06-21 09:30 UTC, bensze01 commented
The readthedocs build completed successfully, but failed to update its status on github, for some reason.

2023-06-21 09:31 UTC, merged