PBKDF2: Out of range input cost
Mbed-TLS/mbedtls pull request #7702
Opened 2023-06-06 11:45 UTC by silabs-Kusumit

## Description

Add test function and case for testing correct behavior when input cost is greater than `PSA_VENDOR_PBKDF2_MAX_ITERATIONS`.

## PR checklist

- [ ] **changelog**  not required
- [ ] **backport** not required
- [ ] **tests** provided

2023-06-07 17:41 UTC, gilles-peskine-arm requested changes
Looks good to me for the original scope, but I just realized we're missing a test case where the cost is too low (PKCS#5 says the cost must be >0) so please add that.

2023-06-07 17:41 UTC, gilles-peskine-arm commented on tests/suites/test_suite_psa_crypto.data
> +
Please add a test case with cost=0, I just realized we're missing that.

2023-06-28 13:53 UTC, gilles-peskine-arm commented
There's a known issue with the GitHub reporting from OpenCI at the moment. https://ci.trustedfirmware.org/blue/organizations/jenkins/mbed-tls-pr-head/detail/PR-7702-head/2/pipeline/ passed on cbfe333c2b78b422ccd85269e02d5083ebd81eee.

2023-06-28 13:56 UTC, gilles-peskine-arm approved these changes
LGTM

2023-07-03 08:57 UTC, daverodgman approved these changes

2023-07-03 08:58 UTC, merged