Use DER format for x509 SAN tests
Mbed-TLS/mbedtls pull request #7802
Opened 2023-06-20 10:17 UTC by AndrzejKurek

This way there's no dependency on PEM parsing.

## PR checklist
- [x] **changelog** not required, internal test change
- [x] **backport** not required - not a bugfix, just an improvement
- [x] **tests** - updated existing ones

2023-06-21 17:11 UTC, davidhorstmann-arm requested changes
When I regenerated the certs the tests failed, but I guess this is due to the hard-coded expiry dates and so is not easy to fix?

I guess it affects all tests that use `strcmp()` against a string with a date and so would require major work so I'm happy to not fix that in this PR.

2023-06-21 17:22 UTC, gilles-peskine-arm commented on tests/data_files/parse_input/server5-othername.crt.der
The idea of the `parse_input` directory is that we never re-generate files in there. The certificates might expire, but we don't care, because the files are for parser tests and parsers don't care about the current time.

2023-06-22 07:33 UTC, AndrzejKurek commented on tests/data_files/parse_input/server5-othername.crt.der
I partially agree with @gilles-peskine-arm - we never re-generate files in there due to expiry. We still might want to re-generate them due to other reasons, changes to x509 parsing, test changes, etc. That's why it would be nice to have these recipes working, as I mentioned [here](https://github.com/Mbed-TLS/mbedtls/pull/7617#discussion_r1234985637).
I have filed an issue [here](https://github.com/Mbed-TLS/mbedtls/issues/7816).

2023-06-22 08:27 UTC, davidhorstmann-arm approved these changes
LGTM with issue raised to solve the Makefile recipe incoherence.

2023-06-28 09:40 UTC, AndrzejKurek commented
This will have a conflict if https://github.com/Mbed-TLS/mbedtls/pull/7853 gets merged first.

2023-06-29 13:00 UTC, mprse approved these changes
LGTM

2023-06-30 07:36 UTC, merged