tests/test_suite_ecp: Fix ECP group compare test
Mbed-TLS/mbedtls pull request #7907
Opened 2023-07-11 07:07 UTC by gowthamsk-arm

## Description

ECP group compare function should not check the value of T. We only need to assert the value of T after the ECP group copy function is called.

Relates to #6707.

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [ ] **changelog**: Not needed as this is a test data
- [ ] **backport**: This applies only to mbedtls-2.28
- [ ] **tests**: Provided

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

2023-07-11 07:45 UTC, mpg submitted a review, later dismissed
LGTM, thanks!

2023-07-11 09:30 UTC, tgonzalezorlandoarm submitted a review, later dismissed
LGTM :)

2023-07-11 15:27 UTC, gilles-peskine-arm requested changes
Sorry, this still doesn't look right.

2023-07-12 10:54 UTC, gowthamsk-arm commented on tests/suites/test_suite_ecp.function
>      if (grp1->T_size != grp2->T_size) {
Yes, it does. I missed T_size here. Will update it and add a comment. :)

2023-07-12 14:52 UTC, tgonzalezorlandoarm approved these changes
LGTM

2023-07-13 10:43 UTC, gilles-peskine-arm commented
The task requires both a PR to development and a PR to 2.28, but they're going to be very different, so there's no reason to wait until development is ready, we can merge the 2.28 PR independently.

2023-07-13 10:43 UTC, merged