Enable DH in generate_psa_tests.py
Mbed-TLS/mbedtls pull request #7909
Opened 2023-07-11 08:31 UTC by mpg

## Description

Resolves #7812: add support for DH keys to `generate_psa_tests.py`.

## PR checklist

- [x] **changelog** not required - tests only
- [x] **backport** not required - we only have that feature in development
- [x] **tests** provided - that's what the PR is about :)

2023-07-11 09:09 UTC, AndrzejKurek commented on tests/scripts/generate_psa_tests.py
> +            if key_type in self.DH_KEY_TYPES:
Minor: this could be done in one line with the previous if.

2023-07-11 09:09 UTC, AndrzejKurek submitted a review, later dismissed
Looks good comparing to the way `ECC_KEY_TYPES` are handled.

2023-07-11 16:51 UTC, gilles-peskine-arm requested changes
A couple of minor issues. Also I haven't ensured that `test_suite_psa_crypto_not_supported.generated.data` looks right because of https://github.com/Mbed-TLS/mbedtls/issues/7915.

2023-07-11 16:51 UTC, gilles-peskine-arm commented on scripts/mbedtls_dev/crypto_knowledge.py
Minor: please tweak line to `short_expression` to abbreviate `DH_FAMILY` like `ECC_FAMILY`.

2023-07-11 16:51 UTC, gilles-peskine-arm commented on tests/scripts/generate_psa_tests.py
The dependency for DH key pairs is `PSA_WANT_KEY_TYPE_DH_KEY_PAIR`, so the tests are not executed. This needs to change to the new suffixes, like is already the case for ECC.

2023-07-18 10:04 UTC, mpg commented
Just pushed a new version that I think fixes #7915. It won't pass CI yet as `make test` doesn't pass in the default config: `PSA key_agreement FFDH: incompatible with DH_KEY_PAIR(RFC7919)` from `test_suite_psa_crypto_op_fail.generated` is failing and I need to look into this, but I wanted to push the current state in order to share the fix for #7915.

2023-07-18 10:33 UTC, gilles-peskine-arm commented
> PSA key_agreement FFDH: incompatible with DH_KEY_PAIR(RFC7919) from test_suite_psa_crypto_op_fail.generated is failing

That means in `crypto_knowledge.py`, in `KeyType`, `can_do` isn't doing its job. And indeed it's missing a case for FFDH.

2023-07-26 07:28 UTC, gilles-peskine-arm reviewed
43257747731861e40fc171070a504d61bc6409c0 looks good to me, but now `generate_psa_tests.py` no longer needs the `MBEDTLS_GENPRIME` insertion hack.

2023-07-26 07:42 UTC, mpg commented
Indeed, it became unnecessary 15h ago when #7902 was merged. I've rebased to fix the conflict and remove the last commit.

2023-07-26 12:58 UTC, gilles-peskine-arm approved these changes
Looks good to me, except for wrong dependencies in `test_suite_psa_crypto_not_supported.generated.data` which is a pre-existing issue that will be resolved with https://github.com/Mbed-TLS/mbedtls/issues/7915.

2023-07-26 13:12 UTC, mpg commented
Well, I did try to resolve #7915 with this PR (as noted in the PR description), specifically [this commit](https://github.com/Mbed-TLS/mbedtls/pull/7909/commits/c154a043bb299847ec6c36b32517f0d99b032a1a) (whose message is out-of-date after rebasing btw). What did I miss?

2023-07-26 13:26 UTC, gilles-peskine-arm commented
> Well, I did try to resolve #7915 with this PR (as noted in the PR description), specifically this commit (whose message is out-of-date after rebasing btw). What did I miss?

Oops, I missed that. Well, #7915 is not resolved, but I think the current state is good to merge anyway as long as we don't close the issue.

Observation:
```
# Take config-suite-b.h plus PSA (which is executed by test-ref-configs.pl on the CI)
mbedtls-prepare-build -p debug -d build-psa-suite-b --config-file=configs/config-suite-b.h --config-set=MBEDTLS_PSA_CRYPTO_C,MBEDTLS_USE_PSA_CRYPTO
make -C build-psa-suite-b tests/test_suite_psa_crypto_not_supported.generated.run
```

Comparing the output on development and this PR:
```
diff ../../f1c032adba124fecbb43ff52d3e08f7157ae69e1.txt ../../182eb1514e49a1dc1eafffd83ab7abf03e3c6591.txt
1c1
< make: Entering directory '/home/gilpes01/z/dev/mbedtls/main/build-psa-suite-b'
---
> make: Entering directory '/home/gilpes01/z/dev/mbedtls/reviewing/7909-dh-generate-psa-tests/build-psa-suite-b'
224a225,254
> PSA import DH_KEY_PAIR(RFC7919) 2048-bit type not supported ....... ----
> PSA generate DH_KEY_PAIR(RFC7919) 2048-bit type not supported ..... ----
> PSA import DH_KEY_PAIR(RFC7919) 3072-bit type not supported ....... ----
> PSA generate DH_KEY_PAIR(RFC7919) 3072-bit type not supported ..... ----
> PSA import DH_KEY_PAIR(RFC7919) 4096-bit type not supported ....... ----
> PSA generate DH_KEY_PAIR(RFC7919) 4096-bit type not supported ..... ----
> PSA import DH_KEY_PAIR(RFC7919) 6144-bit type not supported ....... ----
> PSA generate DH_KEY_PAIR(RFC7919) 6144-bit type not supported ..... ----
> PSA import DH_KEY_PAIR(RFC7919) 8192-bit type not supported ....... ----
> PSA generate DH_KEY_PAIR(RFC7919) 8192-bit type not supported ..... ----
> PSA import DH_KEY_PAIR(RFC7919) 2048-bit group not supported ...... ----
> PSA generate DH_KEY_PAIR(RFC7919) 2048-bit group not supported .... ----
> PSA import DH_KEY_PAIR(RFC7919) 3072-bit group not supported ...... ----
> PSA generate DH_KEY_PAIR(RFC7919) 3072-bit group not supported .... ----
> PSA import DH_KEY_PAIR(RFC7919) 4096-bit group not supported ...... ----
> PSA generate DH_KEY_PAIR(RFC7919) 4096-bit group not supported .... ----
> PSA import DH_KEY_PAIR(RFC7919) 6144-bit group not supported ...... ----
> PSA generate DH_KEY_PAIR(RFC7919) 6144-bit group not supported .... ----
> PSA import DH_KEY_PAIR(RFC7919) 8192-bit group not supported ...... ----
> PSA generate DH_KEY_PAIR(RFC7919) 8192-bit group not supported .... ----
> PSA import DH_PUBLIC_KEY(RFC7919) 2048-bit type not supported ..... ----
> PSA import DH_PUBLIC_KEY(RFC7919) 3072-bit type not supported ..... ----
> PSA import DH_PUBLIC_KEY(RFC7919) 4096-bit type not supported ..... ----
> PSA import DH_PUBLIC_KEY(RFC7919) 6144-bit type not supported ..... ----
> PSA import DH_PUBLIC_KEY(RFC7919) 8192-bit type not supported ..... ----
> PSA import DH_PUBLIC_KEY(RFC7919) 2048-bit group not supported .... ----
> PSA import DH_PUBLIC_KEY(RFC7919) 3072-bit group not supported .... ----
> PSA import DH_PUBLIC_KEY(RFC7919) 4096-bit group not supported .... ----
> PSA import DH_PUBLIC_KEY(RFC7919) 6144-bit group not supported .... ----
> PSA import DH_PUBLIC_KEY(RFC7919) 8192-bit group not supported .... ----
228,229c258,259
< PASSED (222 / 222 tests (169 skipped))
< make: Leaving directory '/home/gilpes01/z/dev/mbedtls/main/build-psa-suite-b'
---
> PASSED (252 / 252 tests (199 skipped))
> make: Leaving directory '/home/gilpes01/z/dev/mbedtls/reviewing/7909-dh-generate-psa-tests/build-psa-suite-b'
```

Resolving 7915 would mean that the DH tests pass here, and also the ECC test cases for curves that are not supported in development pass here. But they're still skipped.

2023-07-26 17:37 UTC, tom-daubney-arm approved these changes
LGTM, thanks.

2023-07-26 17:45 UTC, gilles-peskine-arm commented
I've removed the statement about #7915 from the issue description since I approved thinking that this would resolve #7815 but not #7915.

2023-07-26 21:32 UTC, merged