Miscellaneous changes to scripts for PSA-Crypto enablement
Mbed-TLS/mbedtls pull request #7955
Opened 2023-07-18 17:13 UTC by davidhorstmann-arm

Enable the scripts to be used either in Mbed TLS or in the PSA Cryptography repository.

Specifically:
* Change root directory detection logic in several places
* Change filepaths in several places dependent on which repo we are in

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** not required - internal script changes only
- [x] **backport** not required - The PSA Crypto repo is based on development only
- [x] **tests** not required - changes are only to scripts

2023-07-19 11:58 UTC, daverodgman commented
Test comment

2023-07-20 07:03 UTC, ronald-cron-arm requested changes
This looks overall good to me, things to improve in test_psa_compliance.py though.

2023-08-23 15:26 UTC, davidhorstmann-arm commented on tests/scripts/test_psa_compliance.py
> +    if not is_psa_crypto:
Done by omission as this line no longer exists.

2023-08-28 09:32 UTC, ronald-cron-arm requested changes

2023-08-29 08:46 UTC, davidhorstmann-arm commented on tests/scripts/test_psa_compliance.py
> +    parser.add_argument('--build-dir', nargs=1,
It does work, as the script builds Mbed TLS from scratch via CMake in `./mbedtls_out_of_source_build` before it runs the tests.

I can change the default build dir to something that is likely to be aligned with the user's chosen build dir like `build` if necessary.

2023-08-29 12:34 UTC, ronald-cron-arm requested changes
This looks almost good to me. Otherwise mypy is not happy it seems and the CI is failing.

2023-08-29 12:34 UTC, ronald-cron-arm commented on tests/scripts/test_psa_compliance.py
> +        subprocess.check_call(['cmake', '--build', library_build_dir])
```suggestion
        subprocess.check_call(['cmake', '--build', library_build_dir, '-t psacrypto/mbedcrypto'])
```
to build only the crypto library, not the other targets.

2023-08-31 06:32 UTC, ronald-cron-arm approved these changes
This looks good to me, thanks.

2023-08-31 18:19 UTC, paul-elliott-arm approved these changes
LGTM

2023-08-31 20:05 UTC, merged