Driver guide/examples: fix an error and improve discoverability
Mbed-TLS/mbedtls pull request #8040
Opened 2023-08-07 09:40 UTC by mpg

## Description

Make the document that describes the current reality of driver development more discoverable, and fix an error in it.

## PR checklist

- [x] **changelog** not required - documentation only
- [x] **backport** not required - that document is not in 2.28
- [x] **tests** not required - documentation only

2023-08-07 14:50 UTC, gilles-peskine-arm requested changes
I think one of the lines was added to the wrong file

2023-08-07 14:50 UTC, gilles-peskine-arm commented on docs/proposed/psa-driver-wrappers-codegen-migration-guide.md
> +For a description of the current state of drivers Mbed TLS, see our [PSA Cryptoprocessor driver development examples](../psa-driver-example-and-guide.html).
This document describes the generator script as it is now, so the line about a work in progress is not correct. When the generator script is completed, this document should no longer be needed: the integration guide should suffice.

2023-08-07 14:50 UTC, gilles-peskine-arm commented on docs/proposed/psa-driver-integration-guide.md
> +For a description of the current state of drivers Mbed TLS, see our [PSA Cryptoprocessor driver development examples](../psa-driver-example-and-guide.html).
We should add this line to `psa-driver-interface.md` as well.

2023-08-08 08:14 UTC, gilles-peskine-arm approved these changes
LGTM

2023-08-09 10:26 UTC, merged

2023-10-31 12:30 UTC, davidhorstmann-arm commented
Did the links to the driver example guide ever work?

We've just had them reported as broken in #8453 and I think perhaps they should point to `.md` not `.html`.

2023-10-31 16:25 UTC, gilles-peskine-arm commented
The links to `.html` files work if you build the HTML collection locally. They don't work if you browse the `.md` files on GitHub.