pkwrite: use heap to save stack usage for writing keys in PEM string
Mbed-TLS/mbedtls pull request #8062
Opened 2023-08-11 08:37 UTC by yanrayw

## Description

Similar to #7991 , in `mbedtls_pk_write_pubkey_pem` and `mbedtls_pk_write_key_pem`, we would allocate `2086` and `5679` respectively for a RSA public/private key. We can use heap to save stack usage a lot.

Saves of stack usage (measured by 0882828 with `default config` on `x86_64`):
| Function | Old Size | New Size | Change (Bytes) |
| :--- | ---: |  ---: |  ---: |
| mbedtls_pk_write_pubkey_pem | 2176 | 96 | -2080 |
| mbedtls_pk_write_key_pem | 5808 | 128 | -5680 |

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** provided
- [x] **backport** https://github.com/Mbed-TLS/mbedtls/pull/8162
- [x] **tests** not required

2023-08-21 07:03 UTC, lpy4105 requested changes
Issue on the API used for memory allocation.

2023-08-22 01:55 UTC, lpy4105 commented on library/pkwrite.c
> +    mbedtls_free(output_buf);
Do we need to zeroize `output_buf` since it contains the private key?

2023-08-28 03:07 UTC, lpy4105 approved these changes
LGTM

2023-10-09 14:57 UTC, Ryan-Everett-arm approved these changes
LGTM

2023-10-13 17:15 UTC, merged