Implement allowlist of test cases that are legitimately not executed
Mbed-TLS/mbedtls pull request #8074
Opened 2023-08-14 14:59 UTC by tgonzalezorlandoarm

## Description

Resolves #5389

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [ ] **changelog** not provided
- [ ] **backport**will be done after the PR is approved.
- [ ] **tests** not provided, this modifies the parsing of tests.

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

2023-08-14 15:07 UTC, tgonzalezorlandoarm commented
The rest of the allowed tests will be added in https://github.com/Mbed-TLS/mbedtls/issues/5390

2023-08-22 08:34 UTC, gilles-peskine-arm requested changes
Looks mostly good to me

2023-08-22 08:55 UTC, tgonzalezorlandoarm commented on tests/scripts/analyze_outcomes.py
> +                'pure EdDSA',
Done

2023-08-23 10:41 UTC, tgonzalezorlandoarm commented
I think this can be re-reviewed as all comments are addressed and all checks are passing. Adding @waleed-elmelegy-arm as a reviewer, having previously discussed this

2023-08-23 14:45 UTC, waleed-elmelegy-arm approved these changes
LGTM

2023-08-23 15:13 UTC, gilles-peskine-arm approved these changes
LGTM

2023-08-23 18:20 UTC, gilles-peskine-arm requested changes
The indentation is off on one line. I'm surprised pylint didn't complain.

2023-08-23 18:20 UTC, gilles-peskine-arm commented on tests/scripts/analyze_outcomes.py
> +        }
```suggestion
    }
```

2023-08-24 08:13 UTC, tgonzalezorlandoarm commented on tests/scripts/analyze_outcomes.py
> +        }
Done

2023-08-24 08:20 UTC, gilles-peskine-arm approved these changes
LGTM

2023-08-24 11:02 UTC, waleed-elmelegy-arm approved these changes
LGTM

2023-08-24 20:34 UTC, merged