Backport 2.28: parts of #7961
Mbed-TLS/mbedtls pull request #8103
Opened 2023-08-22 15:55 UTC by gilles-peskine-arm

This is a partial backport of #7961. I have not added `MBEDTLS_PSA_CRYPTO_CONFIG` to the full config because I don't think it's worth doing a major overhaul of the tested configurations in 2.28 at this point. I also didn't add a `u` suffix to size constants because it's potentially disruptive. I backported the other changes that were applicable.

Detailed backport log:

* "Remove duplicated component": N/A
* "Remove comments that duplicate the 'msg' call just below": yes, slightly different set of affected components
* "Fix typo in function name": N/A
* "Fix inconsistencies in no-chachapoly test": yes
* "Make malloc-0-null a user config file": yes
* "Enable MBEDTLS_PSA_CRYPTO_CONFIG in "config.py full"": no
* "When subtracting classic symbols from full, turn off PSA_CRYPTO_CONFIG": no
* "Simplify msg messages in full config": no
* "Correct some msg messages in full config": modified
* "Make sure that size constants are unsigned": no (may be disruptive)
* "Fix PBKDF2 with empty salt on platforms where malloc(0)=NULL": N/A
* "Fix some dependencies on symmetric crypto in some TLS 1.3 tests": N/A
* "Simplify the logic in a test": yes
* "Don't call psa_crypto_init with uninitialized local contexts (entropy)": N/A
* "PSA_CRYPTO_DRIVER_TEST_ALL is incompatible with MBEDTLS_PSA_CRYPTO_CONFIG": yes, but no need to explicitly disable MBEDTLS_PSA_CRYPTO_CONFIG in 2.28
* "More unsigned literal in size macros": no (see "Make sure that size constants are unsigned")
* "Minor readability improvement": N/A
* "Fix copypasta": N/A
* "Merge remote-tracking branch 'development' into psa_crypto_config-in-full": N/A
* "Fix PBKDF2 with empty salt segment on platforms where malloc(0)=NULL": N/A

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** not required
- [x] **backport** of #7961
- [x] **tests** N?A

2023-08-23 15:50 UTC, davidhorstmann-arm requested changes

2023-08-23 16:23 UTC, gilles-peskine-arm commented on tests/scripts/all.sh
>      scripts/config.py set MBEDTLS_PSA_CRYPTO_BUILTIN_KEYS
Indeed. I've amended the last commit accordingly.

2023-09-18 10:49 UTC, merged

2023-09-18 10:55 UTC, olopierpa commented
:)

On Mon, Sep 18, 2023 at 10:13 AM Gilles Peskine ***@***.***>
wrote:

> #8103 <https://github.com/Mbed-TLS/mbedtls/pull/8103> was added to the merge
> queue <https://github.com/Mbed-TLS/mbedtls/queue/mbedtls-2.28>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Mbed-TLS/mbedtls/pull/8103#event-10394693905>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA2MTYIOVMDTHZLP3BWLDPDX277CJANCNFSM6AAAAAA32EQG7Q>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-09-18 10:58 UTC, olopierpa commented
On Mon, Sep 18, 2023 at 12:55 PM Pierpaolo Bernardi ***@***.***>
wrote:

> :)
>

Please excuse my mistake. I was replying to a different email and for
mysterious reasons the reply went here.


Message ID: ***@***.***>
>>
>