Remove GNUTLS_LEGACY and OPENSSL_LEGACY
Mbed-TLS/mbedtls pull request #8121
Opened 2023-08-27 20:04 UTC by gilles-peskine-arm

We don't need the `GNUTLS_LEGACY` and `OPENSSL_LEGACY` versions in Mbed TLS 3.x: the “main” versions work too.

## PR checklist

- [x] **changelog** no (test scripts only)
- [x] **backport** 
- [ ] **tests** CI run + run `basic-build-test.sh` (TODO)

2023-08-30 14:02 UTC, tgonzalezorlandoarm requested changes

2023-08-30 15:06 UTC, tgonzalezorlandoarm approved these changes
LGTM

2023-09-28 13:33 UTC, waleed-elmelegy-arm approved these changes
LGTM
(just think it's worth mentioning in the ticket description the preserve-logs option changes because it's unrelated to the title of the ticket so it's clear in the history)

2023-09-28 13:46 UTC, gilles-peskine-arm commented
> (just think it's worth mentioning in the ticket description the preserve-logs option changes because it's unrelated to the title of the ticket so it's clear in the history)

This is mentioned in the git log. I don't think it's useful to mention this kind of little improvements (as opposed to bug fixes) in the issue description. If later we care when this was implemented, we'll look at `git log`, not GitHub.

2023-10-18 09:46 UTC, merged