Make PEM use cipher.c when available
Mbed-TLS/mbedtls pull request #8125
Opened 2023-08-28 12:57 UTC by valeriosetti

Resolves #8051

## PR checklist

- [ ] **changelog** since `CIPHER_C` is auto-enabled when `PEM_PARSE_C` is enabled, do we need to track this change anyway?
- [ ] **backport** not required
- [ ] **tests** provided: a couple of new tests were added

2023-09-04 15:41 UTC, gabor-mezei-arm requested changes

2023-09-04 15:41 UTC, gabor-mezei-arm commented on library/pem.c
> +    }
The content of the `key` variable must be erased from the memory with `mbedtls_platform_zeroize()`.

2023-09-04 15:41 UTC, gabor-mezei-arm commented on library/pem.c
> +    unsigned char key[32];
I prefer to use the `MBEDTLS_MAX_KEY_LENGTH` instead.

2023-09-05 09:14 UTC, gabor-mezei-arm approved these changes
Looks good to me

2023-10-02 12:31 UTC, valeriosetti commented
I just rebased this PR in order to solve conflicts with `development`

2023-10-12 09:01 UTC, mpg commented
On hold: https://github.com/Mbed-TLS/mbedtls/issues/8051#issuecomment-1759215720

2023-11-29 11:44 UTC, mpg commented
Closing as we're not going to address PEM with driver-only ciphers before 4.0, and after 4.0 the strategy will be different (and much simpler).

2023-11-29 11:44 UTC, closed without merging