Backport 2.28: check_test_cases.py: support to collect test cases for compat.sh
Mbed-TLS/mbedtls pull request #8128
Opened 2023-08-30 04:16 UTC by yanrayw

## Description

Backport of #7165 

## Comments

This PR adds support to list all potential test cases in `compat.sh` by `./tests/compat.sh --list-test-case`. Therefore, `check_test_cases.py` is able to collect those test case description in order to report duplicated test cases.

To analyze outcome by `analyze_outcomes.py`, the test case description should be identical with `OUTCOME.CSV` in #7136 . Please consider those two PRs together. 

## Gatekeeper checklist

- [x] **changelog** not required
- [x] **backport** of https://github.com/Mbed-TLS/mbedtls/pull/7165
- [x] **tests** not required

2023-08-30 09:23 UTC, tgonzalezorlandoarm commented on tests/scripts/check_test_cases.py
> +        for idx, descrip in enumerate(description):
Just a minor comment:
idx here does not mean the line number, so this is technically incorrect.

2023-08-30 09:23 UTC, tgonzalezorlandoarm commented on tests/scripts/check_test_cases.py
> +            self.process_test_case(descriptions, file_name, idx, descrip)
Just a minor comment:
idx here does not mean the line number here.

2023-08-30 09:35 UTC, tgonzalezorlandoarm requested changes

2023-08-30 09:35 UTC, tgonzalezorlandoarm commented on tests/compat.sh
> +                add_common_ciphersuites
Why do you do this in every iteration while in #7165 you do it only for for TYPE in $TYPES; do?

2023-08-30 10:05 UTC, tgonzalezorlandoarm commented on tests/compat.sh
> +                add_common_ciphersuites
Okay I understand, thanks for the clarification

2023-08-30 10:36 UTC, tgonzalezorlandoarm approved these changes

2023-08-31 03:10 UTC, lpy4105 approved these changes
LGTM

2023-08-31 09:55 UTC, merged