Make CTR-DRBG use cipher.c when available
Mbed-TLS/mbedtls pull request #8134
Opened 2023-08-30 16:48 UTC by valeriosetti

Resolves #8054

## PR checklist

- [ ] **changelog** not required
- [ ] **backport** not required
- [ ] **tests** not required

2023-08-31 07:08 UTC, valeriosetti commented
The CI only failed in `ABI-API checking` and this is due to the replacement of `aes_ctx` with the new `cipher_ctx` in the `struct mbedtls_ctr_drbg_context` when `CIPHER_C` is defined. Both of these fields are `MBEDTLS_PRIVATE` so no end user is supposed to have direct access to them. At the same time this change is necessary to complete [the original task](https://github.com/Mbed-TLS/mbedtls/issues/8054) so I would say this error is not relevant.
Question to reviewers: wdyt?

2023-08-31 07:13 UTC, gilles-peskine-arm commented
Adding and removing `MBEDTLS_PRIVATE` fields is always ok in the development branch. Unfortunately those false positives of the ABI/API checker are not trivial to fix.

2023-09-01 12:51 UTC, valeriosetti commented
> Adding and removing MBEDTLS_PRIVATE fields is always ok in the development branch. Unfortunately those false positives of the ABI/API checker are not trivial to fix.

@gilles-peskine-arm wouldn't this create problems with the merge queue? If so, do you have any suggestion on how to overcome this problem?

2023-09-01 13:20 UTC, gilles-peskine-arm commented
Only the checks marked “Required” are taken into account for the merge queue. The interface stability tests aren't.

2023-10-02 13:37 UTC, gabor-mezei-arm submitted a review, later dismissed
LGTM

2023-10-10 08:22 UTC, mpg requested changes
This is absolutely going in the right direction, but the issue with errors from `setup()` needs addressing.

2023-10-10 08:22 UTC, mpg commented on library/ctr_drbg.c
> +    ret = mbedtls_cipher_setup(&cipher_ctx,
I think we're supposed to call `init()` before setup. (And also before the first point that might jump to the label where `free()` is called.)

2023-10-10 10:06 UTC, gilles-peskine-arm requested changes
I question why we're doing this at all. It seems like a step in the wrong direction.

* We have no request to extend CTR_DRBG to other algorithms.
* In Mbed TLS 3.6, we're trying to bypass cipher — see https://github.com/Mbed-TLS/mbedtls/pull/8057. So using cipher more seems counterproductive.
* In Mbed TLS 4.0, we'd like to get rid of cipher. So using cipher more seems counterproductive.

In Mbed TLS 3.6, we may have a goal of making CTR_DRBG work on top of a PSA AES accelerator. It's not yet clear that this is in the scope of 3.6, however. And using cipher.h functions does not seem like a particularly useful way to reach this goal.

2023-10-10 10:53 UTC, mpg commented
@gilles-peskine-arm https://github.com/Mbed-TLS/mbedtls/issues/8054#issuecomment-1755027790

2023-10-11 09:27 UTC, mpg commented
See https://github.com/Mbed-TLS/mbedtls/issues/8337 regarding clarification of the plan.

But also, there might just be an misunderstanding elsewhere: this PR is only a stepping stone towards #8060 - it's just a way to allow starting the work while #8057 is not completed yet. So the plan is not to introduce more dependencies on `CIPHER_C` (this PR does not add a dependency), just to prepare the move to Cipher-light, taking advantage of the fact it's a subset of Cipher.

2023-10-12 08:57 UTC, mpg commented
Ok, following discussion in #8337 there's likely to be a change of plan for CTR-DRBG. Let's put this on hold until we're sure. (I think there's now an agreement between Gilles and I, but I'd like to wait a few more days before jumping to the new plan in order to leave for the consensus to solidify.)

2023-10-30 09:54 UTC, closed without merging