Fix error handling in psa_driver_wrapper_xxx_hash_get_num_ops
Mbed-TLS/mbedtls pull request #8271
Opened 2023-09-28 17:09 UTC by daverodgman

## Description

Fix broken error handling in psa_driver_wrapper_xxx_hash_get_num_ops

Does this count as an API break?

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** not required
- [x] **backport** not in 2.28
- [x] **tests** covered by existing

2023-09-28 17:13 UTC, paul-elliott-arm commented on scripts/data_files/driver_templates/psa_crypto_driver_wrappers.h.jinja
> +static inline int psa_driver_wrapper_sign_hash_get_num_ops(
I think this should probably be psa_status_t

2023-09-28 17:14 UTC, paul-elliott-arm commented on scripts/data_files/driver_templates/psa_crypto_driver_wrappers.h.jinja
> +static inline int psa_driver_wrapper_verify_hash_get_num_ops(
likewise psa_status_t

2023-09-28 17:18 UTC, paul-elliott-arm approved these changes
LGTM

2023-09-28 17:33 UTC, paul-elliott-arm submitted a review, later dismissed

2023-09-28 17:33 UTC, paul-elliott-arm commented on library/psa_crypto.c
> +    if (status == PSA_SUCCESS) {
status could potentially be PSA_OPERATION_INCOMPLETE here as well as success. We should likely do this call regardless of status at this point, but only overwrite status if psa_driver_wrapper_verify_hash_get_num_ops() fails.

2023-09-28 17:33 UTC, paul-elliott-arm commented on library/psa_crypto.c
> +    if (status == PSA_SUCCESS) {
See below, we should call `psa_driver_wrapper_sign_hash_get_num_ops()` anyway and only overwrite status on failure.

2023-09-28 17:45 UTC, gilles-peskine-arm requested changes
I don't understand why we should make this interface change.

`get_num_ops` is a data accessor. We currently have it as a simple function that returns the value and cannot fail. I'm not sure if it's the best design, but it's not obviously broken.

The current code is broken — `psa_driver_wrapper_sign_hash_get_num_ops` (etc.) returns `PSA_ERROR_INVALID_ARGUMENT` in a context that expects an ops count. But that can only happen if there has been data corruption and `operation->id` is not a valid value. Since we don't assert, we can just treat this can't-happen as a can't-happen and continue on (returning 0).

2023-09-28 17:50 UTC, daverodgman commented
> But that can only happen if there has been data corruption and `operation->id` is not a valid value. Since we don't assert, we can just treat this can't-happen as a can't-happen and continue

A hardware accelerated implementation might be capable of failing? Obviously if we are confident that failure isn't possible for any driver, then we can remove returning a status from these functions and go back to the old interface.

2023-09-28 18:15 UTC, gilles-peskine-arm commented
> A hardware accelerated implementation might be capable of failing?

Sure, but it would fail during an operation function. `num_ops` is data which the driver is supposed to keep updated. If we were ok with using transparent structures (which we avoid in order to maintain an abstraction barrier), we'd pass the driver the address of the operation structure and instruct it to update the `num_ops` field.

2023-09-28 18:34 UTC, daverodgman commented
OK, if we're agreed that there is no issue with not being able to return an error code, then let's go for the simple fix.

2023-09-28 18:47 UTC, paul-elliott-arm approved these changes
LGTM

2023-09-29 07:40 UTC, gilles-peskine-arm approved these changes

2023-09-29 13:07 UTC, merged