mbedtls_ecp_read_key(): don't check priv key when no curves enabled
Mbed-TLS/mbedtls pull request #8362
Opened 2023-10-13 15:53 UTC by tom-cosgrove-arm

## Description

When built without `MBEDTLS_ECP_MONTGOMERY_ENABLED` and `MBEDTLS_ECP_SHORT_WEIERSTRASS_ENABLED`, `mbedtls_ecp_read_key()` would previously return `MBEDTLS_ERR_ECP_FEATURE_UNAVAILABLE`, but now it calls `mbedtls_ecp_check_privkey()` on an uninitialised private key.

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [ ] **changelog** provided, or not required
- [ ] **backport** done, or not required
- [ ] **tests** provided, or not required

2023-10-16 09:52 UTC, tom-cosgrove-arm commented
I was running static analysis first with gcc13's `-fanalyzer` and then with an older version of clang's `scan-build` and it came up with

```
ecp.c:3237:5: warning: Value stored to 'ret' is never read
    ret = MBEDTLS_ERR_ECP_FEATURE_UNAVAILABLE;
    ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Looking at the code, it seemed a reasonable way of doing things, but then my concern was if neither `MBEDTLS_ECP_MONTGOMERY_ENABLED` nor `MBEDTLS_ECP_SHORT_WEIERSTRASS_ENABLED` were set.

You're right that this is under `ECP_LIGHT` rather than `ECP_C`, so is still theoretically possible with a mis-configured library

2023-10-16 10:36 UTC, mpg commented
Ah, so that fact that it's static analysis answers my 2nd question ("What part of the code ends up calling `ecp_read_key()` despite `ecp_group_load()` returning an error?" ). I'm still curious what configuration of the library you were using and how you arrived at a config that has `ECP_LIGHT` enabled but no built-in curve: depending on the answer, we might have a problem, which could range from "`check_config.h` is not strict enough", to "something that a reasonable user might want to do is not supported".

2023-10-16 10:44 UTC, tom-cosgrove-arm commented
> I'm still curious what configuration of the library you were using

I was using the default configuration.

The static analysis raised a question around this area of the code, the specific issue was by inspection. I wasn't aware that (a) it shouldn't be possible to configure without one of `MBEDTLS_ECP_MONTGOMERY_ENABLED` and `MBEDTLS_ECP_SHORT_WEIERSTRASS_ENABLED`, and (b) it actually is possible to configure without either.

Given this would be action at a distance, with the `ECP_LIGHT` issue fixed, an equally reasonable "fix" here would be a comment such as

```
/* We can't configure without at least one of MBEDTLS_ECP_MONTGOMERY_ENABLED
 * and `MBEDTLS_ECP_SHORT_WEIERSTRASS_ENABLED, so key->d will have been set */
```

2023-10-16 11:07 UTC, gilles-peskine-arm requested changes
This change is counterproductive.

I don't think this code needs changing at all. But if we do, we should add something like `#else return NOT_IMPLEMENTED;`.

2023-10-16 11:07 UTC, gilles-peskine-arm commented on library/ecp.c
> +#endif
Functionally, this doesn't change anything. The only supported curves are Montgomery curves and short Weierstrass curves. If the preprocessor condition is false, `mbedtls_ecp_group_load` above can't have succeeded.

If we add a new curve family (e.g. twisted Edwards), we'll have to add a case for it in this function and many others.

If we somehow add support for a new curve family to `mbedtls_ecp_group_load` but not here, then this function won't set `key→d`. Note that this is not an uninitialized variable: this function assumes that `key` is already initialized with `mbedtls_ecp_keypair_init`. If `key` is freshly initialized, then `key→d` has the value 0 (represented with length 0), and `mbedtls_ecp_check_privkey` will either succeed or fail depending on whether `{0, {}}` is considered a valid private key object. If `key` had been in use before, then `key→d` still has its old value and may or may not pass `mbedtls_ecp_check_privkey`.

I don't see any advantage with this change. In the unlikely chance that we forget this function when we add support for a new curve family, we're replacing a call that has a good chance of returning an error with nothing.

2023-10-17 08:39 UTC, mpg commented
I've created https://github.com/Mbed-TLS/mbedtls/pull/8376 which (1) adjusts the check in `check_config.h`, and (2) makes a minor code change to fix the original static analyzer warning.

> I don't think this code needs changing at all. But if we do, we should add something like `#else return NOT_IMPLEMENTED;`.

We can't really use `#else` here, we already have `ret == NOT_IMPLEMENTED` at this point if we somehow skipped the two blocks, so I took advantage of that. (I also checked for other occurrences and couldn't find any: most of the time we immediately return after the last `#endif`, and had set `ret` to `NOT_IMPLEMENTED` before the first `#if` so everything's fine already.)

2023-10-17 08:51 UTC, closed without merging