Fix #8372 - Error compiling AESNI in Mbed-TLS with clang on Windows
Mbed-TLS/mbedtls pull request #8373
Opened 2023-10-16 20:02 UTC by sergio-nsk

It can successfully compile w/ or w/o the clang options `-maes -mpclmul`.

## Description

Fixes #8372. Does not conflict with #8339.

The macro `__GNUC__` is not defined by Clang on Windows, thus use the macro `__clang__` for `-maes -mpclmul`.

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** not required
- [x] **backport** not required
- [x] **tests** not required

2023-10-17 10:03 UTC, lpy4105 requested changes
Minor code style issue.
Have you checked this work on `2.28` branch?

2023-10-17 16:11 UTC, sergio-nsk commented on library/aesni.c
> +    __m128i aa = {0}, bb = {0}, cc, dd;
Fixed. BTW clang thought the variables were not initialized and raised errors with `-Werror`.

2023-10-17 16:17 UTC, sergio-nsk commented
> Minor code style issue. Have you checked this work on `2.28` branch?

Yes, of course. I use the LTS, hence I fixed the compiling issue here and then in `developement`. It's now compiled well with MSVC, clang and clang -maes -mpclmul. The latter is not required in 2.28 like in `devlopement` https://github.com/Mbed-TLS/mbedtls/blob/development/library/aesni.h#L67-L72.

2023-10-18 03:15 UTC, lpy4105 approved these changes
LGTM

2023-10-18 10:24 UTC, tom-cosgrove-arm approved these changes
LGTM

2023-10-19 10:22 UTC, tom-cosgrove-arm approved these changes
LGTM

2023-10-19 14:47 UTC, lpy4105 approved these changes
LGTM

2023-10-25 23:38 UTC, sergio-nsk commented
I don't know why my PR is kicked out the merge queue. How can I investigate it?

2023-10-26 01:50 UTC, lpy4105 commented
Merge queue failure seems to be spurious, need to resubmit.

2023-10-26 08:18 UTC, gilles-peskine-arm commented
Weird infrastructure failure on the merge queue:
```
Channel "unknown": Remote call on container-host.eu-west-1b (i-007507a020fad60fb) failed. The channel is closing down or has closed down
```

This is a new error to me, but it seems to happen often since a day or two ago. Same error in https://github.com/Mbed-TLS/mbedtls/pull/8374.

2023-10-26 18:48 UTC, merged