Fix error handling for secure element keys in `psa_start_key_creation`
Mbed-TLS/mbedtls pull request #8538
Opened 2023-11-15 16:42 UTC by Ryan-Everett-arm

## Description
Add some error handling for the call to `psa_copy_key_material_into_slot` in `psa_start_key_creation`. Fixes #8537
## PR checklist
- [x] **changelog** provided
- [ ] **backport** in progress
- [x] **tests** not required, we cannot test out of memory issues

2023-11-16 15:14 UTC, gilles-peskine-arm requested changes
LGTM for the fix but not for the changelog entry.

2023-11-16 15:14 UTC, gilles-peskine-arm commented on ChangeLog.d/fix-secure-element-key-creation.txt
> +     out of memory issues are properly handled. Fixes #8537.
* The changelog entry should mention the fact that this is only a problem when a non-default option is enabled. 
* `psa_start_key_creation` is an internal function, so it is not meaningful in a changelog entry. Changelog entries are meant for library users.

Suggested wording:

> Fix error handling when creating a key in a dynamic secure element (feature enabled by MBEDTLS_PSA_CRYPTO_SE_C). In a low memory condition, the creation could return PSA_SUCCESS but using or destroying the key would not work. Fixes #8537.

2023-11-16 16:55 UTC, gilles-peskine-arm approved these changes
LGTM

2024-04-25 11:41 UTC, tom-daubney-arm approved these changes
LGTM - thanks

2024-05-02 19:11 UTC, merged