Modify changelog assembly to work with tf-psa-crypto
Mbed-TLS/mbedtls pull request #8550
Opened 2023-11-21 16:24 UTC by gabor-mezei-arm

## Description

This PR is part of Mbed-TLS/TF-PSA-Crypto#47.

Add support to  create an initial changelog entry if no entries found and specify the name of the project from the previous entries.

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** not required, only internal change
- [x] **backport** not required, new feature
- [x] **tests** not required, already exists

2023-11-21 18:10 UTC, gilles-peskine-arm requested changes
The changes are correct, but I think some of them add complexity without providing functionality.

2023-11-22 14:22 UTC, gabor-mezei-arm commented on scripts/assemble_changelog.py
> +            top_version_body = ''
You are right I will add an initial entry for the changelog and remove the support from the script.

2023-11-24 18:34 UTC, tom-daubney-arm reviewed
This looks good but I have a question.

I ran this on both Mbed TLS and TF-PSA-Crypto and it largely worked on both. I am just wondering about the version text that gets produced when running on TF-PSA-Crypto. For my local test I copied over the relevant files (ChangeLog, assemble_changelog.py, 00README.md and a .txt file to add in to the ChangeLog) and ran the script.

The file gets added to ChangeLog as expected so that all works but the line that shows what version of Mbed TLS we are on renders as `= Mbed TLS x.x.x branch released xxxx-xx-xx`, rather than showing the actual numbers and date.

I appreciate this is only part of the fix for the main issue but is this output expected at this point?

2023-11-29 13:27 UTC, gabor-mezei-arm commented
> I appreciate this is only part of the fix for the main issue but is this output expected at this point?

AFAIK, the script is not setting the date and the version it needs to be changed manually.

2023-11-29 16:16 UTC, tom-daubney-arm approved these changes
LGTM - thanks.

2023-11-29 17:46 UTC, gilles-peskine-arm commented on scripts/assemble_changelog.py
> +            offset = (self.header + self.top_version_title).count('\n') + 1
I still don't understand this.

2023-12-06 10:02 UTC, gilles-peskine-arm approved these changes
LGTM

The script doesn't exactly work in an empty file. This is pre-existing, though. The following content doesn't work:

```
TF-PSA-Crypto ChangeLog

= TF-PSA-Crypto 0.0.1 branch released xxxx-xx-xx
```

But it works if you manually add a valid category header.

2023-12-06 13:56 UTC, tom-daubney-arm approved these changes

2023-12-06 21:18 UTC, merged