TLS1.3: SRV: check `min_tls_version` when parsing ClientHello
Mbed-TLS/mbedtls pull request #8595
Opened 2023-12-04 07:59 UTC by yanrayw

## Description

Fix: #8593

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** provided
- [x] **backport** not required (tls1.3 only)
- [x] **tests** provided

2023-12-05 03:23 UTC, yuhaoth submitted a review, later dismissed
LGTM

2023-12-06 02:20 UTC, yuhaoth submitted a review, later dismissed
LGTM

2023-12-07 17:01 UTC, ronald-cron-arm requested changes
Thanks for taking care of this. I have a few change suggestions.

2023-12-08 14:08 UTC, ronald-cron-arm requested changes
One nitpick otherwise this looks good to me.

2024-01-11 13:33 UTC, ronald-cron-arm approved these changes
I will address https://github.com/Mbed-TLS/mbedtls/pull/8595/files#r1420474298 in another PR thus LGTM.

2024-01-11 15:59 UTC, merged