G2 wrap-up
Mbed-TLS/mbedtls pull request #8599
Opened 2023-12-04 11:10 UTC by valeriosetti

## Description

Resolves #8357

## PR checklist

- [ ] **changelog** provided
- [ ] **backport** not required
- [ ] **tests** provided

2023-12-05 11:29 UTC, mpg requested changes
Apart from a few typos/wording improvements, most of my comments about the part that's about G3, so I suggest we leave it out for now to get this merged, and we can pick it up later when we do G3 wrap-up.

2023-12-05 11:29 UTC, mpg commented on ChangeLog.d/8357.txt
> +     MBEDTLS_GCM_C and MBEDTLS_CHACHAPOLY_c) as well as the PSA one
Typo: `_c` -> `_C`.

2023-12-05 11:29 UTC, mpg commented on ChangeLog.d/8357.txt
> +     MBEDTLS_PSA_CRYPTO_C without MBEDTLS_CIPHER_C if any of the
I think you mean if none of the unauthenticated  ciphers is enabled?

2023-12-05 11:29 UTC, mpg commented on docs/driver-only-builds.md
> +It is possible to have all AEADs operations provided only by a driver.
I don't disagree, but that's G3 and this is supposed to be G2 wrap-up :)

Maybe skip this commit for now and work on the text in the G3-G4 wrap-up issue instead? The situation is actually not that easy to describe in a way that's both complete and readable.

2023-12-05 11:29 UTC, mpg commented on docs/driver-only-builds.md
> +  key types `MBEDTLS_[AES|ARIA|CAMELLIA|CHACHA20]_C` for AEADs which are
Note: for ChachaPoly you can also disable `MBEDTLS_POLY1305_C`.

2023-12-05 11:29 UTC, mpg commented on docs/driver-only-builds.md
> +If no other non-authenticated cipher is required, it is also possible to
Wording: "If no unauthenticated cipher" instead. (Unauthenticated ciphers are not AEADs, while "other" suggests they are.)

2023-12-05 11:29 UTC, mpg commented on docs/driver-only-builds.md
> +(ex: `mbedtls_ccm_init()`, etc) won't be possible.
Also, once you've disabled `AES_C` you won't get PEM descrytion, or PKCS5/15 or their use in in PKparse. (And perhaps others I'm forgetting, we should double-check what's disabled in the `all.sh` component and what's ignored in `analyze_coverage.py`.)

So, I think we need to change the structure like:
1. if all AEAD algs are accelerated, you can disable the AEAD modules (TODO: list them) and everything will work.
2. if additionally you don't need unauthenticated ciphers, you can disable `AES_C` etc and also `CIPHER_C` and everything will work except for PEM etc. (TODO: complete list - for now this even includes `CTR_DRBG_C`).

2023-12-05 11:29 UTC, mpg commented on configs/config-tfm.h
> + * does not need CIPHER_C to be enabled, so we can disabled it in order
Typo: disableD

2023-12-06 14:23 UTC, valeriosetti commented
@mpg as you correctly pointed out in [this comment](https://github.com/Mbed-TLS/mbedtls/pull/8599#discussion_r1415388595) it's very likely that `driver-only-builds.md` was not the right target of this PR, because this one is the wrap up of G2 which does not involve driver's acceleration. However, since I already started that section, I thought that instead of just dropping the commit, it was worth to add a disclaimer stating that it will be updated soon by another PR and then trying reshape it following your inputs of the following comments.
This seemed reasonable to me, but in case you don't like this approach just let me know and I will remove that change/commit(s).

2023-12-07 09:02 UTC, mpg approved these changes
LGTM.

(I'm not fully happy with the text in driver-only-builds.md yet, but I'm leaving that for later.)

2023-12-12 17:02 UTC, d3zd3z approved these changes

2023-12-13 10:46 UTC, merged