[Backport 2.28] Update `SSL_SERIALIZED_SESSION_CONFIG_BITFLAG` with new flags
Mbed-TLS/mbedtls pull request #8823
Opened 2024-02-13 19:02 UTC by davidhorstmann-arm

Simple but not trivial backport of #8821, created manually rather than through cherry-picking.

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [ ] **changelog** provided, or not required
- [ ] **backport** of #8821 
- [ ] **tests** provided, or not required

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

Help make review efficient:
* Multiple simple commits
  - please structure your PR into a series of small commits, each of which does one thing
* Avoid force-push
  - please do not force-push to update your PR - just add new commit(s)
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) for more details about the review process.

2024-02-29 18:41 UTC, mpg commented
> * **changelog** provided, or not required

I'd say required, since it's fixing a bug that was present in a released version.

2024-03-01 10:15 UTC, tom-cosgrove-arm commented on library/ssl_tls.c
> +         (SSL_SERIALIZED_SESSION_KEEP_PEER_CRT << SSL_SERIALIZED_SESSION_CONFIG_KEEP_CRT_BIT)))
Same naming nit as in the development PR: all the others have `CONFIG` in the name, and just add `_BIT` to specify the bit. This one doesn't have `CONFIG` in the name (but does in the `_BIT` value, but the `_BIT` value removes `_PEER`.

While this was probably done for length reasons, there is `SSL_SERIALIZED_SESSION_CONFIG_CLIENT_TICKET_BIT` which is as long as `SSL_SERIALIZED_SESSION_CONFIG_KEEP_PEER_CRT_BIT` would be

2024-03-01 10:15 UTC, tom-cosgrove-arm submitted a review, later dismissed
LGTM

2024-03-01 12:21 UTC, davidhorstmann-arm commented
Feedback should be addressed. Most of the refactoring work doesn't apply to 2.28 as all of the session serialization code is already in one place.

2024-03-01 12:27 UTC, tom-cosgrove-arm approved these changes
LGTM

2024-03-01 14:00 UTC, tom-cosgrove-arm approved these changes
LGTM

2024-03-01 17:54 UTC, ronald-cron-arm requested changes
Just two guards that are missing in the comments I think.

2024-03-01 17:54 UTC, ronald-cron-arm commented on library/ssl_tls.c
> + * #if defined(MBEDTLS_SSL_KEEP_PEER_CERTIFICATE)
```suggestion
 * #if defined(MBEDTLS_X509_CRT_PARSE_C)
 * #if defined(MBEDTLS_SSL_KEEP_PEER_CERTIFICATE)
```

2024-03-01 17:54 UTC, ronald-cron-arm commented on library/ssl_tls.c
> + * #if defined(MBEDTLS_SSL_SESSION_TICKETS)
```suggestion
 * #if defined(MBEDTLS_SSL_SESSION_TICKETS) && defined(MBEDTLS_SSL_CLI_C)
```

2024-03-04 16:43 UTC, tom-cosgrove-arm approved these changes
LGTM

2024-03-04 16:50 UTC, ronald-cron-arm approved these changes
Thanks for addressing my comments. LGTM. The CI is in a strange state though.

2024-03-04 16:55 UTC, tom-cosgrove-arm commented
The RTD build failure looks like a transient issue. I've re-started the CI on OpenCI (but that may not be the right thing to have done)

2024-03-04 17:01 UTC, davidhorstmann-arm commented
ReadTheDocs is separate, but I've restarted it

2024-03-05 10:01 UTC, gilles-peskine-arm commented
Merging is blocked because the DCO check didn't report back. I'll try the close-reopen trick.

2024-03-05 10:07 UTC, gilles-peskine-arm commented
Close-reopen did not work to re-trigger the DCO check. I'm out of ideas other than pushing a new commit (with an updated time or whatever).

2024-03-05 10:47 UTC, davidhorstmann-arm commented
(Rebasing the last commit with no changes seems to have worked)

2024-03-05 14:26 UTC, merged