Improve test info data accessors
Mbed-TLS/mbedtls pull request #8838
Opened 2024-02-15 14:13 UTC by paul-elliott-arm

## Description

After comments on the recent deadlock fix, attempt to improve the test info data acessors:

1. Mark all internal only functions as static, and rename them as `*_internal` in order to make them more obvious (in line with the aforementioned fix). Also add a comment block to further explain the mutex policies.
2. Whilst checking all the internal functions I spotted two cases which should have had mutex locks but did not (likely due to crossover between two PRs) and have fixed these.

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [ ] **changelog** ~~provided, or~~ not required (Part of multithreading work)
- [ ] **backport** ~~done, or~~ not required (code does not exist in LTS)
- [ ] **tests** ~~provided, or~~ not required (Part of test code)

2024-02-21 14:10 UTC, Ryan-Everett-arm requested changes
One comment could probably use changing, otherwise looks good.

2024-02-21 14:18 UTC, tom-cosgrove-arm commented on tests/src/helpers.c
> + * are expected to be used from this module *only*. These do not attempt to lock
That definitely sounds better. I'd say `in helpers.h` rather than just `in the header`, just to be more specific

2024-02-21 14:21 UTC, tom-cosgrove-arm commented on tests/src/helpers.c
> + * The main reason for this is the need to set some sets of test data
`set some sets` sounds awkward - is there another way to phrase that without the repetition? (I'm looking at a thesaurus right now!)

2024-02-21 14:22 UTC, tom-cosgrove-arm commented on tests/src/helpers.c
> + * The main reason for this is the need to set some sets of test data
Something like `need to set multiple test data values atomically`?

2024-02-21 14:22 UTC, tom-cosgrove-arm commented on tests/src/threading_helpers.c
> +             * mbedtls_threading_mutex_t object itself). The rare case of a
```suggestion
             * mbedtls_threading_mutex_t object itself). The (hopefully) rare case of a
```

2024-02-24 11:04 UTC, tom-cosgrove-arm approved these changes
LGTM

2024-02-26 10:22 UTC, Ryan-Everett-arm approved these changes
LGTM

2024-02-26 13:46 UTC, merged