Restore some X509 functions to public headers
Mbed-TLS/mbedtls pull request #8844
Opened 2024-02-19 11:27 UTC by davidhorstmann-arm

Restore some X509 functions that were erroneously removed in #8715 to public headers.

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** provided
- [x] **backport** not required - functions were only made private in 3.x
- [x] **tests** not required - no functional changes, only to the header location of functions

2024-02-19 12:55 UTC, tom-daubney-arm submitted a review, later dismissed
Subject to CI passing, this LGTM.

2024-02-19 15:20 UTC, tom-daubney-arm commented
OpenCI happy so I'm removing the label

2024-02-20 08:42 UTC, mpg requested changes
Thanks for fixing our mistakes :)

This time I was more careful and checked the diff with 3.5.2 to make sure no function was removed that wasn't already marked internal. I'm happy on this front, but this made me notice an function that was marked internal has actually been left public.

2024-02-20 08:42 UTC, mpg commented on ChangeLog.d/restore-x509-functions-to-public.txt
> +Bugfix
Thanks for not forgetting the ChangeLog, but this time I don't think an entry is needed, considering the bug was never present in any released version. (And the ChangeLog is about changes between say 3.5.2 and 3.6.0, not transient states in `development` in the meantime.)

2024-02-20 08:42 UTC, mpg commented on include/mbedtls/x509.h
>  int mbedtls_x509_string_to_names(mbedtls_asn1_named_data **head, const char *name);
Pre-existing: I think this one should have been removed by #8715. It was below the "Internal module functions" marker and has no doxygen doc. Sorry for noticing only now, but could you make it internal too?

2024-02-21 10:41 UTC, mpg submitted a review, later dismissed
LGTM, thanks!

2024-02-21 10:44 UTC, tom-daubney-arm approved these changes
LGTM

2024-02-21 15:35 UTC, gilles-peskine-arm commented
The CI is not happy.

2024-02-21 17:06 UTC, davidhorstmann-arm commented
> Pre-existing: I think this one should have been removed by #8715. It was below the "Internal module functions" marker and has no doxygen doc.

@mpg It seems that `mbedtls_x509_string_to_names()` was not moved to private because it was used in `programs/x509/cert_req.c` (which is causing CI failures). Given that it is the direct reverse of `mbedtls_x509_dn_gets()`, which is public, would it be okay to make this public too?

Would you accept adding a docstring to this function and keeping it in the public header?

2024-02-23 10:56 UTC, mpg commented
@davidhorstmann-arm Ah, so it wasn't missed, there was a reason Valerio kept it. Yes, I agree with make it public with an added docstring. Thanks!

2024-02-26 15:41 UTC, mpg approved these changes
LGTM, thanks!

2024-02-26 16:57 UTC, tom-daubney-arm approved these changes
Assuming CI success - this LGTM

2024-02-27 13:53 UTC, merged