Improve support of mbedtls_psa_get_random in client-only builds
Mbed-TLS/mbedtls pull request #8862
Opened 2024-02-26 11:56 UTC by valeriosetti

## Description

Resolves #8825.

## PR checklist

- [ ] **changelog** TODO
- [ ] **backport** not required
- [ ] **tests** not required: not adding new code, just changing the way it is enabled

2024-02-26 15:31 UTC, gilles-peskine-arm commented
> I'm not sure about the redundant declarations. It seems to me we should just #include "mbedtls/psa_util.h" and be done with it, is there a reason not to? (Perhaps there was one before but not any more?)

IIRC the reason for the redundant declarations was that both the public include file and the private one needed different cases for the three underlying RNG implementations (CTR_DRBG, HMAC_DRBG or PSA external). Since those cases are going away, I suspect there's nothing particularly fragile anymore.

> So, do we need this file at all or can we just fold it into psa_crypto.c

(the file being `psa_crypto_random_impl.h`)

That's from https://github.com/Mbed-TLS/mbedtls/pull/3933. At the time `mbedtls/psa_util.c` already exposed the PSA RNG abstraction so `psa_crypto_rsa.c` and friends could have used it, but they didn't. I guess the idea was that the PSA implementation would directly depend on a PSA interface rather than an mbedtls interface exposing that abstraction? Anyway I think that's irrelevant now and only `psa_crypto.c` needs to include `psa_crypto_random_impl.h`.

I think `psa_crypto_random_impl.h` does need to remain a header file, because the tests of that abstraction (in `test_suite_psa_crypto_init`) need the declarations.

2024-02-28 05:30 UTC, valeriosetti commented
I just checked and the only thing from `psa_crypto_random_impl.h` that it's referenced outside of `psa_crypto.c` is `MBEDTLS_PSA_HMAC_DRBG_MD_TYPE`. This means that most of the code from that header file can be moved to `psa_crypto.c`. *However* `psa_crypto.c` is already extremely long (> 8k lines), so that would make the file even longer and personally I'm not a big fan of this. Perhaps keeping the implementation in a separate file is a good solution.

2024-02-28 15:31 UTC, mpg commented
> I think `psa_crypto_random_impl.h` does need to remain a header file, because the tests of that abstraction (in `test_suite_psa_crypto_init`) need the declarations.

I don't think they do. As I wrote earlier, I tried commenting out that line and the test suite was still building and passing in both the default and the full config.

2024-02-29 14:26 UTC, valeriosetti commented
While writing the changelog for this PR I realized that I forgot to change the guard for `mbedtls_psa_get_random()` from `CRYPTO_C` to `CRYPTO_CLIENT`. However I suspect that this change might require the same fix for tests that was done in #8842. That's why I updated the description of the PR with this dependency.

2024-02-29 15:17 UTC, valeriosetti commented
[This](https://github.com/Mbed-TLS/mbedtls/pull/8862/commits/1a58e9a2326d34254125c30ffad9acd33a610905) commit updates the guard from `CRYPTO_C` to `CRYPTO_CLIENT`. In order to solve test issues in `component_test_psa_crypto_client()`, a stub function is also added for client only build. This mimics what Gilles suggested in #8842 and therefore this is also the reason for which I expect a conflict once #8842 will be merged. However it should be quite trivial to solve.

2024-02-29 16:02 UTC, mpg submitted a review, later dismissed
LGTM.

I still think `psa_crypto_random_impl.h` should be stripped down further, but that can be done later.

2024-03-01 08:27 UTC, valeriosetti commented
> I still think `psa_crypto_random_impl.h` should be stripped down further, but that can be done later.

One question on this so that I can file up a new issue. As I anticipated in a [previous comment](https://github.com/Mbed-TLS/mbedtls/pull/8862#issuecomment-1968262003) most of the `psa_crypto_random_impl.h` file is not used anywhere a part from `psa_crypto.c` so we can move most of former's content in the latter at the price of latter's size increase.
Can I create a new C file to hold this part instead of moving everything to `psa_crypto.c`? This would mean that `inline` functions will loose their inlining feature, but this should keep `psa_crypto.c` more readable :shrug: . Wdyt?

2024-03-01 16:32 UTC, tom-daubney-arm requested changes
Almost looks completely fine but with two very small nits that I almost feel guilty pulling you up on.

2024-03-01 16:32 UTC, tom-daubney-arm commented on ChangeLog.d/8825.txt
> +     used as random number generator function(f_rng) and context (p_rng) in
```suggestion
     used as random number generator function (f_rng) and context (p_rng) in
```

2024-03-01 16:32 UTC, tom-daubney-arm commented on tests/src/psa_crypto_stubs.c
> +#endif /* MBEDTLS_PSA_CRYPTO_CLIENT !MBEDTLS_PSA_CRYPTO_C */
```suggestion
#endif /* MBEDTLS_PSA_CRYPTO_CLIENT && !MBEDTLS_PSA_CRYPTO_C */
```

2024-03-01 21:08 UTC, gilles-peskine-arm commented
> Can I create a new C file to hold this part instead of moving everything to psa_crypto.c? This would mean that inline functions will loose their inlining feature, but this should keep psa_crypto.c more readable 🤷 . Wdyt?

That tends to be a compromise between readability and code size. For example we split off `psa_crypto_driver_wrappers.c` to a separate `.o` file, then we moved some of it back into a header to allow the functions to be inlined. Link-time optimization would make this not a concern, but many projects that consume Mbed TLS can't easily use LTO.

2024-03-04 14:00 UTC, tom-daubney-arm approved these changes
LGTM, thanks for the changes.

2024-03-10 20:05 UTC, mpg approved these changes
LGTM

2024-03-10 21:18 UTC, merged