New function mbedtls_pk_copy_public_from_psa
Mbed-TLS/mbedtls pull request #8899
Opened 2024-03-06 12:45 UTC by gilles-peskine-arm

Follow-up to https://github.com/Mbed-TLS/mbedtls/pull/8774#discussion_r1513205206: during the review, I identified a design gap: we're missing a convenient way to export the public key of a PSA key into PK.

Status: targeting the tip of #8774. Will need to be rebased once that is rebased and merged.

## PR checklist

- [x] **changelog** provided
- [x] **backport** no (new feature)
- [x] **tests** provided
- [ ] Update https://github.com/Mbed-TLS/mbedtls/pull/8889 to mention `mbedtls_pk_copy_public_from_psa`

2024-03-12 07:31 UTC, valeriosetti reviewed
I only found 1 fix, but a part from that this looks OK to me. I will approve once it will be rebased on #8774

2024-03-12 07:31 UTC, valeriosetti commented on tests/suites/test_suite_pk.function
> +    TEST_EQUAL(mbedtls_pk_copy_public_from_psa(pub_key_id, &pk_priv_copy_public), 0);
I think it's:
```suggestion
    TEST_EQUAL(mbedtls_pk_copy_public_from_psa(priv_key_id, &pk_priv_copy_public), 0);
```

2024-03-12 11:49 UTC, mpg requested changes
Looks good to me other than the issue already pointed out by Valerio.

2024-03-12 14:21 UTC, valeriosetti approved these changes
LGTM :)

2024-03-12 16:00 UTC, mpg submitted a review, later dismissed
LGTM

2024-03-12 18:24 UTC, gilles-peskine-arm commented
I changed the base branch now that the preceding PR is merged. Please re-approve.

2024-03-12 22:31 UTC, mpg approved these changes

2024-03-13 04:39 UTC, valeriosetti approved these changes

2024-03-13 08:16 UTC, merged