Move trivial scripts to framework submodule
Mbed-TLS/mbedtls pull request #8991
Opened 2024-03-26 16:16 UTC by davidhorstmann-arm

Move `code_style.py` and test code generation scripts to the framework submodule.

Depends on Mbed-TLS/mbedtls-framework#5

Note: The `framework` submodule is updated to the tip of Mbed-TLS/mbedtls-framework#5 to get the CI results. I can rebase this once that PR is merged.

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** not required - internal change only
- [x] **backport** not required - framework is 3.x only
- [x] **tests** not required file moves only

2024-03-27 14:57 UTC, davidhorstmann-arm commented
[Force-pushed to update to version of submodule with full history]

2024-03-28 12:17 UTC, Ryan-Everett-arm requested changes
I have found two comments in the codebase which still reference the old paths (sorry for not leaving my review comments on those lines - I don't think Github lets you comment on unchanged files). I am happy with everything else, though!

2024-03-28 12:29 UTC, davidhorstmann-arm commented
Thanks for catching these, should be addressed now!

2024-03-28 13:58 UTC, Ryan-Everett-arm approved these changes
LGTM, thanks!

2024-04-04 17:14 UTC, Ryan-Everett-arm requested changes
There are some CI failures in the trivial 3.6 backport (see my comment [here](https://github.com/Mbed-TLS/mbedtls/pull/9012#pullrequestreview-1980633899)). I think that this branch needs to be rebased to pull in the addition of  [tests/scripts/generate_psa_wrappers.py](https://github.com/Mbed-TLS/mbedtls/blob/development/tests/scripts/generate_psa_wrappers.py) so that we can change the references to `mbedtls_dev` in this file, otherwise the merge CI will likely fail.

2024-04-08 12:06 UTC, Ryan-Everett-arm requested changes
Thanks for the changes. It seems that there are now two scripts in both `mbedtls_dev` and `framework_dev`, everything else looks good though!

2024-04-08 12:40 UTC, Ryan-Everett-arm approved these changes
LGTM, thanks!

2024-04-24 06:57 UTC, ronald-cron-arm requested changes

2024-04-24 06:57 UTC, ronald-cron-arm commented on tests/scripts/check-python-files.sh
> +$PYTHON -m pylint framework/scripts/framework_dev/*.py scripts/*.py tests/scripts/*.py || {
Like in line 65, why not adding framework/scripts/*.py here as well?

2024-04-24 06:57 UTC, ronald-cron-arm commented on tests/scripts/check_files.py
> -from mbedtls_dev import build_tree
This file has to be modified to check the files that are in the `framework` submodule as well. It seems we just have to change `bytes_output = subprocess.check_output(['git', 'ls-files', '-z'])` to `bytes_output = subprocess.check_output(['git', 'ls-files', '--recurse-submodules', '-z'])`.

2024-05-30 08:23 UTC, davidhorstmann-arm commented
Closing as superseded by more separate PRs

2024-05-30 08:23 UTC, closed without merging