[Backport 3.6] Move some scripts to framework submodule
Mbed-TLS/mbedtls pull request #9012
Opened 2024-04-04 16:07 UTC by davidhorstmann-arm

Trivial backport of #8991

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** not required - internal changes only
- [x] **3.6 backport** of #8991 
- [x] **2.28 backport** not required - no framework submodule in 2.28
- [x] **tests** not required - file moves only

2024-04-04 16:45 UTC, Ryan-Everett-arm approved these changes
LGTM

2024-04-04 17:07 UTC, Ryan-Everett-arm requested changes
Looks like there are a couple of CI failures with file generation. I think the cause is this:
 There is a file `tests/scripts/generate_psa_wrappers.py` which exists in this branch ([and development](https://github.com/Mbed-TLS/mbedtls/blob/development/tests/scripts/generate_psa_wrappers.py)) but not in the branch for #8991, hence the CI passing there. This file has references to `mbedtls_dev` which need to be changed to `framework_dev`. I'm not sure why the file doesn't exist in #8991 - I think that #8991 also needs to be rebased so that we can change the `mbedtls_dev` references there.

2024-04-08 12:15 UTC, Ryan-Everett-arm requested changes
Thanks for the changes. It seems that there are now two scripts in both `mbedtls_dev` and `framework_dev`, everything else looks good though!

2024-04-08 12:15 UTC, Ryan-Everett-arm commented on framework
`c_parsing_helper.py` and `c_wrapper_generator.py` are added to framework but are not currrently removed from `mbedtls_dev`

2024-04-08 12:39 UTC, Ryan-Everett-arm approved these changes
LGTM, thanks for the quick changes!

2024-05-31 06:32 UTC, ronald-cron-arm commented
Closing as superseded by more separate PRs

2024-05-31 06:32 UTC, closed without merging