Fixed redefination warning messages for _GNU_SOURCE
Mbed-TLS/mbedtls pull request #9026
Opened 2024-04-12 06:47 UTC by nileshkale123

## Description

This commit solves the issue of redefinition warning messages for _GNU_SOURCE while building on Linux platform.

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [ ] **changelog** provided, or not required
- [ ] **3.6 backport** done, or not required
- [ ] **2.28 backport** done, or not required
- [ ] **tests** provided, or not required

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

Help make review efficient:
* Multiple simple commits
  - please structure your PR into a series of small commits, each of which does one thing
* Avoid force-push
  - please do not force-push to update your PR - just add new commit(s)
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) for more details about the review process.

2024-04-16 11:54 UTC, yanesca requested changes
Hi @nileshkale123, thank you for your contribution.

After fixing the superfluous empty line, could you please raise backport PRs against the `mbedtls-2.28` and `mbedtls-3.6` branches?

2024-04-16 11:54 UTC, yanesca commented on ChangeLog.d/fix-redefination_warning_messages_for_GNU_SOURCE.txt
> +
We are processing these files with a script and it needs the first line to be non-empty. Could you please delete this line.

2024-04-18 13:09 UTC, yanesca requested changes
There is a newline character missing from the end of the last line which makes the CI fail. Could you please fix that?

2024-04-18 13:09 UTC, yanesca commented on ChangeLog.d/fix-redefination_warning_messages_for_GNU_SOURCE.txt
> +     entropy_poll.c and sha_256.c. There was build warnng during
```suggestion
     entropy_poll.c and sha_256.c. There was build warning during
```

2024-04-22 11:03 UTC, yanesca submitted a review, later dismissed
LGTM

2024-04-22 11:27 UTC, tom-daubney-arm requested changes
Looks good except for a couple of small typos.

2024-04-22 11:27 UTC, tom-daubney-arm commented on ChangeLog.d/fix-redefination_warning_messages_for_GNU_SOURCE.txt
> +   * Fix issue of redefination warning messages for _GNU_SOURCE in
```suggestion
   * Fix issue of redefinition warning messages for _GNU_SOURCE in
```

2024-04-22 11:27 UTC, tom-daubney-arm commented on ChangeLog.d/fix-redefination_warning_messages_for_GNU_SOURCE.txt
> +     entropy_poll.c and sha_256.c. There was build warning during
```suggestion
     entropy_poll.c and sha_256.c. There was a build warning during
```

2024-04-30 08:22 UTC, yanesca approved these changes
LGTM

2024-04-30 09:26 UTC, tom-cosgrove-arm requested changes
The CI failure is relevant:

```
[2024-04-30T08:35:15.580Z] ******************************************************************
[2024-04-30T08:35:15.580Z] * check_files: Check: file sanity checks (permissions, encodings) 
[2024-04-30T08:35:15.580Z] * Tue Apr 30 08:35:15 UTC 2024
[2024-04-30T08:35:15.580Z] ******************************************************************
[2024-04-30T08:35:22.185Z] Trailing whitespace:
[2024-04-30T08:35:22.185Z] ChangeLog.d/fix-redefination_warning_messages_for_GNU_SOURCE.txt: 2, 3
[2024-04-30T08:35:22.185Z] 
[2024-04-30T08:35:22.185Z] ^^^^check_files: Check: file sanity checks (permissions, encodings): tests/scripts/check_files.py -> 1^^^^
```

Please remove the trailing whitespace in `ChangeLog.d/fix-redefination_warning_messages_for_GNU_SOURCE.txt`

2024-04-30 14:53 UTC, tom-cosgrove-arm approved these changes
Backports to 3.6 and 2.28 are still required

2024-05-02 07:57 UTC, tom-cosgrove-arm commented
@nileshkale123 Are you able to create the backports for the `mbedtls-2.28` and `mbedtls-3.6` branches?

2024-05-02 09:24 UTC, nileshkale123 commented
> @nileshkale123 Are you able to create the backports for the `mbedtls-2.28` and `mbedtls-3.6` branches?

Yes, I have created MR with issue ID 9085 & 9086

2024-05-06 14:53 UTC, merged