Doc guards
Mbed-TLS/mbedtls pull request #9161
Opened 2024-05-22 11:03 UTC by mpg

## Description

Please write a few sentences describing the overall goals of the pull request's commits.

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [ ] **changelog** provided, or not required
- [ ] **3.6 backport** done, or not required
- [ ] **2.28 backport** done, or not required
- [ ] **tests** provided, or not required

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

Help make review efficient:
* Multiple simple commits
  - please structure your PR into a series of small commits, each of which does one thing
* Avoid force-push
  - please do not force-push to update your PR - just add new commit(s)
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) for more details about the review process.

2024-05-22 12:57 UTC, gilles-peskine-arm requested changes
Looks correct to me apart from some minor niggles.

However, this does not address https://github.com/Mbed-TLS/mbedtls/issues/8736.

2024-05-22 12:57 UTC, gilles-peskine-arm commented on docs/architecture/psa-migration/strategy.md
> +As of Mbed TLS 3.6 (early 2024, work towards G5 is well advanced: it is now
```suggestion
As of Mbed TLS 3.6 (early 2024), work towards G5 is well advanced: it is now
```

2024-05-22 12:57 UTC, gilles-peskine-arm commented on docs/architecture/psa-migration/strategy.md
> +with some limitations. See `docs/driver-only-builds.md` for details.
```suggestion
with some limitations. See [`docs/driver-only-builds.md`](../../driver-only-builds.html) for details.
```

2024-05-22 12:57 UTC, gilles-peskine-arm commented on docs/architecture/psa-migration/strategy.md
> +  `md-cipher-dispatch.md`.
```suggestion
  [`md-cipher-dispatch.md`](md-cipher-dispatch.html).
```

2024-05-23 07:15 UTC, mpg commented
> However, this does not address #8736.

Aw, I forgot to add the new file, how embarrassing. Sorry.

2024-07-02 15:46 UTC, gilles-peskine-arm commented on docs/architecture/psa-migration/transition-guards.md
> +
Macros defined in `include/mbedtls/config_adjust_legacy_*.h` only, used outside of `include/mbedtls/*.h` and not mentioned here:

* `MBEDTLS_BLOCK_CIPHER_xxx_VIA_xxx` (used in library, test dependencies)
* `MBEDTLS_BLOCK_CIPHER_SOME_PSA` (used in library, test helpers, test code)
* `MBEDTLS_MD_xxx_VIA_PSA` (used in library, test dependencies)
* `MBEDTLS_PSA_UTIL_HAVE_ECDSA` (used in library, test dependencies)

We should document them as well, but that's not a blocker for this pull request.

2024-07-03 09:07 UTC, gilles-peskine-arm commented
This should be on the 3.6 branch, since it won't be relevant in 4.0.

2024-09-10 09:18 UTC, mpg commented
@gilles-peskine-arm I added commits addressing your feedback, and then rebased to resolve conflicts and more importantly target the correct branch. Please feel free to review again. Note: I wasn't sure if this is priority medium of high, please feel free to adjust.

2024-09-11 10:04 UTC, mpg commented
> @mpg 1. So this shouldn't be a draft PR anymore? 2. The CI isn't happy.

Yeah, I meant to un-draft it but forgot, thanks for the reminder. Regarding the CI, I'm not sure what happened but it's looking happy now.

2024-09-25 15:35 UTC, gilles-peskine-arm requested changes
Thanks for the updates! This mostly looks good to me, but there's one 4.0 plan that just changed, and a few requests for clarifications from my previous review that you haven't addressed and I think at least some of them should be addressed.

2024-09-25 15:35 UTC, gilles-peskine-arm commented on docs/architecture/psa-migration/psa-limitations.md
> +- Restartable/interruptible ECC operations: support in PSA will be added in 4.0.
“will be added in 4.0” isn't quite accurate. Interruptible signatures were already in 2.28. Restartable ECDH should be in 4.0. We haven't decided yet about restartable export-public. Their usage in TLS will not be in 4.0.

2024-09-25 15:35 UTC, gilles-peskine-arm commented on docs/architecture/psa-migration/transition-guards.md
> +**Overview of existing (internal) APIs:** we currently have 4 (families of)
Block cipher modes are still missing herre.

2024-09-25 15:35 UTC, gilles-peskine-arm commented on docs/architecture/psa-migration/transition-guards.md
> +Note that there is a rule, enforced by `config_adjust_psa_superset_legacy.h`,
Not a blocker, but the clarifications I requested on this paragraph (https://github.com/Mbed-TLS/mbedtls/pull/9161/files#r1657124669, https://github.com/Mbed-TLS/mbedtls/pull/9161/files#r1657126157, https://github.com/Mbed-TLS/mbedtls/pull/9161/files#r1657136618https://github.com/Mbed-TLS/mbedtls/pull/9161/files#r1657136618) haven't been addressed.

2024-09-25 15:35 UTC, gilles-peskine-arm commented on docs/architecture/psa-migration/transition-guards.md
> +
CTR_DRBG is still missing here.

2024-09-25 15:35 UTC, gilles-peskine-arm commented on docs/architecture/psa-migration/transition-guards.md
> +**Legacy and `USE_PSA` domains:** no users here.
The legacy API does expose key derivation used by code in the USE_PSA domain: PKCS5 and PKCS12.

2024-09-25 15:35 UTC, gilles-peskine-arm commented on docs/architecture/psa-migration/transition-guards.md
> +are also supported on the PSA side (`PSA_WANT_ECC_xxx`).
As noted before, only if some PSA is included.

2024-09-26 08:14 UTC, mpg commented on docs/architecture/psa-migration/transition-guards.md
> +**Legacy and `USE_PSA` domains:** no users here.
Well, the key derivation functions are exposed but not directly called by library code - PK only uses those key derivations indirectly through the use of the associated password-based encryption scheme. I've added a paragraph anyway.

2024-09-26 09:02 UTC, mpg commented
@gilles-peskine-arm Thanks for your review and sorry for forgetting to address some of your comments. I believe I've now addressed all of them except for https://github.com/Mbed-TLS/mbedtls/pull/9161#discussion_r1662777690 which I'd rather leave for later.

2024-10-03 10:33 UTC, gilles-peskine-arm approved these changes
LGTM

2024-10-03 10:33 UTC, gilles-peskine-arm commented on docs/architecture/psa-migration/transition-guards.md
> +this domain as opposed to the `USE_PSA` domain whithout looking at the code.
Trivial:
```suggestion
this domain as opposed to the `USE_PSA` domain without looking at the code.
```

2024-10-09 10:14 UTC, Harry-Ramsey approved these changes
LGTM. I don't have prior experience with 3.6 drivers but this information seems vastly useful for developing ontop of Mbed TLS. The transition guards section will be useful for developing ontop of Mbed TLS or contributing to the library as a whole.

2024-10-09 12:03 UTC, merged