Replace MBEDTLS_MD_CAN_SHA224 with PSA_WANT_ALG_SHA_224
Mbed-TLS/mbedtls pull request #9170
Opened 2024-05-23 13:51 UTC by eleuzi01

## Description

Issue #9111

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** not required, internal changes
- [x] **3.6 backport** not required, needed for 4.0
- [x] **2.28 backport** not required, needed for 4.0
- [x] **tests** not required

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

Help make review efficient:
* Multiple simple commits
  - please structure your PR into a series of small commits, each of which does one thing
* Avoid force-push
  - please do not force-push to update your PR - just add new commit(s)
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) for more details about the review process.

2024-06-25 17:05 UTC, gabor-mezei-arm requested changes
This occurrence also should be replaced:
https://github.com/Mbed-TLS/mbedtls/blob/dfa1343c4ce6ac1ccf1f0d298ad82a5c9ac1b63b/include/mbedtls/md.h#L76

2024-06-26 09:13 UTC, eleuzi01 commented
> This occurrence also should be replaced:
> 
> https://github.com/Mbed-TLS/mbedtls/blob/dfa1343c4ce6ac1ccf1f0d298ad82a5c9ac1b63b/include/mbedtls/md.h#L76

@gabor-mezei-arm in the issue description it said replace everywhere except in the include directory. Is this an exception, or should I also replace MBEDTLS_MD_CAN_SHA224 in the include directory as well?

2024-06-26 09:32 UTC, gabor-mezei-arm commented
It seems the `md.h` is an exception. The others don't need to be changed.

2024-06-26 15:57 UTC, gabor-mezei-arm submitted a review, later dismissed
LGTM

2024-07-02 19:19 UTC, tom-daubney-arm approved these changes
LGTM - thanks!

2024-07-03 16:56 UTC, merged