Adapt components with MBEDTLS_PSA_CRYPTO_CONFIG enabled
Mbed-TLS/mbedtls pull request #9185
Opened 2024-05-27 07:00 UTC by ronald-cron-arm

## Description
Progresses #8153 

## PR checklist
- [x] **changelog** not required
- [ ] **3.6 backport** TODO, partial, two fixes 
- [x] **2.28 backport** not required, fixes to be backported to 3.6 not relevant to 2.28
- [x] **tests** not required

2024-06-04 17:42 UTC, ronald-cron-arm commented
I've rebased because of a conflict following the merge of #9200, move of generate_psa_wrappers.py to the framework repository. Because of the move to the framework this PR is not associated to a framework PR, namely  https://github.com/Mbed-TLS/mbedtls-framework/pull/22. Eventually, following the discussion in #9190, I have just removed `component_test_full_no_bignum` rather than adapting it.

2024-06-05 09:11 UTC, ronald-cron-arm commented
@tom-daubney-arm @davidhorstmann-arm this is now ready for re-review/review. See https://github.com/Mbed-TLS/mbedtls/pull/9185#issuecomment-2148077258 for more information.

2024-06-07 08:08 UTC, ronald-cron-arm commented
I've just amended the last commit to get the DCO check.

2024-06-17 15:40 UTC, tom-daubney-arm approved these changes
LGTM - thanks

2024-06-17 17:28 UTC, davidhorstmann-arm requested changes
The tip of MbedTLS/mbedtls-framework#22 doesn't seem to match the submodule update for this PR, have you missed an update to one of them?

The framework commit in this PR seems to be `353f7145f259a6f24f2483395d46e86ae27ae085`, whereas the tip of Mbed-TLS/mbedtls-framework#22 is `c3d2f019196c1109ed9b5f730eff8b4d09806f75`

2024-06-17 19:10 UTC, davidhorstmann-arm approved these changes
LGTM, thanks!

2024-06-18 13:18 UTC, ronald-cron-arm commented
> The tip of MbedTLS/mbedtls-framework#22 doesn't seem to match the submodule update for this PR, have you missed an update to one of them?
> 
> The framework commit in this PR seems to be `353f7145f259a6f24f2483395d46e86ae27ae085`, whereas the tip of [Mbed-TLS/mbedtls-framework#22](https://github.com/Mbed-TLS/mbedtls-framework/pull/22) is `c3d2f019196c1109ed9b5f730eff8b4d09806f75`.
> 
> The 2 commits are equivalent and this PR will be updated on the merge of the other anyway, so I'll review the other work.

Yes sorry about that, in #22 I had to retrigger the DCO check and this has resulted in a change of commit id whilst the content of the commit is the same.

2024-06-19 07:42 UTC, ronald-cron-arm commented
@davidhorstmann-arm @tom-daubney-arm there was a conflict with development regarding the framework pointer. My understanding is that following the merge of #9247, the framework commit pointed to by this PR was not a descendant of the framework commit pointed to by the head of the development branch. Thus I have rebased. Apart from the framework, the rebase was straightforward. Regarding the framework, the commit "tests: src: Fix PSA test wrappers for PAKE" now points to the rebase of PR22 on top of the merge of PR 26: commit b332327b5e. Note that in PR22, GitHub has kept your approvals after the rebase, I guess this is because the trees before and after the rebase are the same.

2024-06-19 10:08 UTC, ronald-cron-arm commented
@davidhorstmann-arm @tom-daubney-arm the OpenCI has passed successfully thus the CI can be considered as green. The PR is ready for re-review, thanks.

2024-06-19 11:00 UTC, davidhorstmann-arm approved these changes
Rebase LGTM, thanks!

2024-06-19 11:50 UTC, ronald-cron-arm commented
@davidhorstmann-arm @tom-daubney-arm last bit, the update of the framework to the merge of PR22.

2024-06-19 12:08 UTC, davidhorstmann-arm approved these changes
LGTM, thanks!

2024-06-19 13:19 UTC, tom-daubney-arm commented
Note: Internal CI failures are spurious and due to timeouts.

2024-06-19 14:50 UTC, merged