Move test data files to framework
Mbed-TLS/mbedtls pull request #9249
Opened 2024-06-12 15:23 UTC by davidhorstmann-arm

Move `tests/data_files` to the `framework` submodule. Paired with Mbed-TLS/mbedtls-framework#18. 

Fixes Mbed-TLS/mbedtls-framework#17.

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** not required - internal change only
- [x] **3.6 backport** #9375 
- [x] **2.28 backport** not required - no framework in 2.28
- [x] **tests** not required - file motion only

2024-06-28 08:07 UTC, ronald-cron-arm requested changes
This looks almost good to me.
I have checked that the "Move some files to framework repository" commits in mbedtls and mbedtls-framework are both based on the same commit: https://github.com/Mbed-TLS/mbedtls/commit/2a674bd9ce4758dff0d18f4ac8b6da4419efc504. The one in mbedtls removes the tests/data_files/* files while the one in mbedtls-framework removes all files but the tests/data_files/* ones that are renamed (path change only), same 773 files removed/renamed in both cases and only data_files/* remaining in the mbedtls-framework PR.

2024-07-02 15:24 UTC, davidhorstmann-arm commented
@ronald-cron-arm @tom-daubney-arm I'll wait for your reviews before I rebase, unless it seems better to you to go ahead?

2024-07-02 15:48 UTC, tom-daubney-arm commented
> @ronald-cron-arm @tom-daubney-arm I'll wait for your reviews before I rebase, unless it seems better to you to go ahead?

Fine for me if you wait.

2024-07-02 16:39 UTC, ronald-cron-arm requested changes

2024-07-02 16:39 UTC, ronald-cron-arm commented on tests/scripts/generate_tls13_compat_tests.py
> +    'ecdsa_secp256r1_sha256': Certificate(DATA_FILES_PATH + '/test-ca2.crt',
Rather
```suggestion
    'ecdsa_secp256r1_sha256': Certificate('$DATA_FILES_PATH/test-ca2.crt',
```
I'd say with DATA_FILES_PATH defined in ssl-opt.sh and then update tls13-compat.sh accordingly.

2024-07-03 17:13 UTC, ronald-cron-arm approved these changes
LGTM but got some conflicts now.

2024-07-04 10:19 UTC, tom-daubney-arm submitted a review, later dismissed
Sorry for taking so long on this one. It took me a minute to work out the workflow here and to verify that the two streams of work are based on the same commit. But I have verified that now and can see they are both based on [2a674bd9ce](https://github.com/Mbed-TLS/mbedtls/commit/2a674bd9ce4758dff0d18f4ac8b6da4419efc504) which also agrees with @ronald-cron-arm's review.

This all LGTM and will review again once the conflicts are merged.

2024-07-05 15:00 UTC, davidhorstmann-arm commented
Rebased by doing the following actions:

* Recreate the file-move commit on top of latest `development` and make a new branch from it
* Cherry-pick path-updating commits from the existing branch onto the new branch:
    * There were conflicts in some test data files due to test dependency renames (`MBEDTLS_XYZ_C` to `PSA_WANT_XYZ`). These were fairly easy to resolve.
    * I skipped framework update commits as these caused conflicts
 * Add a framework update commit at the end that updates to the latest version of the framework PR.

2024-07-08 06:54 UTC, ronald-cron-arm submitted a review, later dismissed
LGTM. The "Move some files to framework repository" commits in mbedtls and mbedtls-framework are now both based on commit: https://github.com/Mbed-TLS/mbedtls/commit/675e150b0f6080eccb43db8e3a3a55ade50dca82.

2024-07-08 11:35 UTC, tom-daubney-arm submitted a review, later dismissed
LGTM! I too confirm that after the rebase the commits are based on the same commit, being  [675e150](https://github.com/Mbed-TLS/mbedtls/commit/675e150b0f6080eccb43db8e3a3a55ade50dca82).

2024-07-09 08:14 UTC, davidhorstmann-arm reviewed
Submodule update LGTM

2024-07-09 08:19 UTC, ronald-cron-arm approved these changes
LGTM with the approval of the last commit by @davidhorstmann-arm

2024-07-09 10:50 UTC, tom-daubney-arm approved these changes
Updates LGTM, thanks.

2024-07-09 13:31 UTC, merged