Fix compiler warnings in test_suite_pk.function
Mbed-TLS/mbedtls pull request #9250
Opened 2024-06-13 09:44 UTC by eleuzi01

## Description

A fix for compiler warnings in test_suite_pk.function when SECP192R1 or/and SECP192K1 are disabled, see #9029 

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [ ] **changelog** provided, or not required
- [ ] **3.6 backport** done, or not required
- [ ] **2.28 backport** done, or not required
- [ ] **tests** provided, or not required

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

Help make review efficient:
* Multiple simple commits
  - please structure your PR into a series of small commits, each of which does one thing
* Avoid force-push
  - please do not force-push to update your PR - just add new commit(s)
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) for more details about the review process.

2024-06-17 14:31 UTC, sezrab requested changes
Looks good. Should it have a change-log since these are user-facing changes?

2024-06-17 14:31 UTC, minosgalanakis submitted a review, later dismissed
LGTM

2024-06-17 14:36 UTC, minosgalanakis commented
> Looks good. Should it have a change-log since these are user-facing changes?

We do not normally do changelog entries for test code.

We **should have** 3.6 backports though.

2024-06-17 14:37 UTC, sezrab submitted a review, later dismissed

2024-06-17 14:59 UTC, gilles-peskine-arm commented
We don't write changelog entries for test improvements, but this is a build failure, and it's user-reported, so I think we should have a changelog entry.

2024-06-17 16:16 UTC, eleuzi01 commented
> We don't write changelog entries for test improvements, but this is a build failure, and it's user-reported, so I think we should have a changelog entry.

Done, let me know if it's good.

2024-06-17 17:59 UTC, gilles-peskine-arm submitted a review, later dismissed
LGTM

2024-06-17 18:01 UTC, gilles-peskine-arm commented on ChangeLog.d/fix-test-suite-pk-warnings.txt
> +     Fixes #9029.
The last line is missing a newline at the end. That confuses some tools including `assemble_changelog.py`.

2024-06-18 12:07 UTC, tom-cosgrove-arm approved these changes
LGTM

2024-06-18 13:14 UTC, minosgalanakis approved these changes
LGTM

2024-06-24 10:41 UTC, paul-elliott-arm commented
Ignoring Open CI fail, as internal passed.

2024-06-24 12:34 UTC, merged