Remove hash alt interface
Mbed-TLS/mbedtls pull request #9265
Opened 2024-06-14 15:13 UTC by tom-daubney-arm

## Description

Remove hash ALT interfaces.

This PR is made up of commits split out from #9226 in order to ease review.

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** Will be provided at end of PR series
- [x] **3.6 backport** not required
- [x] **2.28 backport** not required
- [x] **tests** existing tests suffice

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

Help make review efficient:
* Multiple simple commits
  - please structure your PR into a series of small commits, each of which does one thing
* Avoid force-push
  - please do not force-push to update your PR - just add new commit(s)
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) for more details about the review process.

2024-06-17 08:11 UTC, ronald-cron-arm requested changes

2024-06-17 08:11 UTC, ronald-cron-arm commented on include/mbedtls/mbedtls_config.h
> + * \note When the underlying implementation of the CMAC algorithm is provided
Just remove I think.

2024-06-17 08:11 UTC, ronald-cron-arm commented on include/mbedtls/cmac.h
> + *                      implementation (through a PSA driver), some ciphers
Just remove the note I think. Ditto below.

2024-06-20 07:08 UTC, ronald-cron-arm requested changes

2024-06-20 07:08 UTC, ronald-cron-arm commented on include/mbedtls/cmac.h
> - * \note                When the CMAC implementation is supplied by an alternate
Two similar notes to remove below as well.

2024-06-25 08:08 UTC, ronald-cron-arm submitted a review, later dismissed
LGTM, thanks.

2024-07-08 17:47 UTC, bensze01 approved these changes
LGTM. Please rebase to resolve the conflicts.

2024-07-10 07:25 UTC, ronald-cron-arm submitted a review, later dismissed
I've checked the rebase, LGTM.

2024-07-11 08:17 UTC, tom-daubney-arm commented
@ronald-cron-arm Rebased without needing manual conflict resolution.

2024-07-11 12:49 UTC, ronald-cron-arm approved these changes
LGTM

2024-07-12 13:47 UTC, bensze01 approved these changes
LGTM

2024-07-15 11:59 UTC, ronald-cron-arm approved these changes
Rebase LGTM.

2024-07-15 14:22 UTC, bensze01 approved these changes
LGTM

2024-07-15 15:56 UTC, merged