Fix some all.sh components with sub-components
Mbed-TLS/mbedtls pull request #9293
Opened 2024-06-20 08:31 UTC by gilles-peskine-arm

This is a collection of fixes to issues in `all.sh` that I discovered while working on https://github.com/Mbed-TLS/mbedtls/pull/9286. The biggest part is a reorganization of `component_build_aes_armce` and `component_build_sha_armce` to make them split into clear distinct configurations.

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** not required (test only)
- [ ] **3.6 backport** TODO
- [ ] **2.28 backport** TODO (very partial)
- [x] **tests** provided

2024-07-11 18:39 UTC, waleed-elmelegy-arm approved these changes
LGTM

2024-08-02 08:55 UTC, yanesca approved these changes
LGTM

2024-08-02 09:22 UTC, gilles-peskine-arm commented on tests/scripts/all.sh
> -    not grep mbedtls_des* ${BUILTIN_SRC_PATH}/des.o
It's true, that's the point. `mbedtls_des*` is a regular expression, so `*` means “zero or more of the preceding character or group”. It matches `mbedtls_derive` with `s*` matching 0 occurrences of `s`.

(Not mentioned, the unlikely case where there is at least one file in the current directory whose name starts with `mbedtls_des`, in which case `grep` would search a pattern based on the first matching file name and would search the other files whose name matches if there are any.)

2024-08-02 09:24 UTC, yanesca commented on tests/scripts/all.sh
> -    not grep mbedtls_des* ${BUILTIN_SRC_PATH}/des.o
Oh, indeed, it fooled me too :)

2024-08-05 12:31 UTC, yanesca requested changes
I looks like now we need a rebase.

2024-08-05 14:16 UTC, gilles-peskine-arm commented
I rebased to resolve the conflicts, mostly in `tests/scripts/all.sh` after #8226 but also consecutive lines modified in `library/Makefile`. The previous version is in https://github.com/gilles-peskine-arm/mbedtls/tree/outcome-check-repeated-configurations-all.sh-preliminaries-2.

The following command shows that the new changeset differs from the old one only by file names and (in a few places) context, but the line changes are the same.
```
git range-diff origin/development 3856d5cf68130f9e66704b54cd8bd7dee7df4ff8 59aea4e1cc2c1b94ef10ed0872f278aa4c449380 | grep -v '^    [-+][-+]'
```

2024-08-05 16:24 UTC, yanesca approved these changes
I have checked the parameters and the output of the range-diff command, the only differences are in a few commit messages.

Looks good to me.

2024-09-24 10:28 UTC, waleed-elmelegy-arm approved these changes
Checked the diff as well, LGTM.

2024-10-25 16:26 UTC, merged