Move mbedtls crypto headers
Mbed-TLS/mbedtls pull request #9299
Opened 2024-06-20 15:44 UTC by ronald-cron-arm

## Description
Repo split preparation, move Mbed TLS crypto headers to  tf-psa-crypto.
Companion mbedtls-framework PR: https://github.com/Mbed-TLS/mbedtls-framework/pull/30
Fix #9262 

## PR checklist
- [x] **changelog** not required, we will have one change log for the whole repo split work
- [x] **3.6 backport** nothing to backport
- [x] **2.28 backport** nothing to backport
- [x] **tests** no additional tests required

2024-06-26 10:41 UTC, tom-daubney-arm approved these changes
All LGTM, except the conflicts which I assume will be rebased after the review from @bensze01

2024-07-01 12:42 UTC, bensze01 requested changes
One small typo. Other than that, looks good to me.

2024-07-01 12:42 UTC, bensze01 commented on library/Makefile
> +# ../tf-psa-crypto/drivers/builtin/includefor public headers and . for
Missing space
```suggestion
# ../tf-psa-crypto/drivers/builtin/include for public headers and . for
```

2024-07-01 13:02 UTC, ronald-cron-arm commented
I've rebased to resolve the conflicts (trivial), fixed the typo and updated the framework to the merge of PR 30. @tom-daubney-arm @bensze01 please have another look.

2024-07-01 13:33 UTC, bensze01 approved these changes
LGTM, thanks!

2024-07-01 16:04 UTC, merged