Replace MBEDTLS_SSL_HAVE_CBC with PSA_WANT_ALG_CBC_NO_PADDING
Mbed-TLS/mbedtls pull request #9363
Opened 2024-07-05 10:33 UTC by eleuzi01

## Description

Partially resolves #9335 

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** not required, internal changes
- [x] **3.6 backport** not required, needed for 4.0
- [x] **2.28 backport** not required, needed for 4.0
- [x] **tests** not required

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

Help make review efficient:
* Multiple simple commits
  - please structure your PR into a series of small commits, each of which does one thing
* Avoid force-push
  - please do not force-push to update your PR - just add new commit(s)
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) for more details about the review process.

2024-07-09 15:54 UTC, gilles-peskine-arm requested changes
Please put this on hold until we have architectural agreement.

2024-07-09 15:54 UTC, gilles-peskine-arm commented on library/ssl_misc.h
> +#if defined(PSA_WANT_ALG_CBC_NO_PADDING)      &&                                  \
I don't understand why we're doing this [and I don't think we should](https://github.com/Mbed-TLS/mbedtls/issues/9335#issuecomment-2218071604). It's a good thing that SSL have-algorithm guards are separate from crypto supply-algorithm guards.

2024-07-10 15:10 UTC, gabor-mezei-arm commented
The `MBEDTLS_SSL_HAVE_CBC` macro should not has to be removed.

2024-07-26 08:15 UTC, mpg commented
The design discussion has been resolved, see https://github.com/Mbed-TLS/mbedtls/issues/9335#issuecomment-2251107614

2024-08-01 08:55 UTC, gabor-mezei-arm approved these changes
LGTM

2024-08-01 13:26 UTC, sezrab approved these changes
LGTM

2024-08-01 15:30 UTC, merged