ecp.c: Added minor comment
Mbed-TLS/mbedtls pull request #9494
Opened 2024-08-21 15:59 UTC by minosgalanakis

## Description

Added a comment based on an investigation we did at the functional behaviour of a check.  

## PR checklist

Please remove the segment/s on either side of the | symbol as appropriate, and add any relevant link/s to the end of the line.
If the provided content is part of the present PR remove the # symbol.

- [ ] **changelog** provided | not required because: is a minor comment
- [ ] **development PR** provided # | not required because: 
- [ ] **framework PR** not required
- [ ] **3.6 PR** provided # | not required because: 
- [ ] **2.28 PR** provided # | not required because: 
- **tests**  not required because:  is a minor comment

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

Help make review efficient:
* Multiple simple commits
  - please structure your PR into a series of small commits, each of which does one thing
* Avoid force-push
  - please do not force-push to update your PR - just add new commit(s)
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) for more details about the review process.

2024-08-22 09:45 UTC, gilles-peskine-arm requested changes
The comment isn't right.

2024-08-22 09:45 UTC, gilles-peskine-arm commented on tf-psa-crypto/drivers/builtin/src/ecp.c
> +                                                           can not be equal to UINT64_MAX. */
Sorry, this comment is wrong.

> Zero limb mpis are invalid

1. Zero-limb `mbedtls_mpi` are perfectly valid to represent the value 0.
2. Zero-limb MPIs are not relevant here. `mbedtls_mpi_bitlen(d)` is 0 when the value of `d` is 0, regardless of how many limbs are used to represent it.

> can not be equal to `UINT64_MAX`

`UINT64_MAX` is irrelevant here, you meant `SIZE_MAX`. This computation doesn't involve `uint64_t` values. Both `mbedtls_mpi_bitlen(d)` and `grp->nbits` are `size_t` values.

2024-08-22 09:45 UTC, gilles-peskine-arm commented on tf-psa-crypto/drivers/builtin/src/ecp.c
>              mbedtls_mpi_bitlen(d) - 1 != grp->nbits) {  /* mbedtls_mpi_bitlen is one-based! */
We could just rewrite this and avoid getting bogged down by a subtraction.
```suggestion
            mbedtls_mpi_bitlen(d) != grp->nbits + 1) {  /* mbedtls_mpi_bitlen is one-based! */
```

2024-08-22 15:36 UTC, gilles-peskine-arm approved these changes
LGTM

2025-01-23 15:33 UTC, minosgalanakis commented
This PR has been migrated to the TF-PSA-Framework [PR166](https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/166)

2025-01-23 15:33 UTC, closed without merging