ccm.c: Return early when ccm* is used without tag.
Mbed-TLS/mbedtls pull request #9497
Opened 2024-08-22 08:25 UTC by minosgalanakis

## Description

Adjusts `ccm_calculate_first_block_if_ready` to return early before unnecessarily calculating  invalid context.

## PR checklist

Please remove the segment/s on either side of the | symbol as appropriate, and add any relevant link/s to the end of the line.
If the provided content is part of the present PR remove the # symbol.

- [ ] **changelog** provided | not required because: 
- [ ] **development PR** provided # | not required because: 
- [ ] **framework PR** provided Mbed-TLS/mbedtls-framework# | not required
- [ ] **3.6 PR** provided # | not required because: 
- [ ] **2.28 PR** provided # | not required because: 
- **tests**  provided | not required because: 

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

Help make review efficient:
* Multiple simple commits
  - please structure your PR into a series of small commits, each of which does one thing
* Avoid force-push
  - please do not force-push to update your PR - just add new commit(s)
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) for more details about the review process.

2024-08-22 09:27 UTC, gilles-peskine-arm commented
The CI isn't happy.

2024-08-22 13:52 UTC, gilles-peskine-arm requested changes
That's not the right return value.

2024-08-22 13:52 UTC, gilles-peskine-arm commented on tf-psa-crypto/drivers/builtin/src/ccm.c
> +            return ret;
At this point `ret` is still `MBEDTLS_ERR_ERROR_CORRUPTION_DETECTED`. And if an error was possible, we'd need to set the state to `CCM_STATE__ERROR`. (Preexisting: we should do that in the bad-mode case.)
```suggestion
            return 0;
```

2024-08-22 13:52 UTC, gilles-peskine-arm commented on tf-psa-crypto/drivers/builtin/src/ccm.c
> +            return ret;
We should update the comment. We're not just ignoring the plaintext length: we're skipping the tag calculation.

2024-08-22 15:38 UTC, gilles-peskine-arm approved these changes
LGTM

2024-09-10 13:32 UTC, eleuzi01 approved these changes
LGTM

2024-09-13 11:24 UTC, merged