[Backport 3.6] Move `config.py` functionalities to the framework
Mbed-TLS/mbedtls pull request #9511
Opened 2024-08-27 17:17 UTC by gabor-mezei-arm

## Description

Move the part of the `config.py` which is common in the TF-PSA_Crypto and the MbedTLS repo to the framework repo.

Straightforward backport of #9470 with one addition: update old class names in `depends.py`

Resolve #9325

## PR checklist

Please remove the segment/s on either side of the | symbol as appropriate, and add any relevant link/s to the end of the line.
If the provided content is part of the present PR remove the # symbol.

- [x] **changelog** provided | not required because: script change
- [x] **development PR** provided #9470 
- [x] **framework PR** provided Mbed-TLS/mbedtls-framework#41
- [x] **3.6 PR** provided: this is
- [x] **2.28 PR** provided # | not required because: not related change
- **tests**  provided

2024-09-18 16:21 UTC, davidhorstmann-arm submitted a review, later dismissed
LGTM, thanks!

I wasn't able to reproduce this with simple cherry-picking, but have been able to get close enough after resolving conflicts that I'm happy this is a faithful backport.

2024-09-19 07:12 UTC, ronald-cron-arm requested changes

2024-09-19 07:55 UTC, gabor-mezei-arm commented on scripts/config.py
> +        self.config = MbedTLSConfig(self.args.file)
The `CryptoConfig` and `CryptoConfigFile` is used in `generate_config_test.py` for test case generation. Only the `CombinedConfig` is not used.

2024-09-19 08:35 UTC, ronald-cron-arm commented on scripts/config.py
> +        self.config = MbedTLSConfig(self.args.file)
ah okay, then, let's keep them

2024-09-19 08:53 UTC, gabor-mezei-arm commented
Rebased due to recent changes caused CI failures

2024-09-19 13:45 UTC, davidhorstmann-arm approved these changes
Rebase LGTM

2024-09-20 09:06 UTC, ronald-cron-arm requested changes
A few things I'd like to clarify

2024-09-20 11:18 UTC, davidhorstmann-arm approved these changes
LGTM, thanks!

2024-09-20 16:06 UTC, ronald-cron-arm approved these changes
LGTM, thanks.

2024-09-20 18:05 UTC, merged