Adapt some all.sh components to MBEDTLS_PSA_CRYPTO_CONFIG always on
Mbed-TLS/mbedtls pull request #9549
Opened 2024-09-09 05:53 UTC by ronald-cron-arm

## Description
Adapt some all.sh components to MBEDTLS_PSA_CRYPTO_CONFIG always on
Progresses #8153.

## PR checklist
- [ ] **changelog** not required 
- [ ] **development this PR 
- [ ] **framework PR** not required
- [ ] **3.6 PR** not required, 4.0 work 
- [ ] **2.28 PR** not required, 4.0 work 
- **tests**  not required because: adaptations of some test components

2024-09-10 16:07 UTC, minosgalanakis submitted a review, later dismissed
LGTM

2024-09-11 13:19 UTC, tom-daubney-arm requested changes
A set of small nits in the comments coming from copy paste I imagine.

2024-09-11 13:19 UTC, tom-daubney-arm commented on tests/scripts/components-configuration-tls.sh
> +    # Note: The three unsets below are to be removed for Mbed TLS 4.0
Nit: there are four unsets below, rather than three

2024-09-11 13:19 UTC, tom-daubney-arm commented on tests/scripts/components-configuration-tls.sh
> +    # Note: The three unsets below are to be removed for Mbed TLS 4.0
Nit: Only two unsets here

2024-09-11 13:19 UTC, tom-daubney-arm commented on tests/scripts/components-configuration-crypto.sh
> +    # Note: The three unsets below are to be removed for Mbed TLS 4.0
Nit: Only two unsets here

2024-09-11 13:19 UTC, tom-daubney-arm commented on tests/scripts/components-configuration-crypto.sh
> +    # Note: The three unsets below are to be removed for Mbed TLS 4.0
Nit: Only two unsets here

2024-09-11 13:37 UTC, tom-daubney-arm approved these changes
LGTM - thanks for the changes!

2024-09-12 08:46 UTC, minosgalanakis approved these changes
LGTM

2024-09-12 13:32 UTC, merged