md: allow dispatch to PSA whenever CRYPTO_CLIENT is enabled
Mbed-TLS/mbedtls pull request #9562
Opened 2024-09-13 09:04 UTC by valeriosetti

## Description

Instead of allowing PSA dispatching only when CRYPTO_C is set and some MBEDTLS_PSA_ACCEL_ALG_xxx is set, we enable dispatching when CRYPTO_CLIENT and PSA_WANT_ALG_xxx are set. This makes the feature more useful in cases where the PSA support is provided externally, like for example TF-M in Zephyr.

## PR checklist

- [ ] **changelog** TBD, but I would like to have some feedback from reviewers about this change before doing it.
- [ ] **development PR** not required because, if I'm not wrong, the MD module is internal in `development`, so the user is not able to make direct usage of it.
- [ ] **framework PR** not required
- [ ] **3.6 PR** not required because this is it
- [ ] **2.28 PR** not required
- **tests**  not required because this does not affect the behavior of MD and its features are already tested

2024-09-13 09:13 UTC, valeriosetti commented
@mpg I took the liberty to add you as reviewer because you were the one who improved MD last year, allowing for the PSA dispatch, and we also discussed about this change in Slack. However if you don't have enough review bandwidth for this, please let me know and I'll remove you ;)

2024-09-16 09:22 UTC, valeriosetti commented
The ABI-API break is expected because `struct mbedtls_md_context_t` will change its size depending on `PSA_WANT_` instead of `MBEDTLS_PSA_ACCEL_` symbols.

2024-09-17 07:58 UTC, mpg commented
> * **changelog** TBD, but I would like to have some feedback from reviewers about this change before doing it.

IMO not ChangeLog for this, as support for `CLIENT && !C` is not official yet, and when it will become official it will have a ChangeLog entry with a scope much broader than just this :)

2024-09-17 07:59 UTC, mpg commented
> * **development PR** not required because, if I'm not wrong, the MD module is internal in `development`, so the user is not able to make direct usage of it.

The current plan is for MD to remain public in 4.0, so I think we want to forward-port this to development. However there might be other changes planned (or already done) in development that would make this moot, I'm not sure. Cc @gilles-peskine-arm

2024-09-17 08:05 UTC, mpg commented
> The ABI-API break is expected because `struct mbedtls_md_context_t` will change its size depending on `PSA_WANT_` instead of `MBEDTLS_PSA_ACCEL_` symbols.

Aw, I'm afraid this is a blocker. We [promise not to change the ABI in LTS branches](https://github.com/Mbed-TLS/mbedtls/blob/development/BRANCHES.md#long-time-support-branches) (which 3.6 now is) unless we can't find another way to fix a security issue. So, changing the size of `struct mbedtls_md_context_t` in the default configuration is not something we can do in 3.6.

Would there be a way to achieve what you're after while keeping the structure unchanged in the default config, and only changing it in a few specific configs?

2024-09-17 08:06 UTC, mpg requested changes
https://github.com/Mbed-TLS/mbedtls/pull/9562#issuecomment-2354827277

2024-09-17 08:39 UTC, valeriosetti commented
> The current plan is for MD to remain public in 4.0, so I think we want to forward-port this to development.

Oh, I see. I based my previous comment on the fact that `md.h` header is now in `tf-psa-crypto/drivers/builtin/include/mbedtls/md.h` which looks like a quite "hidden" place not meant to be included by end user's code directly. However I surely missed something, so please apologize for the wrong assumption.

> Would there be a way to achieve what you're after while keeping the structure unchanged in the default config, and only changing it in a few specific configs?

I think the easiest way will be to enable PSA dispatching based on PSA_WANTs only in the usual `CRYPTO_CLIENT && !CRYPTO_C` configuration. This is still relevant for Mbed TLS users like Zephyr, but it does not affect the default configuration. I will try to rework the PR in this direction.

2024-09-17 08:59 UTC, gilles-peskine-arm commented
> > The current plan is for MD to remain public in 4.0, so I think we want to forward-port this to development.
>
> Oh, I see. I based my previous comment on the fact that md.h header is now in tf-psa-crypto/drivers/builtin/include/mbedtls/md.h which looks like a quite "hidden" place not meant to be included by end user's code directly. However I surely missed something, so please apologize for the wrong assumption.

Currently all of the legacy crypto headers have moved as part of the work to split the repositories. We'll move some of them again as part of the work to evolve the API. [`md.h` will remain public](https://github.com/Mbed-TLS/mbedtls/issues/8450) (but without HMAC functionality). [Most other crypto headers will become private or unstable](https://github.com/Mbed-TLS/mbedtls/issues/8663).

2024-09-17 12:50 UTC, valeriosetti commented
> > Would there be a way to achieve what you're after while keeping the structure unchanged in the default config, and only changing it in a few specific configs?
> 
> I think the easiest way will be to enable PSA dispatching based on PSA_WANTs only in the usual `CRYPTO_CLIENT && !CRYPTO_C` configuration. This is still relevant for Mbed TLS users like Zephyr, but it does not affect the default configuration. I will try to rework the PR in this direction.

Thanks to this change the ABI-API failure disappeared and the CI is fully green now :)

2024-09-19 09:16 UTC, mpg approved these changes
LGTM, thanks!

2024-11-05 15:50 UTC, gilles-peskine-arm requested changes
I'm ok with this change in principle. And I agree that since this is targeting a configuration that is not officially supported (`MBEDTLS_PSA_CRYPTO_CLIENT` without `MBEDTLS_PSA_CRYPTO_C`), we should in principle not add a changelog entry. But still, I want more documentation for two audiences:

* For maintainers, there should be an explanation of when md dispatches to PSA in plain English (as opposed to C code spread over multiple files). This is in principle covered by `docs/architecture/psa-migration/md-cipher-dispatch.md`, though I'm not sure it was fully up to date even before this pull request. Please update that document. And I'd like a summary, or a reference to that file, at least in `md.c`.
* For users who use CLIENT without C (and who enable at least one hash), there is an incompatible change: they now need to implement `psa_can_do_hash`. We should document that somewhere, even if we keep saying that it's experimental. I guess in the documentation of `MBEDTLS_PSA_CRYPTO_CLIENT`?

Note that I'm not convinced that we shouldn't add a changelog entry. This is a long-time support branch, so the threshold for considering a change to be important it low. We do sometimes announce things like “The undocumented ability … has been removed” in the changelog. I think now is one of those times.

2024-11-06 08:31 UTC, mpg commented
Ok, I'm not opposed to a ChangeLog entry as long as it reminds readers that `CLIENT && !C` is still not officially supported.

Good point about updating the documentation, thanks for noticing!

2025-01-22 15:44 UTC, valeriosetti commented
The last force-push was mostly to reset the head of this PR on top of the current `mbedtls-3.6` because I have not been working on this PR for a long time and it was quite outdated.

2025-02-04 11:11 UTC, mpg commented
Note that the CI is failing in `test_default_psa_crypto_client_without_crypto_provider` which looks related.

2025-02-04 11:14 UTC, valeriosetti commented
> Note that the CI is failing in `test_default_psa_crypto_client_without_crypto_provider` which looks related.

Yes, this is due to a change that I recently introduced https://github.com/Mbed-TLS/mbedtls/pull/9562/commits/cf8bbb88043b0fde4911ab561c65b8677dcc24f3. To me that made sense, but apparently this is triggering a lot of failures in that test scenarios because the library code "thinks" that the PSA Crypto supports hash functions, whereas they are all stub functions. I need to think a bit more on how to overcome this problem. In the worst case I'll just drop the commit.

2025-02-04 13:53 UTC, valeriosetti commented
> > Note that the CI is failing in `test_default_psa_crypto_client_without_crypto_provider` which looks related.
> 
> Yes, this is due to a change that I recently introduced [cf8bbb8](https://github.com/Mbed-TLS/mbedtls/commit/cf8bbb88043b0fde4911ab561c65b8677dcc24f3). To me that made sense, but apparently this is triggering a lot of failures in that test scenarios because the library code "thinks" that the PSA Crypto supports hash functions, whereas they are all stub functions. I need to think a bit more on how to overcome this problem. In the worst case I'll just drop the commit.

I think I've found a workaround for the problem I mentioned above -> https://github.com/Mbed-TLS/mbedtls/compare/304bd4f3efd424f762455b226a7afa28bbdcef12..5368386524f9432fb21179e7800dfdb4c861c824.
Wdyt?

2025-02-11 11:00 UTC, valeriosetti commented
@mpg @gilles-peskine-arm the CI is green again, so the PR should be ready for another round of reviews when/if you have some spare time :)

2025-02-11 13:27 UTC, frkv commented
We deem this essential to ensure Zephyr supports TF-M out-of-the-box for TLS/DTLS and X.509 use-cases using the LTS branch (of TF-M and Mbed TLS)

Zephyr actively uses `MBEDTLS_PSA_CRYPTO_CLIENT` 

Please prioritize this for Mbed TLS 3.6.3. This seems like a very low hanging fruit for better PSA crypto adoption (and by extension essential for TF-M support)

2025-02-12 09:04 UTC, mpg requested changes
Looks pretty good to me, just a couple comments.

2025-02-12 09:04 UTC, mpg commented on library/md.c
> +    if ((status == PSA_ERROR_COMMUNICATION_FAILURE) || (status == PSA_ERROR_NOT_SUPPORTED)) {
Nice trick. However wouldn't it be safer to return 0 on _any_ error? Checking [the documentation](https://arm-software.github.io/psa-api/crypto/1.1/api/ops/hashes.html#c.psa_hash_abort) it can also return `PSA_ERROR_BAD_STATE`, and I think drivers are in theory free to return other error codes.

2025-02-12 14:21 UTC, gilles-peskine-arm requested changes
Having analyzed the design more closely (with the help of the added documentation, thanks for that), I think it's geared towards one specific integration, and putting the availability check in the wrong place. Whether a hash is available through PSA at a given time is very integration-dependent, so I think that should be the job of `psa_can_do_hash`, to be provided by the integrator in client-only builds.

So I am rejecting a design that bypasses `psa_can_do_hash` in client-only builds, unless you give a good reason why we should do it this way.

Once we converge on the design, please make a forward-port to the development branch. It doesn't matter if development isn't in its final state, just make a similar patch as if `md.h` was going to be released as is, and we'll continue from there later.

2025-02-12 14:21 UTC, gilles-peskine-arm commented on library/md.c
>      return psa_can_do_hash(alg);
Shouldn't we call `psa_can_do_hash` in the client-only case as well? I don't see why we wouldn't.

2025-02-12 14:21 UTC, gilles-peskine-arm commented on library/md.c
> +    if ((status == PSA_ERROR_COMMUNICATION_FAILURE) || (status == PSA_ERROR_NOT_SUPPORTED)) {
I'm also not sure whether this is the right set of errors, but it would make sense to treat most error codes as final. We're asking a subsystem “can you do this?” There are four kinds of answers: “yes”, “not at this time but maybe later”, “not me but maybe someone else” and “this is impossible”. Since we don't cache the result or retry in a loop, we don't care about the difference between “not at this time” and “not me”. On the other hand, “I can't” and “nobody can” are different conditions: for “I can't”, it is desirable to try another method to perform the same task; for “nobody can”, we should give up immediately.

In the driver interface, “not me” is `PSA_ERROR_NOT_SUPPORTED` (leading to trying a fallback driver if there is one) and “this is impossible” is all other error codes. (Again, there is no “not now” because there is no retry or caching mechanism.) Only `NOT_SUPPORTED` is treated as “not me” because this is what the fallback mechanism is meant for: when a driver only supports a subset of possible inputs, and there might be another driver that is (for example) slower but more featured. Other errors such as `INVALID_ARGUMENT` are fatal because they assert that the driver knows what it's doing, and it knows that the request is not valid.

Here, I think `COMMUNICATION_FAILURE` makes sense as a “not now” error: it's the most natural error code if there's a client-server mechanism but it is not available yet during system startup. (For example, in a bootloader which loads signed drivers, and needs to calculate hashes to verify the driver's signatures.) I would expect most other errors to be fatal. `BAD_STATE` would also be a reasonable error code in that case; it's a “not like this” error, and for a freshly initialized operation, the only part of “like this” that could be invalid is the system state. In particular, `NOT_SUPPORTED` means that `psa_hash_abort` is not supported at all, so whatever PSA implementation we have is not at all capable of calculating hashes. But if that's the case, then we shouldn't reach this point: all `PSA_WANT_ALG_hash` should be disabled and so `psa_alg_of_md` should have returned 0.

The set of errors that we have here is part of the contract between Mbed TLS and the PSA Crypto provider. So we should document it somewhere, and it should follow some simple rule. Since this is not an official API, we can change the rule (but we'll try not to change it without a good reason). I'm not sure what the right place is for this documentation.

All this being written: do we really need this check? My inclination would be to let the integrator worry about this. Require the integrator to implement `psa_can_do_hash`, and just use its boolean result.

2025-02-13 10:18 UTC, valeriosetti commented on library/md.c
>      return psa_can_do_hash(alg);
As discussed during the meeting `md_can_use_psa` in case of `MBEDTLS_PSA_CRYPTO_CLIENT && !MBEDTLS_PSA_CRYPTO_C` now:

- checks that the hash algorithm is supported in PSA through `psa_alg_of_md`
- checks that `psa_crypto_init` was called through the fake aborting of a freshly initialized hash operation.

Is that reasonably OK?

2025-02-18 17:28 UTC, gilles-peskine-arm requested changes
I still disagree with the proposed implementation, which looks to me like a vendor-specific trick that would be unlikely to work with other vendors.

I propose to follow the architecture proposed in the section “Improving support for `MBEDTLS_PSA_CRYPTO_CLIENT`”, unless there's a better proposal.

2025-02-18 17:28 UTC, gilles-peskine-arm commented on docs/architecture/psa-migration/md-cipher-dispatch.md
> +There is no strong reason to allow mechanisms available through legacy but not PSA when `MBEDTLS_PSA_CRYPTO_C` is enabled. This would only save at best a very small amount of code size in the PSA dis
Why did you remove the part about CLIENT here? It's still relevant.

2025-02-18 17:28 UTC, gilles-peskine-arm commented on docs/architecture/psa-migration/md-cipher-dispatch.md
> +* For ciphers `MBEDTLS_PSA_CRYPTO_CLIENT` is disabled.
This isn't specific to ciphers. If `MBEDTLS_PSA_CRYPTO_CLIENT` is disabled, then there are no `psa_xxx` functions in the build, so we can't call them.

Also, the part about drivers is still relevant.

```suggestion
* `MBEDTLS_PSA_CRYPTO_CLIENT` is disabled.
* There is a PSA driver which has not been initialized (this happens in `psa_crypto_init()`).
```

2025-02-18 17:28 UTC, gilles-peskine-arm commented on docs/architecture/psa-migration/md-cipher-dispatch.md
> +* If `MBEDTLS_PSA_CRYPTO_CLIENT && !MBEDTLS_PSA_CRYPTO_C`, `psa_can_do_hash` cannot be called because this is an Mbed TLS vendor specific addition that is not officially supported by the PSA Crypto s
I don't understand why attempting to abort an operation would be relevant. This looks to me like an implementation-specific hack. Some plausible behaviors would be incompatible with this check, such as:

* The local code of abort sees that it has no handle of an ongoing operation, so does nothing without attempting to contact the server.
* The first attempt to perform an operation attempts to open a connection. This may or may not be desirable during the early boot where a fallback may be desirable.

The considerations for “has client-server communication been initialized yet?” and “have drivers [and the keystore, if we extend this to ciphers] been initialized yet?” are similar. For “have hash/cipher drivers been initialized yet?”, we introduced `psa_can_do_hash` and `psa_can_do_cipher`. Those functions are provided by our library when `MBEDTLS_PSA_CRYPTO_C` is enabled. When only `MBEDTLS_CRYPTO_CLIENT_C` is enabled, it would make sense to require the implementation of the communication layer to provide them.

2025-02-20 18:56 UTC, gilles-peskine-arm requested changes
LGTM except that we should document `psa_can_do_hash()` since it's now an interface that client providers need to implement.

2025-02-20 18:56 UTC, gilles-peskine-arm commented on docs/architecture/psa-migration/md-cipher-dispatch.md
> +* `int psa_can_do_hash(psa_algorithm_t hash_alg)` is then used to further checking if the PSA Crypto core has been initialized or not. If so then `md_can_use_psa` will finally succeed, otherwise it w
Please add a note to explain that in client-server builds, the implementer of the client interface is expected to provide `psa_can_do_hash()`.

2025-02-20 18:56 UTC, gilles-peskine-arm commented on ChangeLog.d/9652.txt
> +     performing any PSA call.
Also the provider needs to implement `psa_can_do_hash()`. Please:

* Mention this in the changelog entry.
* Move the declaration of `psa_can_do_hash()` to a public header file, with some suitable documentation. In principle this should be a new header, to be consumed only by client providers. In practice I think we can use `include/psa/crypto_extra.h` in 3.6, in a new Doxygen group.

```
/** \defgroup psa_crypto_client Functions defined by a client provider
 *
 * The functions in this group are meant to be implemented by providers of
 * the PSA Crypto client interface. They are provided by the library when
 * #MBEDTLS_PSA_CRYPTO_C is enabled.
 *
 * \note All functions in this group are experimental, as using
 *       alternative client interface providers is experimental. 
 *
 * @{
 */
/** … */
psa_status_t psa_can_do_hash(…);
/**@}*/

```

2025-02-21 17:56 UTC, gilles-peskine-arm submitted a review, later dismissed
Thanks for updating the documentation! Looks good to me now.

2025-02-26 09:55 UTC, mpg approved these changes
LGTM, thanks!

2025-02-28 11:16 UTC, mpg commented
@valeriosetti can you update the submodule pointer now that https://github.com/Mbed-TLS/mbedtls-framework/pull/140 has been merged?

2025-02-28 11:47 UTC, mpg approved these changes

2025-02-28 11:59 UTC, gilles-peskine-arm approved these changes
LGTM after framework update

2025-02-28 12:00 UTC, gilles-peskine-arm commented
Can you please make a PR to development? Sure, the md interface will change, but that doesn't affect the changes here.

2025-02-28 13:13 UTC, gilles-peskine-arm commented
`md.h` will remain public in TF-PSA-Crypto 1.x, with a subset of functionality: just hash calculation, not HMAC or metadata. Basically the current `MBEDTLS_MD_LIGHT`.

2025-03-04 10:08 UTC, merged