PSA Crypto Configuration Split
Mbed-TLS/mbedtls pull request #9567
Opened 2024-09-16 13:36 UTC by minosgalanakis

## Description

Draft PR, for testing purposes

## PR checklist

Please remove the segment/s on either side of the | symbol as appropriate, and add any relevant link/s to the end of the line.
If the provided content is part of the present PR remove the # symbol.

- [ ] **changelog** provided | not required because: 
- [ ] **development PR** provided # | not required because: 
- [ ] **framework PR** provided Mbed-TLS/mbedtls-framework# | not required
- [ ] **3.6 PR** provided # | not required because: 
- [ ] **2.28 PR** provided # | not required because: 
- **tests**  provided | not required because: 

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

Help make review efficient:
* Multiple simple commits
  - please structure your PR into a series of small commits, each of which does one thing
* Avoid force-push
  - please do not force-push to update your PR - just add new commit(s)
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) for more details about the review process.

2024-11-18 09:46 UTC, ronald-cron-arm reviewed
I've had a first overall look. I've left a few comments. Otherwise, I think it would be beneficial to rebase on top of  #9771 now. You can then remove all MBEDTLS_PSA_CRYPTO_CONFIG. Also instead of moving MBEDTLS_USE_PSA_CRYPTO across config files, just remove it, it is not a configuration option anymore. Finally,  it would be nice to rework the changes around MBEDTLS_PSA_CRYPTO_USER/CONFIG_FILE now that the final state seems to be suitable.

2024-11-18 09:46 UTC, ronald-cron-arm commented on scripts/config.py
> -
I think we should keep this for PSA_WANT symbols.

2024-11-19 09:42 UTC, ronald-cron-arm commented on tests/scripts/all-core.sh
> +        CONFIG_CRYPTO_TEST_DRIVER_H='tests/include/test/drivers/config_test_driver_tf_psa_crypto.h'
```suggestion
        CRYPTO_CRYPTO_TEST_DRIVER_H='tests/include/test/drivers/crypto_config_test_driver.h'
```

2024-12-02 11:45 UTC, ronald-cron-arm requested changes
This looks quite good to me. I have a few minor comments. Otherwise, regarding the test_suite_config.psa_boolean errors reported by `analyze_outcomes.py`, it is just that the test cases have been moved from test_suite_config.mbedtls_boolean to test_suite_config.psa_boolean as expected and consequently they have to be moved in analyze_outcomes.py in IGNORED_TESTS from the test_suite_config.mbedtls_boolean key to the test_suite_config.psa_boolean one.

2024-12-03 07:54 UTC, ronald-cron-arm requested changes
This looks almost good to me. See my final comments. Otherwise, config-split.md reorganizes sections in mbedtls_config.h and this is not done in this PR. I have also not checked the order of the options in crypto_config.h. This PR is already big enough thus I propose to do these in a follow-up PR.

2024-12-03 07:54 UTC, ronald-cron-arm commented on tests/Makefile
> +	# with the the library's PSA_WANT_* macros
```suggestion
	# with the the library's PSA_WANT_* macros extracted from
```

2024-12-03 07:54 UTC, ronald-cron-arm commented on tests/scripts/components-build-system.sh
> +    msg "build: cmake with -DMBEDTLS_CONFIG_FILE + -DMBEDTLS_USER_CONFIG_FILE + -DTF_PSA_CRYPTO_CONFIG_FILE"
```suggestion
    msg "build: cmake with -DMBEDTLS/TF_PSA_CRYPTO_CONFIG_FILE + -DMBEDTLS/TF_PSA_CRYPTO_USER_CONFIG_FILE"
```

2024-12-03 07:54 UTC, ronald-cron-arm commented on tests/scripts/components-build-system.sh
> +    msg "build: cmake (in-tree) with -DMBEDTLS_CONFIG_FILE + -DMBEDTLS_USER_CONFIG_FILE + -DTF_PSA_CRYPTO_CONFIG_FILE"
```suggestion
    msg "build: cmake (in-tree) with -DMBEDTLS/TF_PSA_CRYPTO_CONFIG_FILE + -DMBEDTLS/TF_PSA_CRYPTO_USER_CONFIG_FILE"
```

2024-12-03 07:54 UTC, ronald-cron-arm commented on tests/ssl-opt.sh
> +    CONFIGS_ENABLED=" $(echo `$P_QUERY -l` ) "
Please add a comment above about this.

2024-12-03 07:54 UTC, ronald-cron-arm commented on tests/scripts/components-build-system.sh
> +    not programs/test/query_compile_time_config MBEDTLS_SSL_ALL_ALERT_MESSAGES
```suggestion
    not programs/test/query_compile_time_config MBEDTLS_SSL_ALL_ALERT_MESSAGES
    not programs/test/query_compile_time_config MBEDTLS_NIST_KW_C
```

2024-12-03 07:54 UTC, ronald-cron-arm commented on tests/scripts/components-build-system.sh
> +    not programs/test/query_compile_time_config MBEDTLS_SSL_ALL_ALERT_MESSAGES
```suggestion
    not programs/test/query_compile_time_config MBEDTLS_SSL_ALL_ALERT_MESSAGES
    not programs/test/query_compile_time_config MBEDTLS_NIST_KW_C
```

2024-12-03 07:54 UTC, ronald-cron-arm commented on configs/ext/tfm_mbedcrypto_config_profile_medium.h
> + * If the symbol #TF_PSA_CRYPTO_CONFIG_FILE is defined, it specifies
I forgot about it previously but we need to update configs/ext/README.md explaining the current situation where the TF-M config files are not directly from TF-M but have been adapted to the Mbed TLS configuration file split and more generally to the Mbed TLS repository split.

2024-12-03 07:54 UTC, ronald-cron-arm commented on docs/proposed/config-split.md
> +//#define MBEDTLS_MEMORY_BUFFER_ALLOC_C
Rather between MBEDTLS_MEMORY_BACKTRACE and MBEDTLS_MEMORY_DEBUG, alphabetic order.

2024-12-03 07:54 UTC, ronald-cron-arm commented on include/mbedtls/mbedtls_config.h
> + * \def MBEDTLS_SELF_TEST
Should be moved to crypto_config.h section "General and test configuration options". Same for MBEDTLS_TEST_CONSTANT_FLOW_MEMSAN, MBEDTLS_TEST_CONSTANT_FLOW_VALGRIND and MBEDTLS_TEST_HOOKS below.

2024-12-03 07:54 UTC, ronald-cron-arm commented on tf-psa-crypto/include/psa/crypto_config.h
> + * \def MBEDTLS_CIPHER_NULL_CIPHER
We need to update config-split.md accordingly.

2024-12-03 12:36 UTC, gabor-mezei-arm requested changes
Found only minor things otherwise looks good to me.

2024-12-03 12:36 UTC, gabor-mezei-arm commented on tf-psa-crypto/include/psa/crypto_config.h
Please add the section tags for the `PSA_WANT` macros.

```suggestion
/** \} name SECTION Cryptographic mechanism selection (PSA API) */

```

for Line 32:
```
/**
 * \name SECTION Cryptographic mechanism selection (PSA API)
 * 
 * \{
 */
```

2024-12-03 16:03 UTC, minosgalanakis commented
All comments have been addressed. I also cleaned up the commit history, and updated the framework pointer.

2024-12-03 18:35 UTC, ronald-cron-arm commented
@minosgalanakis  Following the merge of #9781, we now have conflicts in `configs/ext/README.md` and `include/mbedtls/mbedtls_config.h`. For `configs/ext/README.md` I propose to just keep what has been done in #9781 thus to eventually not change anything in this PR. Otherwise please rebase to fix the conflicts in `include/mbedtls/mbedtls_config.h`.

2024-12-04 07:30 UTC, ronald-cron-arm requested changes
Some suggestions for the change log.

2024-12-04 07:30 UTC, ronald-cron-arm commented on ChangeLog.d/configuration-split.txt
> +     directive, will have to specify the file's location using the build-system.
The last sentence seems too specific to me. I'd go for something more general like:
```suggestion
     To migrate custom Mbed TLS configurations where
     MBEDTLS_PSA_CRYPTO_CONFIG is disabled, you should first adapt them
     to the PSA configuration scheme based on PSA_WANT_XXX symbols
     (see psa-conditional-inclusion-c.md for more information).
     To migrate custom Mbed TLS configurations where
     MBEDTLS_PSA_CRYPTO_CONFIG is enabled, you should migrate the
     cryptographic and platform configuration options from mbedtls_config.h
     to crypto_config.h (see config-split.md for more information and configs/
     for examples).
```

2024-12-04 12:26 UTC, ronald-cron-arm approved these changes
All my comments have been addressed, the rebase looks good to me thus approving.

2024-12-04 12:26 UTC, ronald-cron-arm commented
@gabor-mezei-arm please have another look.

2024-12-04 13:17 UTC, gabor-mezei-arm approved these changes
LGTM

2024-12-04 14:43 UTC, ronald-cron-arm submitted a review, later dismissed
Last update of analyze_outcomes.py and framework pointer look good to me.

2024-12-04 14:43 UTC, ronald-cron-arm commented
@gabor-mezei-arm thanks for having another look.

2024-12-04 14:49 UTC, gabor-mezei-arm submitted a review, later dismissed
LGTM

2024-12-04 15:13 UTC, ronald-cron-arm approved these changes
LGTM

2024-12-04 18:58 UTC, merged

2024-12-08 14:00 UTC, adeaarm reviewed
LGTM (I know, already merged :) )