Update the `curves` domain to use PSA macros in `depends.py`
Mbed-TLS/mbedtls pull request #9633
Opened 2024-09-24 18:44 UTC by gabor-mezei-arm

## Description

In `depends.py` use PSA macros for the `curves` domain.

Resolve #9143
Depends on #9292 

## PR checklist

Please remove the segment/s on either side of the | symbol as appropriate, and add any relevant link/s to the end of the line.
If the provided content is part of the present PR remove the # symbol.

- [x] **changelog** not required because: test related changes
- [x] **development PR** provided: this is
- [x] **framework PR** not required
- [x] **3.6 PR** not required because: 4.0 related changes
- [x] **2.28 PR** not required because: 4.0 related changes
- **tests**  provided

2024-12-17 15:03 UTC, minosgalanakis submitted a review, later dismissed
LGTM

2025-01-08 14:54 UTC, ronald-cron-arm requested changes
One thing I am not sure about. Otherwise could you please rebase? I would like to compare the outcomes.csv to one of the nightly ones but the base is too old to get anything close to it in the CI.

2025-01-08 14:54 UTC, ronald-cron-arm commented on tests/scripts/depends.py
> +            (family_name, corrected_bit_size) = \
I am not sure why but this does not seem to work. With `key_type_family=PSA_ECC_FAMILY_SECP_K1 225` and `bit_size=225` the `corrected_bit_size` seems to be still 225, not 224 as I would expect.

2025-01-08 15:58 UTC, gilles-peskine-arm commented on tests/scripts/depends.py
> +            (family_name, corrected_bit_size) = \
[secp224k1 is not and will not be supported in TF-PSA-Crypto](https://github.com/Mbed-TLS/mbedtls/issues/3541#issuecomment-2330910903). So it doesn't really matter what this code does as long as the CI is passing — either this code isn't used or its result isn't used.

Please note that https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/122 will be merged very soon. It removes the fragments of support we currently have for secp224k1 in PSA (just a few declarations). I don't know what impact this has on the code here if any.

2025-01-08 16:35 UTC, gabor-mezei-arm commented on tests/scripts/depends.py
> +            (family_name, corrected_bit_size) = \
> Please note that [Mbed-TLS/TF-PSA-Crypto#122](https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/122) will be merged very soon. It removes the fragments of support we currently have for secp224k1 in PSA (just a few declarations). I don't know what impact this has on the code here if any.

Then this and other secp224k1 specific code can be removed.

2025-01-09 08:43 UTC, ronald-cron-arm commented on tests/scripts/depends.py
> +        curve_symbols = {symbol
Another thought, for the `cipher` domain that kind of code based on `psa_info` was necessary but for curves it seems that just something like `curve_symbols = self.config_symbols_matching(r'PSA_WANT_ECC_')` would be enough.

2025-01-14 12:20 UTC, minosgalanakis approved these changes
LGTM

2025-01-14 14:55 UTC, ronald-cron-arm requested changes
Two things I am not sure about.

2025-01-14 14:55 UTC, ronald-cron-arm commented on tests/scripts/depends.py
> +    'PSA_WANT_ECC_MONTGOMERY_448': ['-MBEDTLS_ECDSA_C',
As mentioned offline now when we run the curves tests  MBEDTLS_ECP_DP_SECP224K1_ENABLED is never disabled. It would be better if it were. We could use EXCLUSIVE_GROUPS to do the job, what do you think?

2025-01-17 13:15 UTC, ronald-cron-arm commented on tests/scripts/depends.py
> +    'PSA_WANT_ECC_MONTGOMERY_448': ['-MBEDTLS_ECDSA_C',
The second option looks good to me with the exclusion of `MBEDTLS_ECP_DP_SECP224K1_ENABLED`. That way the other curves are tested with all code related to SECP224K1 disabled and we do not run tests for SECP224K1. When the configuration option is removed, we will just remove MBEDTLS_ECP_DP_SECP224K1_ENABLED from the list of curve symbols.

2025-01-27 14:03 UTC, ronald-cron-arm approved these changes
LGTM, thanks. @minosgalanakis please have another look, thanks.

2025-01-27 14:35 UTC, ronald-cron-arm approved these changes
LGTM

2025-01-27 14:55 UTC, minosgalanakis commented on tests/scripts/depends.py
> +        def get_symbol_from_key_type(key_type_family, bit_size):
This feels a bit overcomplicated with no benefit?

What we  effectively need to do is:
`if key_type.family_name:
    bit_size = 224`
    
Instead we:

1. Declare a mapping dictionary with one entry `key_type_mapping = {('PSA_ECC_FAMILY_SECP_K1', '225'): ('PSA_ECC_FAMILY_SECP_K1', '224')}`
2. Create a limitted scope method `get_symbol_from_key_type` that either retrieves the values of afforementioned dictionary and passes them through `psa_information.finish_family_dependency` and `psa_information.psa_want_symbol` or (None, None)?
3. Create a new dictionary using dict comprehention chich is mapping everything through that function.

It feels that using a simple for-loop, and an if statement would achieve the same and be easier to maintain plus it wouln't pass Nonetypes to methods which are not equipped to handle it?

Am i missing something?

2025-01-27 14:56 UTC, minosgalanakis approved these changes
LGTM

2025-01-29 09:26 UTC, merged