Update the `hashes` domain to use PSA macros in `depends.py`
Mbed-TLS/mbedtls pull request #9634
Opened 2024-09-24 18:47 UTC by gabor-mezei-arm

## Description

In `depends.py` use PSA macros for the `hashes` domain.

Resolve #9144 
Depends on #9292 

## PR checklist

Please remove the segment/s on either side of the | symbol as appropriate, and add any relevant link/s to the end of the line.
If the provided content is part of the present PR remove the # symbol.

- [x] **changelog** not required because: test related changes
- [x] **development PR** provided this is
- [x] **framework PR** not required
- [x] **3.6 PR** not required because: 4.0 related changes
- [x] **2.28 PR** not required because: 4.0 related changes
- **tests**  provided

2025-01-17 10:00 UTC, minosgalanakis approved these changes
Looks good. Some minor non blocking comments.

2025-01-17 10:00 UTC, minosgalanakis commented on tests/scripts/depends.py
> +            # Note for update: when MBEDTLS_SHA3_C is removed the mutual_exclusion
We need a common operator to indicate things that need to be done in the documentation. Until that is decided shoud we use `TODO:` which is global?

2025-03-31 09:20 UTC, ronald-cron-arm requested changes
First, I see the grouping mechanism (or mutual_exclusion) as a improvement but not really as something necessary.

In terms of complementary domain jobs, we should have !PSA_WANT_ALG_SHA3_224 !PSA_WANT_ALG_SHA3_256 !PSA_WANT_ALG_SHA3_384 !PSA_WANT_ALG_SHA3_512. I know in all of them MBEDTLS_SHA3_C is enabled but they are not completely equivalent, we have some code guarded by only PSA_WANT_ALG_SHA3_224/256 ... In all these jobs, MBEDTLS_SHA3_C is indeed not disabled but we have the same kind of situation with !PSA_WANT_ALG_SHA_224/384 and !PSA_WANT_ALG_SHA_256/512 (sha256/512.c "enabled").

I agree that it would be nice to keep the case where MBEDTLS_SHA3_C is disabled and have on top of the above jobs, the job !(PSA_WANT_ALG_SHA3_224 PSA_WANT_ALG_SHA3_256 PSA_WANT_ALG_SHA3_384 PSA_WANT_ALG_SHA3_512) as we have currently. 

Thus we could add grouping support for complementary and exclusive domains. It should then probably be a "groups" parameter not a "mutual_exclusion" as the latter does not fit well with exclusive domains I'd say. We would have then for hashes, three groups:
- PSA_WANT_ALG_SHA3_224 + PSA_WANT_ALG_SHA3_256 + PSA_WANT_ALG_SHA3_384 + PSA_WANT_ALG_SHA3_512
- PSA_WANT_ALG_SHA_224 + PSA_WANT_ALG_SHA_256
-  PSA_WANT_ALG_SHA_384 + PSA_WANT_ALG_SHA_512

I propose to move the grouping support in another PR and here to do only the changes to reach the point where for hashes we have the following jobs:
!PSA_WANT_ALG_SHA3_224 !PSA_WANT_ALG_SHA3_256 !PSA_WANT_ALG_SHA3_384 !PSA_WANT_ALG_SHA3_512 !PSA_WANT_ALG_MD5 !PSA_WANT_ALG_RIPEMD160 !PSA_WANT_ALG_SHA_1 !PSA_WANT_ALG_SHA_224 !PSA_WANT_ALG_SHA_256 !PSA_WANT_ALG_SHA_384 !PSA_WANT_ALG_SHA_512 PSA_WANT_ALG_SHA_256 PSA_WANT_ALG_SHA_512

2025-04-25 08:18 UTC, mpg commented
> I propose to move the grouping support in another PR

Yes, I think we should really prioritize the minimal changes that are needed in order to unblock other work, and leave any improvements for a follow-up.

2025-05-07 11:31 UTC, mpg commented
@gabor-mezei-arm Thanks for updating this. Unfortunately, there are now conflicts, and also the CI has complaints about the code style. Can you fix that and then re-request a review?

As of for the other `depends.py` PR, we have a DI that depends on this, and we're under (justified IMO) pressure to close off our DI taks sooner rather than later.

2025-05-07 15:46 UTC, gabor-mezei-arm commented
The `MBEDTLS_SHA3_C` macro removal is done in #10145 and this PR depends on it.

2025-05-12 07:50 UTC, mpg commented
> The `MBEDTLS_SHA3_C` macro removal is done in #10145 and this PR depends on it.

Ah, I wasn't aware, thanks for the info!

2025-06-12 09:26 UTC, mpg commented
@minosgalanakis This is ready for re-review (and a prompt re-review would be greatly appreciated).

2025-06-13 09:02 UTC, merged