Revert move of version.h to tf-psa-crypto libray
Mbed-TLS/mbedtls pull request #9653
Opened 2024-09-30 08:07 UTC by Harry-Ramsey

This commit moves version.h back into /include/mbedtls from tf-psa-crypto/drivers/builtin/include. This commit also changes the necessary build files and scripts to generate version_features.c

This commit closes: #9620.

## PR checklist

Please remove the segment/s on either side of the | symbol as appropriate, and add any relevant link/s to the end of the line.
If the provided content is part of the present PR remove the # symbol.

- [x] **changelog** not required because: This change was for 4.0 but is now being reverted.
- [x] **development PR** provided.
- [x] **framework PR** not required.
- [x] **3.6 PR** not required because: this change was for 4.0.
- [x] **2.28 PR** not required because: this change was for 4.0
- **tests**  not required because: build configuration change.

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

Help make review efficient:
* Multiple simple commits
  - please structure your PR into a series of small commits, each of which does one thing
* Avoid force-push
  - please do not force-push to update your PR - just add new commit(s)
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) for more details about the review process.

2024-10-02 13:23 UTC, ronald-cron-arm requested changes
This looks quite good to me but we should move the version files to the TLS library (see my comments). Otherwise, please remove version_features.c from `tf-psa-crypto/drivers/builtin/src/.gitignore` and move `tf-psa-crypto/tests/suites/test_suite_version.data/function` to `tests/suites/` (thus from crypto test suites to TLS/x509 test suites).

2024-10-02 15:24 UTC, Harry-Ramsey commented on library/CMakeLists.txt
> +    version_features.c
Thanks, resolved.

2024-10-02 15:24 UTC, Harry-Ramsey commented on library/Makefile
> +	     version_features.o \
Thanks, resolved.

2024-10-03 09:39 UTC, ronald-cron-arm requested changes
Two minor things. Otherwise some CI components based on `config.py crypto` are falling when they check that TLS and x509 libraries are empty. As we move `version.o` and `version_features.o` to the TLS library we should reflect that in `config.py crypto`.
In `include_in_crypto` in `config.py` we should have something like:

```py
if name.startswith('MBEDTLS_X509_') or \                                    
   name.startswith('MBEDTLS_VERSION_') or \                                 
   name.startswith('MBEDTLS_SSL_') or \                                     
   name.startswith('MBEDTLS_KEY_EXCHANGE_'):                                
    return False                         
```

2024-10-03 10:20 UTC, Harry-Ramsey commented on library/CMakeLists.txt
> +    version.c
Thanks, addressed.

2024-10-03 10:20 UTC, Harry-Ramsey commented on library/Makefile
> +	  version.o \
Thanks, addressed.

2024-10-03 16:16 UTC, ronald-cron-arm commented
Two components failed so far as described in  #9652. This has been fixed by #9662. If you rebase these CI errors should disappear.

2024-10-07 06:37 UTC, ronald-cron-arm commented
We have issues with psasim tests as we move the version modules to libmbedtls.a and for PSASIM server we are expecting them in libmbedcrypto.a. We can fix that by adding in all.sh after line 1019 (`scripts/config.py crypto_full`) `scripts/config.py set MBEDTLS_VERSION_C` and in `tests/psa-client-server/psasim/Makefile` changing line 8 to `SERVER_LIBS := -Lserver_libs -lmbedcrypto -lmbedtls`. When we will add "version" support in TF-PSA-Crypto we will be able to remove the dependency on `libmbedtls.a`. @tom-cosgrove-arm does this seem acceptable?

2024-10-07 08:49 UTC, tom-cosgrove-arm commented
@ronald-cron-arm Yes, that would be fine.

However, as far as I am aware the Mbed TLS version support (`mbedtls_version_get_string_full()`) in PSASIM is only needed to print a sign-on message. Since that is a "nice to have", that bit could easily be removed if you wanted (maybe behind `#ifdef MBEDTLS_VERSION_C`). Ideally we would put that back when there is version support in TF-PSA-Crypto, but that's not essential

2024-10-07 09:55 UTC, ronald-cron-arm commented
> @ronald-cron-arm Yes, that would be fine.
> 
> However, as far as I am aware the Mbed TLS version support (`mbedtls_version_get_string_full()`) in PSASIM is only needed to print a sign-on message. Since that is a "nice to have", that bit could easily be removed if you wanted (maybe behind `#ifdef MBEDTLS_VERSION_C`). Ideally we would put that back when there is version support in TF-PSA-Crypto, but that's not essential

Thanks. In "tests/psa-client-server/psasim/src/server.c", in psa_server_main():
```C
#if defined(MBEDTLS_VERSION_C)
    char mbedtls_version[18];             
    mbedtls_version_get_string_full(mbedtls_version);
    SERVER_PRINT("%s", mbedtls_version);
    #endif
```
seems to fix the CI issues. It is simpler than my proposal thus @Harry-Ramsey please try that.

2024-10-08 12:16 UTC, ronald-cron-arm approved these changes
LGTM, thanks.

2024-10-08 12:17 UTC, ronald-cron-arm commented
@minosgalanakis please have a look.

2024-10-08 13:54 UTC, minosgalanakis commented on tf-psa-crypto/drivers/builtin/src/.gitignore
> -/version_features.c
Minor, the commit message is refering to the the version.c file while we are removing the _features.c.

No need to rework as its pretty obvious what is happening.

2024-10-08 13:54 UTC, minosgalanakis approved these changes
LGTM

2024-10-09 08:05 UTC, ronald-cron-arm commented
The ABI-API-checking test component indicates that "version" symbols are removed from libmbedcrypto. That's expected.

2024-10-09 09:44 UTC, merged