Fix new coverity issues
Mbed-TLS/mbedtls pull request #9721
Opened 2024-10-24 13:55 UTC by paul-elliott-arm

## Description

Fix a number of issues detected by coverity in the most recent run.

## PR checklist

Please remove the segment/s on either side of the | symbol as appropriate, and add any relevant link/s to the end of the line.
If the provided content is part of the present PR remove the # symbol.

- [ ] **changelog** ~~provided |~~ not required because: No major issues fixed
- [ ] **development PR** ~~provided # |~~ not required because: This is the development PR
- [ ] **framework PR** ~~provided Mbed-TLS/mbedtls-framework# |~~ not required : no framework changes
- [ ] **3.6 PR** provided # | not required because: TBC
- [ ] **2.28 PR** provided # | not required because: TBC
- **tests**  ~~provided |~~ not required because: Existing tests provide coverage.

2024-10-24 14:09 UTC, davidhorstmann-arm submitted a review, later dismissed
LGTM, thanks!

2024-10-24 15:40 UTC, gilles-peskine-arm requested changes
This is correct but slightly incomplete.

2024-10-24 15:40 UTC, gilles-peskine-arm commented on tf-psa-crypto/tests/suites/test_suite_ctr_drbg.function
>      AES_PSA_INIT();
This also needs to be moved below the initializations.

2024-10-24 15:40 UTC, gilles-peskine-arm commented on tests/suites/test_suite_x509write.function
> +    mbedtls_pk_init(&key);
Non-blocker: I prefer to init immediately after the declaration. The reason a lot of code has all the declarations then all the function-call initializations is that it was written for C89, but now we use C99 which allows function calls mixed with declarations.

2024-10-25 14:54 UTC, gilles-peskine-arm approved these changes
LGTM

2024-10-25 16:37 UTC, davidhorstmann-arm approved these changes
LGTM, thanks!

2024-10-25 18:25 UTC, merged